import { buildVerbalBank } from "./VerbalQuestionFactory.js";

const companies=["Aster Labs","BluePeak Systems","Cedar Analytics","DeltaWorks","Evergreen Retail","Flux Mobility"], projects=["billing migration","support automation","inventory pilot","security review","campus portal","delivery redesign"], cities=["Pune","Bengaluru","Hyderabad","Chennai","Noida","Jaipur"];
const pick=(values,v,offset=0)=>values[(v-1+offset)%values.length];

const clozeSpecs=[
 ["Cause and effect","because","although","unless","meanwhile","the release was delayed ___ the final security test exposed an unresolved dependency"],
 ["Contrast","however","therefore","similarly","because","response time improved; ___, customer satisfaction did not change"],
 ["Concession","despite","because of","unless","therefore","___ limited historical data, the model produced a stable forecast"],
 ["Condition","unless","although","because","after","the team will not migrate the archive ___ its checksum is verified"],
 ["Sequence","subsequently","nevertheless","instead","otherwise","the pilot was approved; ___, training began in all regional offices"],
 ["Addition","furthermore","in contrast","otherwise","nevertheless","the control blocks duplicate requests; ___, it records every rejected transaction"],
 ["Purpose","so that","even though","whereas","as if","access was restricted ___ only authorised reviewers could view candidate records"],
 ["Collocation: conduct an audit","conduct","manufacture","performing of","construct","the compliance unit will ___ an independent audit before renewal"],
 ["Collocation: reach consensus","reach","arrive","touch","catch","after two workshops, the stakeholders were able to ___ consensus"],
 ["Formal verb: allocate","allocate","scatter","borrow","extract","management decided to ___ additional testers to the delayed module"],
 ["Formal verb: retain","retain","detain","contain","sustain","the policy requires teams to ___ evidence for seven years"],
 ["Formal verb: infer","infer","implying","refer","transfer","from the repeated pattern, an analyst may reasonably ___ that demand is seasonal"],
 ["Precision: sustainable","sustainable","temporary","decorative","accidental","the board preferred a ___ solution whose operating cost remained affordable"],
 ["Precision: redundant","redundant","essential","innovative","scarce","the second approval became ___ after both checks were merged"],
 ["Precision: coherent","coherent","erratic","silent","partial","the final report presented a ___ argument supported by consistent evidence"],
 ["Tense consistency","had completed","completes","has complete","was complete","before the client arrived, the team ___ the recovery test"],
 ["Passive construction","was approved","approved","has approving","was approve","the revised workflow ___ by the risk committee on Friday"],
 ["Subject–verb agreement","has","have","are","were","each of the regional teams ___ submitted its readiness report"],
 ["Pronoun reference","it","they","them","their","the dashboard stopped refreshing because ___ had lost its data connection"],
 ["Relative pronoun","whose","which","whom","where","the engineer ___ recommendation was accepted led the implementation"],
 ["Parallelism","documenting","to document","documented","document","the role includes testing controls, interviewing owners and ___ exceptions"],
 ["Gerund complement","adopting","to adopted","adopt","adopted","the committee recommended ___ a single evidence template"],
 ["Infinitive complement","to revise","revising","revised","revision","the vendor agreed ___ the delivery schedule after negotiation"],
 ["Tone and diplomacy","constructively","carelessly","hostilely","vaguely","the reviewer challenged the estimate ___ and offered supporting data"],
 ["Contextual conclusion","therefore","however","although","meanwhile","all mandatory controls passed; ___, the release was authorised"],
];
const clozePatterns=clozeSpecs.map(([subtopic,correct,a,b,c,sentence],p)=>v=>({subtopic,prompt:`Read the short passage and fill the numbered blank. ${pick(companies,v)} reviewed its ${pick(projects,v,p)} in assessment cycle ${v}. The review used operational evidence rather than opinion. In its conclusion, ${sentence.replace("___","[BLANK]")}.`,correct,distractors:[a,b,c],explanation:`The surrounding clauses require ${subtopic.toLowerCase()}. “${correct}” creates the intended grammatical and logical link; the alternatives conflict with either the sentence structure or the direction of the passage.`,assessmentStyle:"multi-step",idealTimeSeconds:45}));

const jumbleTypes=["General-to-specific flow","Problem–response–result","Chronological process","Pronoun reference","Cause before consequence","Claim–evidence–conclusion","Definition before example","Question–answer sequence","Contrast development","Experiment sequence","Policy implementation","Customer journey","Risk-control chain","Data interpretation narrative","Recommendation rationale","Incident chronology","Product launch sequence","Recruitment workflow","Audit finding sequence","Training evaluation","Market-entry analysis","Technology adoption","Service recovery","Sustainability initiative","Executive summary flow"];
const permutations=[[2,0,3,1],[1,3,0,2],[3,1,2,0],[0,2,1,3],[2,3,1,0],[1,0,3,2]];
const paraJumblePatterns=jumbleTypes.map((subtopic,p)=>v=>{const company=pick(companies,v,p),project=pick(projects,v,p),city=pick(cities,v,p),canonical=[`${company} began by identifying a recurring delay in its ${project}.`,`A six-week review in ${city} then traced the delay to duplicated manual approvals.`,`After the approvals were merged, median processing time fell by ${12+p+v} percent.`,`The pilot therefore showed that simplifying the control could improve speed without weakening oversight.`],perm=permutations[(p+v-1)%permutations.length],shown=perm.map(index=>canonical[index]),correct=[0,1,2,3].map(index=>String.fromCharCode(65+perm.indexOf(index))).join("-"),distractors=[correct.split("-").reverse().join("-"),`${correct.split("-")[0]}-${correct.split("-")[2]}-${correct.split("-")[1]}-${correct.split("-")[3]}`,`${correct.split("-")[1]}-${correct.split("-")[0]}-${correct.split("-")[3]}-${correct.split("-")[2]}`];return{subtopic,prompt:`This item tests ${subtopic.toLowerCase()}. Arrange the sentences to form a coherent paragraph. ${shown.map((sentence,index)=>`${String.fromCharCode(65+index)}. ${sentence}`).join(" ")}`,correct,distractors,explanation:`The paragraph must introduce the organisation and problem, present the diagnostic evidence, state the measured result, and finish with the inference. Mapping that dependency chain to the displayed labels gives ${correct}.`,assessmentStyle:"multi-step",idealTimeSeconds:65};});

const rcTypes=["Main idea","Primary purpose","Direct detail","Numerical detail","Inference","Author's tone","Best title","Meaning in context","Cause identified","Effect observed","Evidence used","Policy implication","Valid conclusion","Unsupported statement","Sequence of events","Comparison","Problem addressed","Solution adopted","Limitation","Stakeholder response","Long-term implication","Assumption supported","Data interpretation","Summary selection","Application of passage"];
const passageFor=(p,v)=>{const company=pick(companies,v,p),project=pick(projects,v,p),city=pick(cities,v,p),before=48+p+v,after=before-(8+(p%7)),adoption=62+(p+v)%20;return{company,project,city,before,after,adoption,text:`${company} tested a redesigned workflow for its ${project} with ${120+10*v} users in ${city}. Before the change, the median completion time was ${before} minutes and users often repeated the same data entry. The redesign reused verified information and reduced median time to ${after} minutes, while ${adoption}% of participants completed the process without assistance. Managers approved a wider trial but noted that the six-week pilot did not measure long-term error rates.`};};
const rcPatterns=rcTypes.map((subtopic,p)=>v=>{const d=passageFor(p,v),family=/main idea|summary/i.test(subtopic)?0:/purpose|limitation/i.test(subtopic)?1:/direct detail|evidence used|sequence|solution adopted|stakeholder response|effect observed/i.test(subtopic)?2:/numerical|comparison|data interpretation/i.test(subtopic)?3:/inference|implication|conclusion|assumption|application/i.test(subtopic)?4:/tone/i.test(subtopic)?5:/title/i.test(subtopic)?6:/meaning/i.test(subtopic)?7:/cause|problem/i.test(subtopic)?8:9;let question,correct,distractors,why;
 if(family===0){question="What is the central idea of the passage?";correct="A pilot improved efficiency, but wider adoption still requires longer-term evidence.";distractors=["The company permanently replaced every process after one trial.","Participants rejected the redesigned process.","The pilot studied only employee satisfaction."];why="It combines the measured improvement with the explicit limitation.";}
 else if(family===1){question="Why does the author mention the six-week duration?";correct="To explain why long-term error performance remains uncertain";distractors=["To prove the trial was too expensive","To show that no users completed the process","To identify the city in which the company is based"];why="The final sentence links the duration directly to the unmeasured long-term error rate.";}
 else if(family===2){question="Which change was part of the redesign?";correct="It reused information that had already been verified.";distractors=["It removed all verification checks.","It required users to enter every field twice.","It replaced the user group with managers."];why="This detail is explicitly stated in the third sentence.";}
 else if(family===3){question="By how many minutes did median completion time fall?";correct=String(d.before-d.after);distractors=[String(d.after),String(d.before),String(d.before-d.after+4)];why=`Subtracting ${d.after} from ${d.before} gives ${d.before-d.after}.`;}
 else if(family===4){question="Which inference is best supported?";correct="Reusing verified data probably removed some repetitive work.";distractors=["The redesign eliminated every possible error.","Long-term error rates definitely improved.","Assisted users were excluded from the pilot."];why="The passage connects reused information with reduced repetition and time, but makes no absolute error claim.";}
 else if(family===5){question="Which description best matches the author's tone?";correct="Measured and cautiously positive";distractors=["Uncritically enthusiastic","Hostile and dismissive","Humorous and informal"];why="The author reports benefits while explicitly retaining a limitation.";}
 else if(family===6){question="Choose the most suitable title.";correct="A Promising Process Pilot with Evidence Still to Gather";distractors=["Why Every Pilot Must Be Rejected","The End of Data Verification","A History of the City Office"];why="The title captures both the positive pilot results and the remaining evidence gap.";}
 else if(family===7){question="What does “wider trial” most nearly mean here?";correct="Testing the redesign with a broader group or scope";distractors=["Making the screen physically wider","Ending all further evaluation","Repeating the same trial with fewer users"];why="In context, wider modifies the scope of subsequent testing.";}
 else if(family===8){question="What recurring problem did the redesign directly address?";correct="Repeated entry of the same information";distractors=["A shortage of managers","An absence of any verification","The location of the pilot office"];why="Repeated data entry is the operational problem explicitly identified before the redesign.";}
 else {question="Which statement is NOT established by the passage?";correct="The redesign reduced long-term error rates.";distractors=[`The pilot included ${120+10*v} users.`,`Median completion time decreased.`,`Managers approved a broader trial.`];why="The passage specifically says long-term error rates were not measured.";}
 return{subtopic,prompt:`Read the passage and answer the question. ${d.text} ${question}`,correct,distractors,explanation:`${why} The answer is limited to information stated or necessarily implied by the passage; stronger claims are not justified.`,assessmentStyle:"multi-step",idealTimeSeconds:80};});

const crTypes=["Necessary assumption","Strengthen the argument","Weaken the argument","Evaluate the proposal","Identify the conclusion","Identify the evidence","Find the reasoning flaw","Resolve the paradox","Inference from evidence","Course of action","Cause versus correlation","Representative sample","Alternative explanation","Analogy evaluation","Policy consequence","Decision criterion","Risk assessment","Counterexample","Principle application","Plan feasibility","Argument completion","Most useful information","Reconcile conflicting data","Scope shift","Evidence sufficiency"];
const crPatterns=crTypes.map((subtopic,p)=>v=>{const company=pick(companies,v,p),project=pick(projects,v,p),gain=10+p+v,family=/assumption/i.test(subtopic)?0:/strengthen/i.test(subtopic)?1:/weaken|alternative explanation|counterexample/i.test(subtopic)?2:/evaluate|most useful|decision criterion|risk assessment|plan feasibility/i.test(subtopic)?3:/conclusion|course of action|policy consequence|argument completion/i.test(subtopic)?4:/evidence|inference|principle application/i.test(subtopic)?5:/flaw|correlation|sample|analogy|scope shift/i.test(subtopic)?6:7;let stem,correct,distractors,why;
 if(family===0){stem=`${company} argues that automating its ${project} will reduce processing time because a pilot was ${gain}% faster. Which assumption is necessary?`;correct="The pilot's tasks and users are sufficiently similar to those in the proposed rollout.";distractors=["Every employee prefers automation.","The project has no implementation cost.","Processing time is the company's only objective."];why="Without reasonable comparability, the pilot cannot support the rollout prediction.";}
 else if(family===1){stem=`${company} claims that optional practice sessions improved assessment scores because attendees scored higher. Which fact most strengthens the claim?`;correct="Before the sessions, attendees and non-attendees had nearly identical average scores.";distractors=["Some attendees preferred morning sessions.","The assessment had four answer options.","High scorers received certificates."];why="Comparable starting ability removes a major selection-based alternative explanation.";}
 else if(family===2){stem=`A manager says extending support hours increased satisfaction because ratings rose the following month. Which fact most weakens the claim?`;correct="A major product defect was fixed during the same month.";distractors=["Support agents worked in shifts.","The rating scale ranged from one to five.","Some customers contacted support twice."];why="A simultaneous product fix offers a credible alternative cause for the higher ratings.";}
 else if(family===3){stem=`${company} plans to replace classroom onboarding with a self-paced course. Which information would be most useful for evaluating the plan?`;correct="Whether comparable new hires learn the required tasks equally well in the self-paced format";distractors=["The colour of the current training room","The CEO's preferred presentation font","The number of pages in last year's handbook"];why="The plan succeeds only if the alternative format produces comparable job readiness.";}
 else if(family===4){stem=`Customer wait time fell after ${company} introduced triage. The company should retain triage because faster responses reduce abandonment. Which statement is the conclusion?`;correct="The company should retain triage.";distractors=["Customer wait time fell.","Faster responses reduce abandonment.","Triage was introduced before wait time fell."];why="The conclusion is the recommendation supported by the remaining statements.";}
 else if(family===5){stem=`Applications rose ${gain}% after ${company} simplified its form. Which statement is direct evidence rather than an interpretation?`;correct=`Application volume rose ${gain}% after the form was simplified.`;distractors=["The old form was certainly the only barrier.","Every applicant preferred the new form.","The change will raise applications forever."];why="The measured before-and-after change is evidence; the other options add unsupported causal or universal claims.";}
 else if(family===6){stem=`One successful team used daily meetings; therefore every team will become successful if it meets daily. What is the main flaw?`;correct="It generalises from one case without ruling out other causes of success.";distractors=["It uses a numerical percentage incorrectly.","It defines daily as once per week.","It provides too many independent samples."];why="A single case cannot establish a universal causal rule.";}
 else {stem=`After a faster portal was launched, average completion time fell but the number of unfinished applications rose. Which option best resolves the apparent paradox?`;correct="The faster portal attracted many first-time users who began applications but were not yet ready to submit them.";distractors=["The portal used a different colour scheme.","Completed applications took less time.","The company measured time in minutes."];why="A changed user mix can simultaneously lower time among completions and raise unfinished starts.";}
 return{subtopic,prompt:`Assessment variant ${v}: read the argument and answer the ${subtopic.toLowerCase()} question. ${stem}`,correct,distractors,explanation:`${why} The selected option addresses the exact logical gap or task, while the alternatives are irrelevant, too strong, or merely restate background information.`,assessmentStyle:"multi-step",idealTimeSeconds:70};});

export const clozeTestsVerbalBank=()=>buildVerbalBank(clozePatterns);
export const paraJumblesVerbalBank=()=>buildVerbalBank(paraJumblePatterns);
export const readingComprehensionVerbalBank=()=>buildVerbalBank(rcPatterns);
export const criticalReasoningVerbalBank=()=>buildVerbalBank(crPatterns);
