import { buildVerbalBank } from "./VerbalQuestionFactory.js";

const companies=["Aster Labs","BluePeak Systems","Cedar Analytics","DeltaWorks","Evergreen Retail","Flux Mobility"], projects=["billing migration","support automation","inventory pilot","security review","campus portal","delivery redesign"], cities=["Pune","Bengaluru","Hyderabad","Chennai","Noida","Jaipur"];
const pick=(values,v,offset=0)=>values[(v-1+offset)%values.length];

const clozeSpecs=[
 ["Cause and effect","because","although","unless","meanwhile","the release was delayed ___ the final security test exposed an unresolved dependency"],
 ["Contrast","however","therefore","similarly","because","response time improved; ___, customer satisfaction did not change"],
 ["Concession","despite","because of","unless","therefore","___ limited historical data, the model produced a stable forecast"],
 ["Condition","unless","although","because","after","the team will not migrate the archive ___ its checksum is verified"],
 ["Sequence","subsequently","nevertheless","instead","otherwise","the pilot was approved; ___, training began in all regional offices"],
 ["Addition","furthermore","in contrast","otherwise","nevertheless","the control blocks duplicate requests; ___, it records every rejected transaction"],
 ["Purpose","so that","even though","whereas","as if","access was restricted ___ only authorised reviewers could view candidate records"],
 ["Collocation: conduct an audit","conduct","manufacture","performing of","construct","the compliance unit will ___ an independent audit before renewal"],
 ["Collocation: reach consensus","reach","arrive","touch","catch","after two workshops, the stakeholders were able to ___ consensus"],
 ["Formal verb: allocate","allocate","scatter","borrow","extract","management decided to ___ additional testers to the delayed module"],
 ["Formal verb: retain","retain","detain","contain","sustain","the policy requires teams to ___ evidence for seven years"],
 ["Formal verb: infer","infer","implying","refer","transfer","from the repeated pattern, an analyst may reasonably ___ that demand is seasonal"],
 ["Precision: sustainable","sustainable","temporary","decorative","accidental","the board preferred a ___ solution whose operating cost remained affordable"],
 ["Precision: redundant","redundant","essential","innovative","scarce","the second approval became ___ after both checks were merged"],
 ["Precision: coherent","coherent","erratic","silent","partial","the final report presented a ___ argument supported by consistent evidence"],
 ["Tense consistency","had completed","completes","has complete","was complete","before the client arrived, the team ___ the recovery test"],
 ["Passive construction","was approved","approved","has approving","was approve","the revised workflow ___ by the risk committee on Friday"],
 ["Subject–verb agreement","has","have","are","were","each of the regional teams ___ submitted its readiness report"],
 ["Pronoun reference","it","they","them","their","the dashboard stopped refreshing because ___ had lost its data connection"],
 ["Relative pronoun","whose","which","whom","where","the engineer ___ recommendation was accepted led the implementation"],
 ["Parallelism","documenting","to document","documented","document","the role includes testing controls, interviewing owners and ___ exceptions"],
 ["Gerund complement","adopting","to adopted","adopt","adopted","the committee recommended ___ a single evidence template"],
 ["Infinitive complement","to revise","revising","revised","revision","the vendor agreed ___ the delivery schedule after negotiation"],
 ["Tone and diplomacy","constructively","carelessly","hostilely","vaguely","the reviewer challenged the estimate ___ and offered supporting data"],
 ["Contextual conclusion","therefore","however","although","meanwhile","all mandatory controls passed; ___, the release was authorised"],
];
const clozePatterns=clozeSpecs.map(([subtopic,correct,a,b,c,sentence],p)=>(v,level)=>{const company=pick(companies,v),project=pick(projects,v,p),advanced=/Advanced|Challenge/.test(level),challenge=/Challenge/.test(level),context=challenge?`${company} compared the ${project} with two earlier releases, separated measured outcomes from manager opinion, and retained one unresolved limitation in the final note.`:advanced?`${company} reviewed its ${project}, compared operational evidence with interview responses, and documented one conflicting observation.`:`${company} reviewed its ${project} using operational evidence.`;return{subtopic,prompt:`Read the passage and fill the blank. ${context} ${advanced?"Although several findings were favourable, the conclusion had to preserve the exact logical relationship between the clauses.":""} ${sentence.replace("___","[BLANK]")}.`,correct,distractors:[a,b,c],explanation:`The surrounding clauses require ${subtopic.toLowerCase()}. “${correct}” creates the intended grammatical and logical link. “${a}”, “${b}” and “${c}” each fail because they reverse the relationship, violate the governing construction, or use an unsuitable register.`,assessmentStyle:"multi-step",idealTimeSeconds:advanced?65:45,shortcut:`Read the sentence before and after the blank, predict the required ${subtopic.toLowerCase()} function, and only then compare options.`,commonMistake:`Do not solve this ${subtopic.toLowerCase()} blank from the nearest word alone; passage-level direction controls the answer.`};});

const jumbleTypes=["General-to-specific flow","Problem–response–result","Chronological process","Pronoun reference","Cause before consequence","Claim–evidence–conclusion","Definition before example","Question–answer sequence","Contrast development","Experiment sequence","Policy implementation","Customer journey","Risk-control chain","Data interpretation narrative","Recommendation rationale","Incident chronology","Product launch sequence","Recruitment workflow","Audit finding sequence","Training evaluation","Market-entry analysis","Technology adoption","Service recovery","Sustainability initiative","Executive summary flow"];
const permutations=[[2,0,3,1],[1,3,0,2],[3,1,2,0],[0,2,1,3],[2,3,1,0],[1,0,3,2]];
const paraJumblePatterns=jumbleTypes.map((subtopic,p)=>(v,level)=>{
  const company=pick(companies,v,p),project=pick(projects,v,p),city=pick(cities,v,p);
  const gain=12+p+v, evidenceDays=11+(p*6)+v, family=p%5;
  const canonical=family===0
    ? [`${company} began by identifying a recurring delay in its ${project}.`,`A ${evidenceDays}-day review in ${city} traced the delay to duplicated manual approvals.`,`After the approvals were merged, median processing time fell by ${gain} percent.`,`The pilot therefore showed that simplification could improve speed without weakening oversight.`]
    : family===1
      ? [`${company} first selected one ${city} team for a controlled ${project} pilot.`,`Next, analysts recorded baseline time and error data for ${evidenceDays} days.`,`They then introduced the revised workflow while keeping staffing unchanged.`,`Finally, the before-and-after results were submitted to the governance panel.`]
      : family===2
        ? [`A resilient process is one that recovers quickly without losing essential controls.`,`For example, ${company}'s ${project} switched to a backup queue during a ${evidenceDays}-minute outage.`,`Unlike the earlier design, the backup preserved request order and audit history.`,`The incident therefore illustrates resilience rather than merely temporary availability.`]
        : family===3
          ? [`Managers asked why the ${project} was producing inconsistent results across offices.`,`The ${city} team answered that each office was interpreting one validation rule differently.`,`A controlled ${evidenceDays}-case retest using a single interpretation removed most of the variation.`,`This evidence implied that rule clarity, rather than employee effort, was the principal issue.`]
          : [`${company} proposed automating approvals in its ${project} to reduce delay.`,`Pilot data from ${evidenceDays} cases showed a ${gain} percent speed improvement under normal workloads.`,`However, the trial excluded exceptional cases requiring legal review.`,`A wider trial should therefore include those cases before full implementation.`];
  const advanced=/Advanced|Challenge/.test(level),challenge=/Challenge/.test(level);
  if(advanced)canonical.push(`The review panel scheduled a ${7+v}-day follow-up to test whether the result remained stable under a different workload.`);
  if(challenge)canonical.push(`Only if that follow-up reproduced the result would ${company} recommend extending the change beyond ${city}.`);
  const perm=advanced
    ? canonical.map((_,index)=>index).sort((a,b)=>((a*7+p+v)%canonical.length)-((b*7+p+v)%canonical.length))
    : permutations[(p+v-1)%permutations.length];
  const shown=perm.map(index=>canonical[index]);
  const correct=canonical.map((_,index)=>String.fromCharCode(65+perm.indexOf(index))).join("-");
  const parts=correct.split("-"),swapped=[...parts],paired=[...parts];
  [swapped[1],swapped[2]]=[swapped[2],swapped[1]];
  [paired[0],paired[1]]=[paired[1],paired[0]];
  [paired[2],paired[3]]=[paired[3],paired[2]];
  const distractors=[[...parts].reverse().join("-"),swapped.join("-"),paired.join("-")];
  return{subtopic,prompt:`Arrange the ${canonical.length} sentences into the most coherent paragraph. ${shown.map((sentence,index)=>`${String.fromCharCode(65+index)}. ${sentence}`).join(" ")}`,correct,distractors,explanation:`The governing structure is ${["problem → diagnosis → intervention → result","first → next → then → finally","definition → example → contrast → classification","question → explanation → test evidence → inference","proposal → supporting result → limitation → qualified recommendation"][family]}${advanced?" → follow-up test":""}${challenge?" → conditional rollout":""}. Mapping that dependency chain to the displayed labels gives ${correct}; each alternative breaks a reference, chronology or inference.`,assessmentStyle:"multi-step",idealTimeSeconds:challenge?100:advanced?85:60,shortcut:`Find the sentence that introduces all nouns independently, then lock connectors and references before arranging the remaining pair.`,commonMistake:`Do not order sentences by repeated keywords alone; in ${subtopic.toLowerCase()}, logical dependency is stronger than word overlap.`};
});

const rcTypes=["Main idea","Primary purpose","Direct detail","Numerical detail","Inference","Author's tone","Best title","Meaning in context","Cause identified","Effect observed","Evidence used","Policy implication","Valid conclusion","Unsupported statement","Sequence of events","Comparison","Problem addressed","Solution adopted","Limitation","Stakeholder response","Long-term implication","Assumption supported","Data interpretation","Summary selection","Application of passage"];
const passageFor=(p,v,level)=>{const company=pick(companies,v,p),project=pick(projects,v,p),city=pick(cities,v,p),before=48+p+v,after=before-(8+(p%7)),adoption=62+(p+v)%20,advanced=/Advanced|Challenge/.test(level),challenge=/Challenge/.test(level),sentences=[`${company} tested a redesigned workflow for its ${project} with ${120+10*v} users in ${city}.`,`Before the change, the median completion time was ${before} minutes and users often repeated the same data entry.`,`The redesign reused verified information and reduced median time to ${after} minutes, while ${adoption}% of participants completed the process without assistance.`,`Managers approved a wider trial but noted that the six-week pilot did not measure long-term error rates.`];if(advanced)sentences.splice(3,0,`Interviews suggested that experienced users valued the saved time, whereas some first-time users still needed help interpreting two technical labels.`,`Because staffing remained constant during the pilot, managers considered a simple head-count explanation unlikely, though they could not exclude seasonal changes in workload.`);if(challenge)sentences.splice(5,0,`A regional comparison complicated the result: the largest time reduction occurred in the office that had already standardised its data, while another office improved only marginally.`,`The evaluation team therefore warned that the workflow and local data quality might interact, making a single company-wide forecast premature.`);return{company,project,city,before,after,adoption,text:sentences.join(" ")};};
const rcPatterns=rcTypes.map((subtopic,p)=>(v,level)=>{const d=passageFor(p,v,level),family=/main idea|summary/i.test(subtopic)?0:/purpose|limitation/i.test(subtopic)?1:/direct detail|evidence used|sequence|solution adopted|stakeholder response|effect observed/i.test(subtopic)?2:/numerical|comparison|data interpretation/i.test(subtopic)?3:/inference|implication|conclusion|assumption|application/i.test(subtopic)?4:/tone/i.test(subtopic)?5:/title/i.test(subtopic)?6:/meaning/i.test(subtopic)?7:/cause|problem/i.test(subtopic)?8:9,advanced=/Advanced|Challenge/.test(level);let question,correct,distractors,why;
 if(family===0){question="What is the central idea of the passage?";correct="A pilot improved efficiency, but wider adoption still requires longer-term evidence.";distractors=["The company permanently replaced every process after one trial.","Participants rejected the redesigned process.","The pilot studied only employee satisfaction."];why="It combines the measured improvement with the explicit limitation.";}
 else if(family===1){question="Why does the author mention the six-week duration?";correct="To explain why long-term error performance remains uncertain";distractors=["To prove the trial was too expensive","To show that no users completed the process","To identify the city in which the company is based"];why="The final sentence links the duration directly to the unmeasured long-term error rate.";}
 else if(family===2){question="Which change was part of the redesign?";correct="It reused information that had already been verified.";distractors=["It removed all verification checks.","It required users to enter every field twice.","It replaced the user group with managers."];why="This detail is explicitly stated in the third sentence.";}
 else if(family===3){question="By how many minutes did median completion time fall?";correct=String(d.before-d.after);distractors=[String(d.after),String(d.before),String(d.before-d.after+4)];why=`Subtracting ${d.after} from ${d.before} gives ${d.before-d.after}.`;}
 else if(family===4){question="Which inference is best supported?";correct="Reusing verified data probably removed some repetitive work.";distractors=["The redesign eliminated every possible error.","Long-term error rates definitely improved.","Assisted users were excluded from the pilot."];why="The passage connects reused information with reduced repetition and time, but makes no absolute error claim.";}
 else if(family===5){question="Which description best matches the author's tone?";correct="Measured and cautiously positive";distractors=["Uncritically enthusiastic","Hostile and dismissive","Humorous and informal"];why="The author reports benefits while explicitly retaining a limitation.";}
 else if(family===6){question="Choose the most suitable title.";correct="A Promising Process Pilot with Evidence Still to Gather";distractors=["Why Every Pilot Must Be Rejected","The End of Data Verification","A History of the City Office"];why="The title captures both the positive pilot results and the remaining evidence gap.";}
 else if(family===7){question="What does “wider trial” most nearly mean here?";correct="Testing the redesign with a broader group or scope";distractors=["Making the screen physically wider","Ending all further evaluation","Repeating the same trial with fewer users"];why="In context, wider modifies the scope of subsequent testing.";}
 else if(family===8){question="What recurring problem did the redesign directly address?";correct="Repeated entry of the same information";distractors=["A shortage of managers","An absence of any verification","The location of the pilot office"];why="Repeated data entry is the operational problem explicitly identified before the redesign.";}
 else {question="Which statement is NOT established by the passage?";correct="The redesign reduced long-term error rates.";distractors=[`The pilot included ${120+10*v} users.`,`Median completion time decreased.`,`Managers approved a broader trial.`];why="The passage specifically says long-term error rates were not measured.";}
 return{subtopic,prompt:`Read the passage and answer the question. ${d.text} ${question}`,correct,distractors,explanation:`${why} The answer is limited to information stated or necessarily implied by the passage. Each rejected option either exceeds the evidence, reverses a comparison, mistakes correlation for proof, or ignores the stated limitation.`,assessmentStyle:"multi-step",idealTimeSeconds:advanced?100:75,shortcut:`For ${subtopic.toLowerCase()}, mark the exact supporting sentence and compare the scope words in the two closest options.`,commonMistake:`Do not import outside knowledge or strengthen “may” into “must”; reading-comprehension answers cannot exceed passage evidence.`};});

const crTypes=["Necessary assumption","Strengthen the argument","Weaken the argument","Evaluate the proposal","Identify the conclusion","Identify the evidence","Find the reasoning flaw","Resolve the paradox","Inference from evidence","Course of action","Cause versus correlation","Representative sample","Alternative explanation","Analogy evaluation","Policy consequence","Decision criterion","Risk assessment","Counterexample","Principle application","Plan feasibility","Argument completion","Most useful information","Reconcile conflicting data","Scope shift","Evidence sufficiency"];
const crPatterns=crTypes.map((subtopic,p)=>(v,level)=>{const company=pick(companies,v,p),project=pick(projects,v,p),gain=10+p+v,family=/assumption/i.test(subtopic)?0:/strengthen/i.test(subtopic)?1:/weaken|alternative explanation|counterexample/i.test(subtopic)?2:/evaluate|most useful|decision criterion|risk assessment|plan feasibility/i.test(subtopic)?3:/conclusion|course of action|policy consequence|argument completion/i.test(subtopic)?4:/evidence|inference|principle application/i.test(subtopic)?5:/flaw|correlation|sample|analogy|scope shift/i.test(subtopic)?6:7,advanced=/Advanced|Challenge/.test(level),challenge=/Challenge/.test(level);let stem,correct,distractors,why;
 if(family===0){stem=`${company} argues that automating its ${project} will reduce processing time because a pilot was ${gain}% faster. Which assumption is necessary?`;correct="The pilot's tasks and users are sufficiently similar to those in the proposed rollout.";distractors=["Every employee prefers automation.","The project has no implementation cost.","Processing time is the company's only objective."];why="Without reasonable comparability, the pilot cannot support the rollout prediction.";}
 else if(family===1){stem=`${company} claims that optional practice sessions improved assessment scores because attendees scored higher. Which fact most strengthens the claim?`;correct="Before the sessions, attendees and non-attendees had nearly identical average scores.";distractors=["Some attendees preferred morning sessions.","The assessment had four answer options.","High scorers received certificates."];why="Comparable starting ability removes a major selection-based alternative explanation.";}
 else if(family===2){stem=`A manager says extending support hours increased satisfaction because ratings rose the following month. Which fact most weakens the claim?`;correct="A major product defect was fixed during the same month.";distractors=["Support agents worked in shifts.","The rating scale ranged from one to five.","Some customers contacted support twice."];why="A simultaneous product fix offers a credible alternative cause for the higher ratings.";}
 else if(family===3){stem=`${company} plans to replace classroom onboarding with a self-paced course. Which information would be most useful for evaluating the plan?`;correct="Whether comparable new hires learn the required tasks equally well in the self-paced format";distractors=["The colour of the current training room","The CEO's preferred presentation font","The number of pages in last year's handbook"];why="The plan succeeds only if the alternative format produces comparable job readiness.";}
 else if(family===4){stem=`Customer wait time fell after ${company} introduced triage. The company should retain triage because faster responses reduce abandonment. Which statement is the conclusion?`;correct="The company should retain triage.";distractors=["Customer wait time fell.","Faster responses reduce abandonment.","Triage was introduced before wait time fell."];why="The conclusion is the recommendation supported by the remaining statements.";}
 else if(family===5){stem=`Applications rose ${gain}% after ${company} simplified its form. Which statement is direct evidence rather than an interpretation?`;correct=`Application volume rose ${gain}% after the form was simplified.`;distractors=["The old form was certainly the only barrier.","Every applicant preferred the new form.","The change will raise applications forever."];why="The measured before-and-after change is evidence; the other options add unsupported causal or universal claims.";}
 else if(family===6){stem=`One successful team used daily meetings; therefore every team will become successful if it meets daily. What is the main flaw?`;correct="It generalises from one case without ruling out other causes of success.";distractors=["It uses a numerical percentage incorrectly.","It defines daily as once per week.","It provides too many independent samples."];why="A single case cannot establish a universal causal rule.";}
 else {stem=`After a faster portal was launched, average completion time fell but the number of unfinished applications rose. Which option best resolves the apparent paradox?`;correct="The faster portal attracted many first-time users who began applications but were not yet ready to submit them.";distractors=["The portal used a different colour scheme.","Completed applications took less time.","The company measured time in minutes."];why="A changed user mix can simultaneously lower time among completions and raise unfinished starts.";}
 const evidenceNote=challenge?" An audit note adds that the available figures cover one quarter, include both new and experienced users, and do not by themselves establish what would happen after a company-wide rollout.":advanced?" The review panel cautions that the observation is limited to one period and that temporal sequence alone does not establish causation.":"";
 return{subtopic,prompt:`Assessment set ${v}: ${stem}${evidenceNote} Select the option that most precisely resolves the ${subtopic.toLowerCase()} task; do not assume facts outside the case.`,correct,distractors,explanation:`${why} ${advanced?"The scope note must be retained: it prevents a correlation, pilot result or isolated case from becoming an unrestricted causal claim. ":""}The selected option addresses the exact logical gap or task, while each rejected choice is irrelevant, too strong, circular, or merely restates background information.`,assessmentStyle:"multi-step",idealTimeSeconds:challenge?95:advanced?85:70,shortcut:`Identify whether ${subtopic.toLowerCase()} asks you to support, attack, infer or evaluate; then map each option to the argument's precise evidence-to-conclusion gap.`,commonMistake:`Do not choose an option merely because it discusses ${company} or the ${project}; relevance requires changing or identifying the stated inference.`};});

export const clozeTestsVerbalBank=()=>buildVerbalBank(clozePatterns);
export const paraJumblesVerbalBank=()=>buildVerbalBank(paraJumblePatterns);
export const readingComprehensionVerbalBank=()=>buildVerbalBank(rcPatterns);
export const criticalReasoningVerbalBank=()=>buildVerbalBank(crPatterns);
