import { buildVerbalBank } from "./VerbalQuestionFactory.js";

const lexicon=[
 ["abate","become less intense","diminish","intensify"],["aberration","a departure from what is normal","anomaly","conformity"],["acquiesce","accept without protest","consent","resist"],["alacrity","cheerful readiness","eagerness","reluctance"],["ambiguous","open to more than one interpretation","unclear","explicit"],["ameliorate","make a bad situation better","improve","worsen"],["anomaly","something inconsistent with the norm","irregularity","standard"],["appease","calm or satisfy a demand","pacify","provoke"],["arduous","requiring great effort","strenuous","effortless"],["austere","plain and without luxury","severe","ornate"],
 ["benevolent","well meaning and kind","charitable","malicious"],["candid","truthful and direct","frank","evasive"],["cogent","clear and convincing","compelling","unconvincing"],["concise","brief but comprehensive","succinct","verbose"],["conundrum","a difficult problem","puzzle","solution"],["corroborate","confirm with supporting evidence","substantiate","refute"],["deference","respectful submission to another's judgment","respect","defiance"],["diligent","showing careful persistent effort","industrious","negligent"],["disparate","fundamentally different","dissimilar","similar"],["eclectic","drawn from varied sources","diverse","uniform"],
 ["elusive","difficult to find or achieve","evasive","obvious"],["empirical","based on observation or experiment","observational","theoretical"],["ephemeral","lasting for a very short time","transient","enduring"],["equivocal","deliberately unclear or ambiguous","ambiguous","unequivocal"],["fastidious","very attentive to detail","meticulous","careless"],["feasible","capable of being achieved","practicable","impossible"],["frugal","careful about spending","thrifty","extravagant"],["gregarious","fond of company","sociable","reclusive"],["impartial","treating all sides fairly","unbiased","prejudiced"],["inadvertent","not resulting from deliberate intent","unintentional","deliberate"],
 ["laconic","using very few words","terse","loquacious"],["lucid","expressed clearly","intelligible","confusing"],["magnanimous","generous toward a rival","noble","petty"],["meticulous","extremely careful about details","thorough","slipshod"],["mitigate","make something harmful less severe","alleviate","aggravate"],["obdurate","stubbornly refusing to change","unyielding","amenable"],["pragmatic","focused on practical results","practical","idealistic"],["prudent","showing careful judgment","cautious","reckless"],["resilient","able to recover quickly","robust","fragile"],["scrutinise","examine very closely","inspect","overlook"],
 ["sporadic","occurring at irregular intervals","intermittent","continuous"],["tenacious","persistent in maintaining effort","determined","irresolute"],["tentative","not certain or fixed","provisional","definite"],["transparent","easy to perceive and open to scrutiny","clear","opaque"],["ubiquitous","present or found everywhere","omnipresent","rare"],["viable","capable of working successfully","workable","impracticable"],["vindicate","clear from blame using evidence","exonerate","incriminate"],["volatile","liable to change rapidly and unpredictably","unstable","stable"],["wary","showing caution about danger","cautious","careless"],["zealous","showing energetic enthusiasm","ardent","apathetic"],
 ["perfunctory","done with minimal effort or interest","cursory","thorough"],["prolific","producing a large amount","productive","unproductive"],["reconcile","restore agreement or consistency","harmonise","alienate"],["reticent","unwilling to reveal thoughts","reserved","forthcoming"],["sagacious","having good judgment","wise","foolish"],["tacit","understood without being stated","implicit","explicit"],["venerate","regard with deep respect","revere","despise"],["placate","make someone less angry","soothe","enrage"],["disseminate","spread information widely","circulate","withhold"],["exacerbate","make a problem more severe","aggravate","relieve"],
];
const modes=["Definition in context","Contextual synonym","Contextual antonym","Correct usage","Semantic precision","Register and tone","Root meaning","Meaning by contrast","Workplace vocabulary","Inference from context","Nuance selection","Near-synonym distinction","Opposite meaning","Formal replacement","Concise replacement","Evidence vocabulary","Decision vocabulary","Risk vocabulary","Communication vocabulary","Performance vocabulary","Attitude vocabulary","Change vocabulary","Frequency vocabulary","Clarity vocabulary","Advanced vocabulary"];
const other=(index,field,offset)=>lexicon[(index+offset)%lexicon.length][field];
const fillDistractors=(correct,candidates,field=0)=>{const result=[...new Set(candidates)].filter(value=>value!==correct);for(let i=0;result.length<3&&i<lexicon.length;i++){const value=lexicon[i][field];if(value!==correct&&!result.includes(value))result.push(value);}return result.slice(0,3);};

const vocabularyPatterns=modes.map((subtopic,p)=>(v,level)=>{const index=(p*6+v-1)%lexicon.length,[word,meaning,synonym,antonym]=lexicon[index],mode=p%5,advanced=/Advanced|Challenge/.test(level),challenge=/Challenge/.test(level);let prompt,correct,distractors;
 if(mode===0){prompt=`During placement case ${v} (${subtopic}), the reviewer described an exception as “${word}”. Which meaning best preserves the sentence?`;correct=meaning;distractors=[other(index,1,7),other(index,1,13),`the state of being ${antonym}`];}
 else if(mode===1){prompt=`In the ${subtopic.toLowerCase()} task for set ${v}, the panel called the proposal ${word} after checking its evidence and constraints. Which word is the closest contextual replacement?`;correct=synonym;distractors=[antonym,other(index,2,9),other(index,2,17)];}
 else if(mode===2){prompt=`For ${subtopic.toLowerCase()} item ${v}, which option expresses the opposite of “${word}” in a formal assessment passage?`;correct=antonym;distractors=[synonym,other(index,3,11),other(index,2,19)];}
 else if(mode===3){prompt=`In ${subtopic.toLowerCase()} item ${v}, select the sentence that uses “${word}” in the sense “${meaning}”.`;correct=`The assessment described the response as ${word} after reviewing all evidence.`;distractors=[`The team ${word} the invoice into a spreadsheet.`,`The ${word} was measured in kilometres.`,`They purchased three ${word} for the laboratory.`];}
 else {prompt=`An ${subtopic.toLowerCase()} report in set ${v} needs a precise formal word meaning “${meaning}”. Which option should the analyst use?`;correct=word;distractors=[lexicon[(index+5)%lexicon.length][0],lexicon[(index+12)%lexicon.length][0],antonym];}
 if(advanced)prompt=`${challenge?"The answer must preserve denotation, connotation and formal register; reject an option that is only loosely associated. ":"Use both the surrounding claim and the writer's formal tone. "}${prompt}`;
 return{subtopic,prompt,correct,distractors:fillDistractors(correct,distractors,mode===0?1:mode===4?0:2),explanation:`“${word}” means “${meaning}”; its close synonym is “${synonym}” and its contextual opposite is “${antonym}”. The selected option alone preserves denotation, direction and register; the distractors are an opposite, a merely associated term, or a word from a different semantic field.`,assessmentStyle:advanced?"multi-step":"contextual",idealTimeSeconds:challenge?65:advanced?55:40,shortcut:`Use the sentence's contrast, cause and tone clues to predict the meaning of “${word}” before viewing the options.`,commonMistake:`Do not confuse “${word}” with a visually similar or merely associated word, and do not select “${antonym}”, which reverses the intended meaning.`};});

const synonymPatterns=modes.map((label,p)=>(v,level)=>{const index=(p*6+v+17)%lexicon.length,[word,meaning,synonym,antonym]=lexicon[index],askAntonym=p%2===1,correct=askAntonym?antonym:synonym,advanced=/Advanced|Challenge/.test(level),challenge=/Challenge/.test(level),scope=challenge?"Distinguish exact semantic direction from loose association and preserve the formal register.":advanced?"Resolve the contextual meaning before testing the requested same-or-opposite relation.":"Use the stated contextual meaning.";return{subtopic:`${askAntonym?"Antonym":"Synonym"}: ${label}`,prompt:`${scope} In ${label.toLowerCase()} set ${v}, “${word}” means “${meaning}”. Choose its ${askAntonym?"contextual antonym":"closest contextual synonym"}.`,correct,distractors:fillDistractors(correct,[askAntonym?synonym:antonym,other(index,askAntonym?3:2,8),other(index,askAntonym?2:3,21)],askAntonym?3:2),explanation:`In this context, “${word}” means “${meaning}”. Its closest synonym is “${synonym}”, while “${antonym}” supplies the relevant opposite; the requested relationship therefore yields “${correct}”. The remaining terms are only loosely associated or point in the wrong semantic direction.`,assessmentStyle:advanced?"multi-step":"contextual",idealTimeSeconds:challenge?60:advanced?50:35,shortcut:`Paraphrase “${word}” as “${meaning}”, then match the requested same/opposite direction before comparing options.`,commonMistake:`Do not answer with “${askAntonym?synonym:antonym}”; it represents the ${askAntonym?"same":"opposite"} direction rather than the requested ${askAntonym?"opposite":"same"} meaning.`};});

const idioms=[
 ["break the ice","make people feel more comfortable"],["hit the nail on the head","describe the exact cause of a problem"],["burn the midnight oil","work late into the night"],["bite the bullet","face a difficult situation bravely"],["back to the drawing board","restart planning after failure"],["a blessing in disguise","an apparent problem that produces a benefit"],["beat around the bush","avoid discussing the main point"],["call it a day","stop working for the present"],["cut corners","save effort by ignoring proper standards"],["get the ball rolling","start an activity"],
 ["in the same boat","be in the same difficult situation"],["keep an eye on","monitor carefully"],["leave no stone unturned","try every possible method"],["on the same page","share the same understanding"],["pull someone's leg","joke by trying to mislead someone"],["read between the lines","infer an unstated meaning"],["rule of thumb","a practical approximate guideline"],["spill the beans","reveal secret information"],["take with a pinch of salt","treat a claim with scepticism"],["the tip of the iceberg","a small visible part of a larger issue"],
 ["under the weather","feel unwell"],["up in the air","remain undecided"],["weather the storm","survive a difficult period"],["wrap one's head around","understand something complex"],["a grey area","a situation without a clear rule"],["by the book","strictly according to rules"],["go the extra mile","make more effort than required"],["miss the boat","lose an opportunity through delay"],["raise the bar","set a higher standard"],["touch base","make brief contact to exchange updates"],
 ["in the pipeline","being prepared or developed"],["learn the ropes","learn how a job is performed"],["move the goalposts","unfairly change requirements during a process"],["think outside the box","consider unconventional solutions"],["throw in the towel","admit defeat and stop trying"],["keep something under wraps","keep information secret"],["a steep learning curve","a process requiring rapid difficult learning"],["from the ground up","starting from the most basic stage"],["in black and white","recorded clearly in writing"],["jump the gun","act before the proper time"],
 ["make ends meet","manage expenses with available income"],["put all one's eggs in one basket","risk everything on one option"],["see eye to eye","agree fully"],["sit on the fence","avoid choosing between alternatives"],["take the bull by the horns","deal directly with a difficult problem"],["through thick and thin","during both good and difficult times"],["turn a blind eye","deliberately ignore wrongdoing"],["cross that bridge when we come to it","handle a problem when it actually arises"],["get cold feet","become too nervous to proceed"],["have one's hands full","be extremely busy"],
];
const idiomPatterns=modes.map((label,p)=>(v,level)=>{const index=(p*6+v-1)%idioms.length,[idiom,meaning]=idioms[index],others=[idioms[(index+9)%idioms.length][1],idioms[(index+17)%idioms.length][1],idioms[(index+31)%idioms.length][1]],advanced=/Advanced|Challenge/.test(level),challenge=/Challenge/.test(level);let prompt,correct,distractors;if(!advanced){prompt=`During placement scenario ${v}, the project lead said the team should “${idiom}” before the client review. What does the expression mean in context?`;correct=meaning;distractors=others;}else if(!challenge){prompt=`A manager wants to convey “${meaning}” without sounding literal. Which sentence uses the intended idiom correctly?`;correct=`The manager advised the team to ${idiom} before making the final decision.`;distractors=[`The manager measured the ${idiom} and entered its weight.`,`The team purchased a new ${idiom} for the conference room.`,`The analyst converted ${idiom} into kilometres.`];}else{prompt=`In a client escalation, the lead says, “We should ${idiom}.” Which action most accurately follows that instruction?`;correct=`The team should ${meaning}.`;distractors=others.map(action=>`The team should ${action}.`);}return{subtopic:`Idiom: ${label}`,prompt,correct,distractors,explanation:`The established idiom “${idiom}” means “${meaning}”. The selected option preserves that figurative intention in the workplace context; the alternatives either interpret the phrase literally or express a different conventional idiom.`,assessmentStyle:advanced?"multi-step":"contextual",shortcut:`Replace “${idiom}” with its plain-language action before comparing the choices.`,commonMistake:`Do not interpret the individual words in “${idiom}” literally; judge its conventional meaning and the action implied by the context.`};});

const substitutions=[
 ["one who studies human societies","anthropologist"],["one who compiles dictionaries","lexicographer"],["one who loves books","bibliophile"],["one who speaks many languages","polyglot"],["one who cannot read or write","illiterate"],["a person new to a profession","novice"],["one who works without payment","volunteer"],["one who doubts accepted beliefs","sceptic"],["one who avoids other people","recluse"],["one who settles in another country","immigrant"],
 ["a speech delivered without preparation","impromptu"],["a statement open to two interpretations","ambiguous"],["a remedy for all diseases or problems","panacea"],["a place where birds are kept","aviary"],["a place where bees are kept","apiary"],["a collection of historical records","archive"],["a handwritten document","manuscript"],["an exact copy of a document","facsimile"],["a list of items to be discussed","agenda"],["a record of meeting proceedings","minutes"],
 ["government by the people","democracy"],["government by a small powerful group","oligarchy"],["absence of government or order","anarchy"],["a person who opposes war","pacifist"],["a person who believes events are predetermined","fatalist"],["something that cannot be avoided","inevitable"],["something that cannot be corrected","irreparable"],["something that cannot be heard","inaudible"],["something that cannot be read","illegible"],["something that cannot be defeated","invincible"],
 ["lasting for a very short time","ephemeral"],["present everywhere","ubiquitous"],["safe to drink","potable"],["fit to be eaten","edible"],["capable of being defended","defensible"],["worthy of imitation","exemplary"],["a decision that cannot be reversed","irrevocable"],["a statement that contradicts itself","paradox"],["a mild expression replacing a harsh one","euphemism"],["the practice of using another's work as one's own","plagiarism"],
 ["a person appointed to settle a dispute","arbitrator"],["a person who examines accounts","auditor"],["a person authorised to act for another","proxy"],["a person who starts a business venture","entrepreneur"],["a person who provides financial support","patron"],["the ability to use both hands equally well","ambidexterity"],["fear of confined spaces","claustrophobia"],["fear of heights","acrophobia"],["a journey made for a special purpose","expedition"],["a short account of an amusing incident","anecdote"],
];
const substitutionPatterns=modes.map((label,p)=>(v,level)=>{const index=(p*6+v-1)%substitutions.length,[phrase,word]=substitutions[index],otherWords=[substitutions[(index+7)%substitutions.length][1],substitutions[(index+19)%substitutions.length][1],substitutions[(index+33)%substitutions.length][1]],advanced=/Advanced|Challenge/.test(level),challenge=/Challenge/.test(level);let prompt,correct,distractors;if(!advanced){prompt=`Choose the most precise one-word substitute for “${phrase}” in assessment form ${v}.`;correct=word;distractors=otherWords;}else if(!challenge){prompt=`An editor must replace the underlined definition without changing number, register or meaning: “The panel consulted ${phrase}.” Which term is most precise?`;correct=word;distractors=otherWords;}else{prompt=`Which sentence uses “${word}” in exactly the sense “${phrase}”?`;correct=`The report used “${word}” to denote ${phrase}.`;distractors=otherWords.map(otherWord=>`The report treated “${word}” as identical to ${otherWord}.`);}return{subtopic:`One-word substitution: ${label}`,prompt,correct,distractors,explanation:`“${word}” is the established term for ${phrase}. The selected option preserves denotation, register and grammatical role; the alternatives refer to different people, objects or qualities.`,assessmentStyle:advanced?"multi-step":p<5?"direct":"contextual",shortcut:`Classify the definition as person, place, object, quality or idea, then test the exact scope of “${word}”.`,commonMistake:`Do not choose a related technical-looking term; “${word}” must replace the complete phrase without changing its meaning.`};});

export const vocabularyVerbalBank=()=>buildVerbalBank(vocabularyPatterns);
export const synonymsAntonymsVerbalBank=()=>buildVerbalBank(synonymPatterns);
export const idiomsPhrasesVerbalBank=()=>buildVerbalBank(idiomPatterns);
export const oneWordSubstitutionVerbalBank=()=>buildVerbalBank(substitutionPatterns);
