import { buildVerbalBank } from "./VerbalQuestionFactory.js";

const lexicon=[
 ["abate","become less intense","diminish","intensify"],["aberration","a departure from what is normal","anomaly","conformity"],["acquiesce","accept without protest","consent","resist"],["alacrity","cheerful readiness","eagerness","reluctance"],["ambiguous","open to more than one interpretation","unclear","explicit"],["ameliorate","make a bad situation better","improve","worsen"],["anomaly","something inconsistent with the norm","irregularity","standard"],["appease","calm or satisfy a demand","pacify","provoke"],["arduous","requiring great effort","strenuous","effortless"],["austere","plain and without luxury","severe","ornate"],
 ["benevolent","well meaning and kind","charitable","malicious"],["candid","truthful and direct","frank","evasive"],["cogent","clear and convincing","compelling","unconvincing"],["concise","brief but comprehensive","succinct","verbose"],["conundrum","a difficult problem","puzzle","solution"],["corroborate","confirm with supporting evidence","substantiate","refute"],["deference","respectful submission to another's judgment","respect","defiance"],["diligent","showing careful persistent effort","industrious","negligent"],["disparate","fundamentally different","dissimilar","similar"],["eclectic","drawn from varied sources","diverse","uniform"],
 ["elusive","difficult to find or achieve","evasive","obvious"],["empirical","based on observation or experiment","observational","theoretical"],["ephemeral","lasting for a very short time","transient","enduring"],["equivocal","deliberately unclear or ambiguous","ambiguous","unequivocal"],["fastidious","very attentive to detail","meticulous","careless"],["feasible","capable of being achieved","practicable","impossible"],["frugal","careful about spending","thrifty","extravagant"],["gregarious","fond of company","sociable","reclusive"],["impartial","treating all sides fairly","unbiased","prejudiced"],["inadvertent","not resulting from deliberate intent","unintentional","deliberate"],
 ["laconic","using very few words","terse","loquacious"],["lucid","expressed clearly","intelligible","confusing"],["magnanimous","generous toward a rival","noble","petty"],["meticulous","extremely careful about details","thorough","slipshod"],["mitigate","make something harmful less severe","alleviate","aggravate"],["obdurate","stubbornly refusing to change","unyielding","amenable"],["pragmatic","focused on practical results","practical","idealistic"],["prudent","showing careful judgment","cautious","reckless"],["resilient","able to recover quickly","robust","fragile"],["scrutinise","examine very closely","inspect","overlook"],
 ["sporadic","occurring at irregular intervals","intermittent","continuous"],["tenacious","persistent in maintaining effort","determined","irresolute"],["tentative","not certain or fixed","provisional","definite"],["transparent","easy to perceive and open to scrutiny","clear","opaque"],["ubiquitous","present or found everywhere","omnipresent","rare"],["viable","capable of working successfully","workable","impracticable"],["vindicate","clear from blame using evidence","exonerate","incriminate"],["volatile","liable to change rapidly and unpredictably","unstable","stable"],["wary","showing caution about danger","cautious","careless"],["zealous","showing energetic enthusiasm","ardent","apathetic"],
 ["perfunctory","done with minimal effort or interest","cursory","thorough"],["prolific","producing a large amount","productive","unproductive"],["reconcile","restore agreement or consistency","harmonise","alienate"],["reticent","unwilling to reveal thoughts","reserved","forthcoming"],["sagacious","having good judgment","wise","foolish"],["tacit","understood without being stated","implicit","explicit"],["venerate","regard with deep respect","revere","despise"],["placate","make someone less angry","soothe","enrage"],["disseminate","spread information widely","circulate","withhold"],["exacerbate","make a problem more severe","aggravate","relieve"],
];
const modes=["Definition in context","Contextual synonym","Contextual antonym","Correct usage","Semantic precision","Register and tone","Root meaning","Meaning by contrast","Workplace vocabulary","Inference from context","Nuance selection","Near-synonym distinction","Opposite meaning","Formal replacement","Concise replacement","Evidence vocabulary","Decision vocabulary","Risk vocabulary","Communication vocabulary","Performance vocabulary","Attitude vocabulary","Change vocabulary","Frequency vocabulary","Clarity vocabulary","Advanced vocabulary"];
const other=(index,field,offset)=>lexicon[(index+offset)%lexicon.length][field];

const vocabularyPatterns=modes.map((subtopic,p)=>v=>{const index=(p*6+v-1)%lexicon.length,[word,meaning,synonym,antonym]=lexicon[index],mode=p%5;let prompt,correct,distractors;
 if(mode===0){prompt=`During placement case ${v} (${subtopic}), the reviewer described an exception as “${word}”. Which meaning best preserves the sentence?`;correct=meaning;distractors=[other(index,1,7),other(index,1,13),`the state of being ${antonym}`];}
 else if(mode===1){prompt=`In the ${subtopic.toLowerCase()} task for set ${v}, the panel called the proposal ${word} after checking its evidence and constraints. Which word is the closest contextual replacement?`;correct=synonym;distractors=[antonym,other(index,2,9),other(index,2,17)];}
 else if(mode===2){prompt=`For ${subtopic.toLowerCase()} item ${v}, which option expresses the opposite of “${word}” in a formal assessment passage?`;correct=antonym;distractors=[synonym,other(index,3,11),other(index,2,19)];}
 else if(mode===3){prompt=`In ${subtopic.toLowerCase()} item ${v}, select the sentence that uses “${word}” in the sense “${meaning}”.`;correct=`The assessment described the response as ${word} after reviewing all evidence.`;distractors=[`The team ${word} the invoice into a spreadsheet.`,`The ${word} was measured in kilometres.`,`They purchased three ${word} for the laboratory.`];}
 else {prompt=`An ${subtopic.toLowerCase()} report in set ${v} needs a precise formal word meaning “${meaning}”. Which option should the analyst use?`;correct=word;distractors=[lexicon[(index+5)%lexicon.length][0],lexicon[(index+12)%lexicon.length][0],antonym];}
 return{subtopic,prompt,correct,distractors,explanation:`“${word}” means “${meaning}”; its close synonym is “${synonym}” and its contextual opposite is “${antonym}”. The selected option alone preserves that semantic relationship in the stated register.`,assessmentStyle:"contextual"};});

const synonymPatterns=modes.map((label,p)=>v=>{const index=(p*6+v+17)%lexicon.length,[word,meaning,synonym,antonym]=lexicon[index],askAntonym=p%2===1,correct=askAntonym?antonym:synonym;return{subtopic:`${askAntonym?"Antonym":"Synonym"}: ${label}`,prompt:`In ${label.toLowerCase()} set ${v}, choose the ${askAntonym?"antonym":"closest synonym"} of “${word}” as used here: The selection panel considered the response ${word} after reviewing the complete case file.`,correct,distractors:[askAntonym?synonym:antonym,other(index,askAntonym?3:2,8),other(index,askAntonym?2:3,21)],explanation:`In this context, “${word}” means “${meaning}”. Its closest synonym is “${synonym}”, while “${antonym}” supplies the relevant opposite; the requested relationship therefore yields “${correct}”.`,assessmentStyle:"contextual"};});

const idioms=[
 ["break the ice","make people feel more comfortable"],["hit the nail on the head","describe the exact cause of a problem"],["burn the midnight oil","work late into the night"],["bite the bullet","face a difficult situation bravely"],["back to the drawing board","restart planning after failure"],["a blessing in disguise","an apparent problem that produces a benefit"],["beat around the bush","avoid discussing the main point"],["call it a day","stop working for the present"],["cut corners","save effort by ignoring proper standards"],["get the ball rolling","start an activity"],
 ["in the same boat","be in the same difficult situation"],["keep an eye on","monitor carefully"],["leave no stone unturned","try every possible method"],["on the same page","share the same understanding"],["pull someone's leg","joke by trying to mislead someone"],["read between the lines","infer an unstated meaning"],["rule of thumb","a practical approximate guideline"],["spill the beans","reveal secret information"],["take with a pinch of salt","treat a claim with scepticism"],["the tip of the iceberg","a small visible part of a larger issue"],
 ["under the weather","feel unwell"],["up in the air","remain undecided"],["weather the storm","survive a difficult period"],["wrap one's head around","understand something complex"],["a grey area","a situation without a clear rule"],["by the book","strictly according to rules"],["go the extra mile","make more effort than required"],["miss the boat","lose an opportunity through delay"],["raise the bar","set a higher standard"],["touch base","make brief contact to exchange updates"],
 ["in the pipeline","being prepared or developed"],["learn the ropes","learn how a job is performed"],["move the goalposts","unfairly change requirements during a process"],["think outside the box","consider unconventional solutions"],["throw in the towel","admit defeat and stop trying"],["keep something under wraps","keep information secret"],["a steep learning curve","a process requiring rapid difficult learning"],["from the ground up","starting from the most basic stage"],["in black and white","recorded clearly in writing"],["jump the gun","act before the proper time"],
 ["make ends meet","manage expenses with available income"],["put all one's eggs in one basket","risk everything on one option"],["see eye to eye","agree fully"],["sit on the fence","avoid choosing between alternatives"],["take the bull by the horns","deal directly with a difficult problem"],["through thick and thin","during both good and difficult times"],["turn a blind eye","deliberately ignore wrongdoing"],["cross that bridge when we come to it","handle a problem when it actually arises"],["get cold feet","become too nervous to proceed"],["have one's hands full","be extremely busy"],
];
const idiomPatterns=modes.map((label,p)=>v=>{const index=(p*6+v-1)%idioms.length,[idiom,meaning]=idioms[index],others=[idioms[(index+9)%idioms.length][1],idioms[(index+17)%idioms.length][1],idioms[(index+31)%idioms.length][1]];return{subtopic:`Idiom: ${label}`,prompt:`During placement scenario ${v}, the project lead used the expression “${idiom}” while discussing the client review. What does the expression mean?`,correct:meaning,distractors:others,explanation:`The established idiom “${idiom}” means “${meaning}”. It is figurative rather than literal, and the workplace setting does not change its conventional meaning.`,assessmentStyle:"contextual"};});

const substitutions=[
 ["one who studies human societies","anthropologist"],["one who compiles dictionaries","lexicographer"],["one who loves books","bibliophile"],["one who speaks many languages","polyglot"],["one who cannot read or write","illiterate"],["a person new to a profession","novice"],["one who works without payment","volunteer"],["one who doubts accepted beliefs","sceptic"],["one who avoids other people","recluse"],["one who settles in another country","immigrant"],
 ["a speech delivered without preparation","impromptu"],["a statement open to two interpretations","ambiguous"],["a remedy for all diseases or problems","panacea"],["a place where birds are kept","aviary"],["a place where bees are kept","apiary"],["a collection of historical records","archive"],["a handwritten document","manuscript"],["an exact copy of a document","facsimile"],["a list of items to be discussed","agenda"],["a record of meeting proceedings","minutes"],
 ["government by the people","democracy"],["government by a small powerful group","oligarchy"],["absence of government or order","anarchy"],["a person who opposes war","pacifist"],["a person who believes events are predetermined","fatalist"],["something that cannot be avoided","inevitable"],["something that cannot be corrected","irreparable"],["something that cannot be heard","inaudible"],["something that cannot be read","illegible"],["something that cannot be defeated","invincible"],
 ["lasting for a very short time","ephemeral"],["present everywhere","ubiquitous"],["safe to drink","potable"],["fit to be eaten","edible"],["capable of being defended","defensible"],["worthy of imitation","exemplary"],["a decision that cannot be reversed","irrevocable"],["a statement that contradicts itself","paradox"],["a mild expression replacing a harsh one","euphemism"],["the practice of using another's work as one's own","plagiarism"],
 ["a person appointed to settle a dispute","arbitrator"],["a person who examines accounts","auditor"],["a person authorised to act for another","proxy"],["a person who starts a business venture","entrepreneur"],["a person who provides financial support","patron"],["the ability to use both hands equally well","ambidexterity"],["fear of confined spaces","claustrophobia"],["fear of heights","acrophobia"],["a journey made for a special purpose","expedition"],["a short account of an amusing incident","anecdote"],
];
const substitutionPatterns=modes.map((label,p)=>v=>{const index=(p*6+v-1)%substitutions.length,[phrase,word]=substitutions[index];return{subtopic:`One-word substitution: ${label}`,prompt:`Choose the most precise one-word substitute for “${phrase}” in assessment form ${v}.`,correct:word,distractors:[substitutions[(index+7)%substitutions.length][1],substitutions[(index+19)%substitutions.length][1],substitutions[(index+33)%substitutions.length][1]],explanation:`“${word}” is the established term for ${phrase}. The alternatives denote different people, objects or qualities and therefore cannot replace the full expression precisely.`,assessmentStyle:p<5?"direct":"contextual"};});

export const vocabularyVerbalBank=()=>buildVerbalBank(vocabularyPatterns);
export const synonymsAntonymsVerbalBank=()=>buildVerbalBank(synonymPatterns);
export const idiomsPhrasesVerbalBank=()=>buildVerbalBank(idiomPatterns);
export const oneWordSubstitutionVerbalBank=()=>buildVerbalBank(substitutionPatterns);
