import { buildPlacementBank, numberLabel } from "./PlacementQuestionFactory.js";

const direct="direct",reverse="reverse",multi="multi-step",contextual="contextual";
const pi=Math.PI;
const sq=v=>`${numberLabel(v)} square units`;
const cube=v=>`${numberLabel(v)} cubic units`;

const algebraPatterns=[
v=>{const x=4+v,a=3+v,b=5+v,c=a*x+b;return{subtopic:"Linear equation",prompt:`Solve the equation ${a}x + ${b} = ${c} for x.`,answer:x,distractors:[(c+b)/a,c/a,x+1],solution:`Subtract ${b} from both sides, then divide by ${a}: x = (${c}-${b})/${a} = ${x}.`,assessmentStyle:direct};},
v=>{const x=5+v,a=2+v,b=3+v,c=a*(x+b);return{subtopic:"Equation with brackets",prompt:`An assessment equation is ${a}(x + ${b}) = ${c}. Determine x.`,answer:x,distractors:[c/a,x+b,x-1],solution:`Divide both sides by ${a} to get x+${b}=${c/a}; subtract ${b}, giving x=${x}.`,assessmentStyle:direct};},
v=>{const x=6+v,a=2+v,b=3+v,c=4+v,d=(a*x+b)/c;return{subtopic:"Fractional linear equation",prompt:`Find x if (${a}x + ${b})/${c} = ${numberLabel(d)}.`,answer:x,distractors:[(d-b)/a,d*c/a,x+2],solution:`Multiply by ${c}: ${a}x+${b}=${numberLabel(d*c)}. Subtract ${b} and divide by ${a}; x=${x}.`,assessmentStyle:direct};},
v=>{const x=5+v,y=3+v,a=2+v,b=3+v,c=a*x+b*y,d=x-y;return{subtopic:"Simultaneous equations",prompt:`Two variables satisfy ${a}x + ${b}y = ${c} and x - y = ${d}. Find x.`,answer:x,distractors:[y,x+y,x-1],solution:`From x-y=${d}, write x=y+${d}. Substitute into ${a}x+${b}y=${c}, solve y=${y}, then x=${x}.`,assessmentStyle:multi};},
v=>{const x=4+v,a=2+v,b=3+v,c=4+v,d=5+v,e=a*x+b*(c*x-d);return{subtopic:"Nested linear expression",prompt:`Solve ${a}x + ${b}(${c}x - ${d}) = ${e}.`,answer:x,distractors:[e/(a+b*c),x+d,x-1],solution:`Expand to ${a}x+${b*c}x-${b*d}=${e}; add ${b*d}, combine coefficients ${a+b*c}, and divide to get x=${x}.`,assessmentStyle:multi};},
v=>{const r=2+v,s=5+v,sum=(r+s)*(3+v),unit=sum/(r+s),ans=r*unit;return{subtopic:"Ratio-based equation",prompt:`Two project allocations are in the ratio ${r}:${s} and together total ${sum} units. Find the smaller allocation.`,answer:ans,distractors:[s*unit,sum/2,unit],solution:`Total ratio parts = ${r}+${s}. One part = ${sum}/(${r}+${s})=${unit}; smaller allocation = ${r}*${unit}=${ans}.`,assessmentStyle:contextual};},
v=>{const n=8+v,sum=3*n+3;return{subtopic:"Consecutive integers",prompt:`Three consecutive integers have a sum of ${sum}. Find the middle integer.`,answer:n+1,distractors:[n,n+2,sum/3+1],solution:`Let integers be n,n+1,n+2. Their sum is 3n+3=${sum}; solving gives n=${n}, so the middle value is ${n+1}.`,assessmentStyle:reverse};},
v=>{const tens=3+v,ones=1+v,diff=(10*tens+ones)-(10*ones+tens);return{subtopic:"Two-digit number reversal",prompt:`A two-digit number has tens digit ${tens} and units digit ${ones}. By how much does the number exceed the number formed by reversing its digits?`,answer:diff,distractors:[tens-ones,10*(tens-ones),diff+9],solution:`Original = 10*${tens}+${ones}; reversed = 10*${ones}+${tens}. Subtract to get ${diff}.`,assessmentStyle:direct};},
v=>{const r1=2+v,r2=5+v,b=-(r1+r2),c=r1*r2;return{subtopic:"Quadratic roots",prompt:`One root of x^2 ${b<0?"-":"+"} ${Math.abs(b)}x + ${c} = 0 is ${r1}. Find the other root.`,answer:r2,distractors:[r1+r2,r1*r2,r2+1],solution:`For x^2+bx+c=0, product of roots = c. Other root = ${c}/${r1} = ${r2}; the sum check is ${r1}+${r2}=${-b}.`,assessmentStyle:reverse};},
v=>{const r1=3+v,r2=6+v,sum=r1+r2;return{subtopic:"Sum of quadratic roots",prompt:`Without solving fully, find the sum of roots of x^2 - ${sum}x + ${r1*r2} = 0.`,answer:sum,distractors:[r1*r2,-sum,sum+2],solution:`For ax^2+bx+c=0, root sum = -b/a. Here b=-${sum} and a=1, so the sum is ${sum}.`,assessmentStyle:direct};},
v=>{const x=5+v,y=2+v,a=x*x-y*y;return{subtopic:"Difference of squares",prompt:`Evaluate ${x}^2 - ${y}^2 using an algebraic identity.`,answer:a,distractors:[(x-y)**2,x*x+y*y,a+2],solution:`Use x^2-y^2=(x-y)(x+y): (${x}-${y})*(${x}+${y})=${a}.`,assessmentStyle:direct};},
v=>{const a=3+v,b=2+v,value=a+b,square=value*value;return{subtopic:"Square identity application",prompt:`If a = ${a} and b = ${b}, calculate (a + b)^2.`,answer:square,distractors:[a*a+b*b,2*a*b,square+2],solution:`(a+b)^2=a^2+2ab+b^2. Substitution gives ${a*a}+${2*a*b}+${b*b}=${square}.`,assessmentStyle:direct};},
v=>{const base=2+v%3,p=3+v,q=2+v,ans=base**(p+q);return{subtopic:"Laws of indices",prompt:`Simplify and evaluate ${base}^${p} x ${base}^${q}.`,answer:ans,distractors:[base**(p*q),base**(p-q),ans+base],solution:`For equal bases, add exponents: ${base}^(${p}+${q}) = ${base}^${p+q} = ${ans}.`,assessmentStyle:direct};},
v=>{const n=4+v;return{subtopic:"Surd simplification",prompt:`Simplify sqrt(${n*n*5}) and give the numerical coefficient of sqrt(5).`,answer:n,distractors:[n*n,5,n+1],solution:`Factor ${n*n*5}=${n*n}*5. Therefore sqrt(${n*n*5})=${n}sqrt(5), so the coefficient is ${n}.`,assessmentStyle:contextual};},
v=>{const first=3+v,d=2+v,n=8+v,ans=first+(n-1)*d;return{subtopic:"Arithmetic progression nth term",prompt:`An arithmetic progression starts at ${first} with common difference ${d}. Find its ${n}th term.`,answer:ans,distractors:[first+n*d,n*d,ans+d],solution:`a_n=a+(n-1)d=${first}+(${n}-1)*${d}=${ans}.`,assessmentStyle:contextual};},
v=>{const first=4+v,d=3+v,n=10+v,ans=n/2*(2*first+(n-1)*d);return{subtopic:"Arithmetic progression sum",prompt:`Find the sum of the first ${n} terms of an AP whose first term is ${first} and common difference is ${d}.`,answer:ans,distractors:[n*(first+(n-1)*d),first+n*d,ans+n],solution:`S_n=n/2[2a+(n-1)d]=${n}/2[2*${first}+(${n}-1)*${d}]=${ans}.`,assessmentStyle:multi};},
v=>{const first=2+v,r=2,n=5+v%2,ans=first*r**(n-1);return{subtopic:"Geometric progression nth term",prompt:`A geometric progression has first term ${first} and common ratio ${r}. Find its ${n}th term.`,answer:ans,distractors:[first*r*n,first*r**n,ans+r],solution:`a_n=ar^(n-1)=${first}*${r}^(${n}-1)=${ans}.`,assessmentStyle:contextual};},
v=>{const first=2+v,r=2,n=5+v%2,ans=first*(r**n-1)/(r-1);return{subtopic:"Geometric progression sum",prompt:`Calculate the sum of the first ${n} terms of a GP with first term ${first} and common ratio ${r}.`,answer:ans,distractors:[first*r**(n-1),first*(r**n),ans+first],solution:`S_n=a(r^n-1)/(r-1)=${first}*(${r}^${n}-1)/(${r}-1)=${ans}.`,assessmentStyle:multi};},
v=>{const low=2+v,high=10+v,ans=high-low-1;return{subtopic:"Integer solutions of inequality",prompt:`How many integers x satisfy ${low} < x < ${high}?`,answer:ans,distractors:[high-low,high-low+1,ans-1],solution:`The eligible integers run from ${low+1} through ${high-1}. Count = (${high}-1)-(${low}+1)+1=${ans}.`,assessmentStyle:reverse};},
v=>{const x=3+v,a=2+v,b=5+v,fx=a*x+b,input=x+1,ans=a*input+b;return{subtopic:"Function evaluation",prompt:`For f(x) = ${a}x + ${b}, first compute f(${x}) and then determine f(${x}+1). What is the second value?`,answer:ans,distractors:[fx,fx+1,a*x+b+1],solution:`Use the requested second input ${input}: f(${input})=${a}*${input}+${b}=${ans}. The earlier value f(${x})=${fx} is only an intermediate check.`,assessmentStyle:multi};},
v=>{const x=2+v,f=z=>2*z+3,g=z=>z*z,ans=f(g(x));return{subtopic:"Composite functions",prompt:`Let f(x)=2x+3 and g(x)=x^2. Find f(g(${x})).`,answer:ans,distractors:[g(f(x)),f(x)*g(x),ans+2],solution:`First g(${x})=${x*x}. Then f(${x*x})=2*${x*x}+3=${ans}.`,assessmentStyle:multi};},
v=>{const k=6+v,x=4+v,y=k*x,newX=x+3,ans=k*newX;return{subtopic:"Direct variation",prompt:`A quantity y varies directly with x. When x=${x}, y=${y}. Find y when x=${newX}.`,answer:ans,distractors:[y*newX,y+k,ans+k],solution:`Direct variation gives y=kx. Constant k=${y}/${x}=${k}; at x=${newX}, y=${k}*${newX}=${ans}.`,assessmentStyle:reverse};},
v=>{const x=4+v,y=60+10*v,k=x*y,newX=x+2,ans=k/newX;return{subtopic:"Inverse variation",prompt:`A quantity y varies inversely with x. If y=${y} when x=${x}, what is y when x=${newX}?`,answer:ans,distractors:[y*newX/x,k*newX,ans+5],solution:`Inverse variation means xy=k. Here k=${x}*${y}=${k}; new y=${k}/${newX}=${numberLabel(ans)}.`,assessmentStyle:reverse};},
v=>{const fixed=500+50*v,unit=20+v,q=30+v,revenue=45+v,profit=revenue*q-(fixed+unit*q);return{subtopic:"Cost-revenue equation",prompt:`A unit has fixed cost Rs ${fixed}, variable cost Rs ${unit} per item, and sells ${q} items at Rs ${revenue} each. Calculate its profit.`,answer:profit,distractors:[revenue*q-unit*q,fixed+unit*q,profit+fixed],solution:`Revenue=${revenue}*${q}. Total cost=${fixed}+${unit}*${q}. Profit = revenue-total cost = ${revenue*q}-(${fixed}+${unit*q})=${profit}.`,assessmentStyle:multi};},
v=>{const n=5+v,perimeter=4*n+8,ans=n+2;return{subtopic:"Algebraic geometry model",prompt:`A rectangle has length x+2 and width x. Its perimeter is ${perimeter} units. Find its length.`,answer:ans,distractors:[n,perimeter/2,ans+2],solution:`2[(x+2)+x]=${perimeter}; expand to 4x+4=${perimeter}, so x=${n}. Length x+2=${ans}.`,assessmentStyle:reverse};},
];

const mensurationPatterns=[
v=>{const l=10+v,w=6+v,a=l*w;return{subtopic:"Rectangle area",prompt:`A rectangular workspace measures ${l} units by ${w} units. Find its area.`,answer:a,distractors:[2*(l+w),l+w,a+l],format:sq,solution:`Area = length*width = ${l}*${w}=${a} square units.`,assessmentStyle:direct};},
v=>{const l=12+v,w=7+v,a=2*(l+w);return{subtopic:"Rectangle perimeter",prompt:`Find the perimeter of a rectangle with length ${l} units and width ${w} units.`,answer:a,distractors:[l*w,l+w,a+2],solution:`Perimeter=2(length+width)=2*(${l}+${w})=${a} units.`,assessmentStyle:direct};},
v=>{const side=5+v,diag=side*Math.sqrt(2);return{subtopic:"Square diagonal",prompt:`A square has side ${side} units. Calculate the length of its diagonal.`,answer:diag,distractors:[2*side,side*side,diag+1],solution:`By Pythagoras, diagonal=sqrt(${side}^2+${side}^2)=${side}sqrt(2)=${numberLabel(diag)} units.`,assessmentStyle:direct};},
v=>{const b=12+2*v,h=8+v,a=b*h/2;return{subtopic:"Triangle area",prompt:`A triangle has base ${b} units and perpendicular height ${h} units. Find its area.`,answer:a,distractors:[b*h,b+h,a+h],format:sq,solution:`Area=1/2*base*height=1/2*${b}*${h}=${a} square units.`,assessmentStyle:direct};},
v=>{const a=5+v,b=6+v,c=7+v,s=(a+b+c)/2,area=Math.sqrt(s*(s-a)*(s-b)*(s-c));return{subtopic:"Heron formula",prompt:`A triangular plot has sides ${a}, ${b}, and ${c} units. Find its area using Heron's formula.`,answer:area,distractors:[a*b/2,s,area+2],format:sq,solution:`Semiperimeter s=(${a}+${b}+${c})/2=${s}. Area=sqrt[s(s-a)(s-b)(s-c)]=${numberLabel(area)} square units.`,assessmentStyle:contextual};},
v=>{const side=6+v,a=Math.sqrt(3)/4*side*side;return{subtopic:"Equilateral triangle area",prompt:`An equilateral metal plate has side ${side} units. Find the sheet area required to manufacture one plate.`,answer:a,distractors:[side*side/2,Math.sqrt(3)/2*side,a+2],format:sq,solution:`Area=sqrt(3)/4*a^2=sqrt(3)/4*${side}^2=${numberLabel(a)} square units.`,assessmentStyle:contextual};},
v=>{const r=5+v,a=pi*r*r;return{subtopic:"Circle area",prompt:`A circular component has radius ${r} units. Calculate its area using pi.`,answer:a,distractors:[2*pi*r,pi*r,a+pi],format:sq,solution:`Area=pi*r^2=pi*${r}^2=${numberLabel(a)} square units.`,assessmentStyle:direct};},
v=>{const r=6+v,a=2*pi*r;return{subtopic:"Circle circumference",prompt:`A circular garden has radius ${r} units. Find the fencing length required for one complete boundary.`,answer:a,distractors:[pi*r*r,pi*r,a+2],solution:`Circumference=2*pi*r=2*pi*${r}=${numberLabel(a)} units.`,assessmentStyle:contextual};},
v=>{const r=7+v,a=pi*r+2*r;return{subtopic:"Semicircle perimeter",prompt:`A semicircular boundary has radius ${r} units. Find its complete perimeter including the diameter.`,answer:a,distractors:[pi*r,2*pi*r,a+2],solution:`Complete perimeter = semicircular arc pi*r + diameter 2r = pi*${r}+2*${r}=${numberLabel(a)} units.`,assessmentStyle:multi};},
v=>{const r=8+v,angle=60+15*v,a=angle/360*pi*r*r;return{subtopic:"Sector area",prompt:`A circle of radius ${r} units contains a sector of ${angle} degrees. Find the sector's area.`,answer:a,distractors:[angle/360*2*pi*r,pi*r*r,a+5],format:sq,solution:`Sector area=angle/360*pi*r^2=${angle}/360*pi*${r}^2=${numberLabel(a)} square units.`,assessmentStyle:contextual};},
v=>{const r=9+v,angle=45+15*v,a=angle/360*2*pi*r;return{subtopic:"Arc length",prompt:`Calculate the arc length subtended by ${angle} degrees in a circle of radius ${r} units.`,answer:a,distractors:[angle/360*pi*r*r,2*pi*r,a+2],solution:`Arc length=angle/360*2*pi*r=${angle}/360*2*pi*${r}=${numberLabel(a)} units.`,assessmentStyle:contextual};},
v=>{const a=10+v,b=16+v,h=7+v,area=(a+b)*h/2;return{subtopic:"Trapezium area",prompt:`The parallel sides of a trapezium are ${a} and ${b} units, with height ${h} units. Find its area.`,answer:area,distractors:[(a+b)*h,a*b/2,area+h],format:sq,solution:`Area=1/2*(sum of parallel sides)*height=1/2*(${a}+${b})*${h}=${area}.`,assessmentStyle:contextual};},
v=>{const d1=12+2*v,d2=16+2*v,a=d1*d2/2;return{subtopic:"Rhombus area",prompt:`A rhombus has diagonals ${d1} and ${d2} units. Calculate its area.`,answer:a,distractors:[d1*d2,d1+d2,a+4],format:sq,solution:`Area=1/2*d1*d2=1/2*${d1}*${d2}=${a} square units.`,assessmentStyle:contextual};},
v=>{const l=30+2*v,w=20+v,path=2+v%2,outer=(l+2*path)*(w+2*path),inner=l*w,a=outer-inner;return{subtopic:"Path around rectangle",prompt:`A ${path}-unit-wide path is built outside a ${l} by ${w} rectangular lawn. Find the area of the path.`,answer:a,distractors:[2*(l+w)*path,outer,inner],format:sq,solution:`Outer dimensions=(${l}+2*${path}) by (${w}+2*${path}). Path area=outer area-inner area=${outer}-${inner}=${a}.`,assessmentStyle:multi};},
v=>{const r=4+v,h=10+v,a=pi*r*r*h;return{subtopic:"Cylinder volume",prompt:`A cylindrical tank has radius ${r} units and height ${h} units. Find its volume.`,answer:a,distractors:[2*pi*r*h,2*pi*r*(r+h),a+10],format:cube,solution:`Volume=pi*r^2*h=pi*${r}^2*${h}=${numberLabel(a)} cubic units.`,assessmentStyle:direct};},
v=>{const r=5+v,h=12+v,a=2*pi*r*h;return{subtopic:"Cylinder curved surface",prompt:`A cylindrical container has radius ${r} units and height ${h} units. Find the label area needed to cover only its curved side.`,answer:a,distractors:[pi*r*r*h,2*pi*r*(r+h),a+10],format:sq,solution:`Curved surface area=2*pi*r*h=2*pi*${r}*${h}=${numberLabel(a)} square units.`,assessmentStyle:contextual};},
v=>{const r=4+v,h=9+v,a=2*pi*r*(r+h);return{subtopic:"Cylinder total surface",prompt:`A closed cylinder has radius ${r} units and height ${h} units. Calculate its total surface area.`,answer:a,distractors:[2*pi*r*h,pi*r*r*h,a+10],format:sq,solution:`Total surface=2*pi*r(r+h)=2*pi*${r}*(${r}+${h})=${numberLabel(a)} square units.`,assessmentStyle:multi};},
v=>{const r=5+v,h=12+v,a=pi*r*r*h/3;return{subtopic:"Cone volume",prompt:`A cone has radius ${r} units and perpendicular height ${h} units. Find its volume.`,answer:a,distractors:[pi*r*r*h,pi*r*h,a+10],format:cube,solution:`Volume=1/3*pi*r^2*h=1/3*pi*${r}^2*${h}=${numberLabel(a)} cubic units.`,assessmentStyle:direct};},
v=>{const r=5+v,h=12+v,l=Math.hypot(r,h),a=pi*r*l;return{subtopic:"Cone curved surface",prompt:`A right cone has radius ${r} units and height ${h} units. Find its curved surface area.`,answer:a,distractors:[pi*r*h,pi*r*(r+l),a+10],format:sq,solution:`Slant height=sqrt(${r}^2+${h}^2)=${numberLabel(l)}. Curved area=pi*r*l=${numberLabel(a)} square units.`,assessmentStyle:multi};},
v=>{const r=4+v,a=4/3*pi*r**3;return{subtopic:"Sphere volume",prompt:`Calculate the volume of a sphere with radius ${r} units.`,answer:a,distractors:[4*pi*r*r,2/3*pi*r**3,a+10],format:cube,solution:`Sphere volume=4/3*pi*r^3=4/3*pi*${r}^3=${numberLabel(a)} cubic units.`,assessmentStyle:direct};},
v=>{const r=5+v,a=4*pi*r*r;return{subtopic:"Sphere surface area",prompt:`A spherical component has radius ${r} units. Find the coating area required to cover its entire exterior.`,answer:a,distractors:[4/3*pi*r**3,2*pi*r*r,a+10],format:sq,solution:`Surface area=4*pi*r^2=4*pi*${r}^2=${numberLabel(a)} square units.`,assessmentStyle:contextual};},
v=>{const l=8+v,w=6+v,h=5+v,a=l*w*h;return{subtopic:"Cuboid volume",prompt:`A storage box measures ${l} by ${w} by ${h} units internally. Find its capacity in cubic units.`,answer:a,distractors:[2*(l*w+w*h+h*l),l+w+h,a+10],format:cube,solution:`Cuboid volume=length*width*height=${l}*${w}*${h}=${a} cubic units.`,assessmentStyle:contextual};},
v=>{const side=5+v,a=side*Math.sqrt(3);return{subtopic:"Cube space diagonal",prompt:`A cube has edge ${side} units. Calculate its longest internal diagonal.`,answer:a,distractors:[side*Math.sqrt(2),3*side,side**3],solution:`Space diagonal=sqrt(side^2+side^2+side^2)=${side}sqrt(3)=${numberLabel(a)} units.`,assessmentStyle:contextual};},
v=>{const l=20+2*v,w=15+v,volume=1800+300*v,depth=volume/(l*w);return{subtopic:"Tank depth from volume",prompt:`A rectangular tank ${l} units long and ${w} units wide contains ${volume} cubic units of liquid. Find the liquid depth.`,answer:depth,distractors:[volume/(l+w),l*w/volume,depth+2],solution:`Volume=length*width*depth. Therefore depth=${volume}/(${l}*${w})=${numberLabel(depth)} units.`,assessmentStyle:reverse};},
v=>{const small=2+v,big=4+v,n=(big/small)**3;return{subtopic:"Melting solid spheres",prompt:`How many solid spheres of radius ${small} units must be melted to form one sphere of radius ${big} units, with no material loss?`,answer:n,distractors:[big/small,(big/small)**2,n+2],solution:`Volume scales with radius cubed. Required count=(big/small)^3=(${big}/${small})^3=${numberLabel(n)}.`,assessmentStyle:multi};},
];

export const algebraPlacementBank=()=>buildPlacementBank(algebraPatterns);
export const mensurationPlacementBank=()=>buildPlacementBank(mensurationPatterns);
