import { buildPlacementBank, numberLabel } from "./PlacementQuestionFactory.js";

const direct="direct",reverse="reverse",multi="multi-step",contextual="contextual";
const fact=n=>{let p=1;for(let i=2;i<=n;i++)p*=i;return p;};
const nPr=(n,r)=>fact(n)/fact(n-r);
const nCr=(n,r)=>fact(n)/(fact(r)*fact(n-r));

const permutationPatterns=[
v=>{const n=5+v,a=fact(n);return{subtopic:"Factorial arrangements",prompt:`How many linear arrangements are possible for ${n} distinct files placed in a row?`,answer:a,distractors:[n*n,nCr(n,2),fact(n-1)],solution:`All ${n} distinct positions can be filled in ${n}! ways, so count=${n}!=${a}.`,assessmentStyle:direct};},
v=>{const n=7+v,r=3+v%2,a=nPr(n,r);return{subtopic:"Ordered selection",prompt:`From ${n} candidates, how many ordered ways can ${r} distinct presentation slots be assigned?`,answer:a,distractors:[nCr(n,r),n**r,fact(r)],solution:`Order matters, so use nPr=${n}!/(${n}-${r})!=${a}.`,assessmentStyle:direct};},
v=>{const n=8+v,r=3+v%3,a=nCr(n,r);return{subtopic:"Unordered selection",prompt:`A panel of ${r} people is selected from ${n} eligible employees. How many different panels are possible?`,answer:a,distractors:[nPr(n,r),n**r,fact(r)],solution:`Panel order is irrelevant, so use nCr=${n}!/[${r}!(${n}-${r})!]=${a}.`,assessmentStyle:direct};},
v=>{const n=5+v,a=fact(n)/2;return{subtopic:"Repeated-letter word",prompt:`A word contains ${n} letters with exactly two identical letters and all others distinct. How many distinguishable arrangements can be formed?`,answer:a,distractors:[fact(n),fact(n-1),a+fact(n-2)],solution:`Begin with ${n}! arrangements and divide by 2! for the identical pair: ${n}!/2=${a}.`,assessmentStyle:contextual};},
v=>{const n=6+v,a=fact(n-1);return{subtopic:"Circular arrangement",prompt:`How many circular seating arrangements are possible for ${n} distinct people when rotations are considered identical?`,answer:a,distractors:[fact(n),fact(n)/2,fact(n-2)],solution:`Fix one person to remove rotational duplication, then arrange the remaining ${n-1}: (${n}-1)!=${a}.`,assessmentStyle:direct};},
v=>{const men=5+v,women=4+v,r=4,a=nCr(men+women,r)-nCr(men,r);return{subtopic:"Committee with minimum category",prompt:`A ${r}-member committee is chosen from ${men} men and ${women} women. How many committees contain at least one woman?`,answer:a,distractors:[nCr(women,1)*nCr(men,r-1),nCr(men+women,r),a+women],solution:`Use complement: all committees nCr(${men+women},${r}) minus all-male committees nCr(${men},${r}) = ${a}.`,assessmentStyle:multi};},
v=>{const n=7+v,a=2*fact(n-1);return{subtopic:"Two people together",prompt:`In how many row arrangements of ${n} distinct people must two specified people sit together?`,answer:a,distractors:[fact(n),fact(n-1),2*fact(n-2)],solution:`Treat the specified pair as one block: ${n-1} objects give (${n}-1)! orders, and the pair has 2 internal orders. Total=2*(${n}-1)!=${a}.`,assessmentStyle:multi};},
v=>{const n=7+v,a=fact(n)-2*fact(n-1);return{subtopic:"Two people separated",prompt:`How many row arrangements of ${n} distinct people keep two specified people from sitting together?`,answer:a,distractors:[fact(n)-fact(n-1),2*fact(n-1),fact(n)],solution:`All arrangements=${n}!. Together arrangements=2*(${n}-1)!. Subtract: ${n}!-2*(${n}-1)!=${a}.`,assessmentStyle:multi};},
v=>{const boys=4+v,girls=3+v,a=fact(boys)*fact(girls)*2;return{subtopic:"Alternating arrangement",prompt:`${boys} boys and ${girls} girls are arranged in a row with members of each group occupying separate contiguous blocks. In how many ways can the two blocks and people be arranged?`,answer:a,distractors:[fact(boys+girls),fact(boys)*fact(girls),a/2],solution:`Arrange each group internally in ${boys}! and ${girls}! ways, then order the two blocks in 2 ways. Total=${boys}!*${girls}!*2=${a}.`,assessmentStyle:multi};},
v=>{const n=6+v,r=4,a=nPr(n,r);return{subtopic:"Distinct digit numbers",prompt:`How many ${r}-digit codes can be formed from ${n} available nonzero distinct digits without repetition?`,answer:a,distractors:[nCr(n,r),n**r,(n-1)**r],solution:`Choose and order ${r} distinct digits from ${n}: nPr=${n}!/(${n}-${r})!=${a}.`,assessmentStyle:contextual};},
v=>{const n=5+v,r=4,a=n**r;return{subtopic:"Codes with repetition",prompt:`A security code has ${r} positions, each independently chosen from ${n} symbols with repetition allowed. How many codes exist?`,answer:a,distractors:[nPr(n,r),nCr(n,r),fact(r)],solution:`Each of ${r} positions has ${n} choices, independently. Multiplication gives ${n}^${r}=${a}.`,assessmentStyle:contextual};},
v=>{const digits=5+v,r=3,a=(digits-1)*nPr(digits-1,r-1);return{subtopic:"Numbers excluding leading zero",prompt:`Using ${digits} digits including zero, how many ${r}-digit numbers can be formed without repetition?`,answer:a,distractors:[nPr(digits,r),digits**r,(digits-1)**r],solution:`First digit has ${digits-1} nonzero choices. Remaining ${r-1} places use permutations of ${digits-1} remaining digits: (${digits-1})*nPr(${digits-1},${r-1})=${a}.`,assessmentStyle:multi};},
v=>{const even=3+v%2,total=7+v,r=3,a=even*nPr(total-1,r-1);return{subtopic:"Even-number formation",prompt:`A digit set has ${total} distinct nonzero digits, of which ${even} are even. How many ${r}-digit even numbers can be formed without repetition?`,answer:a,distractors:[even*total**(r-1),nPr(total,r)/2,a+even],solution:`Choose the final even digit in ${even} ways, then order ${r-1} digits from the remaining ${total-1}: ${even}*nPr(${total-1},${r-1})=${a}.`,assessmentStyle:multi};},
v=>{const n=8+v,r=3,a=nPr(n,r);return{subtopic:"Leadership roles",prompt:`From ${n} team members, in how many ways can a captain, deputy, and coordinator be appointed with no person holding two roles?`,answer:a,distractors:[nCr(n,r),n**r,fact(r)],solution:`The roles are distinct, so assignment count is nPr(${n},3)=${n}*${n-1}*${n-2}=${a}.`,assessmentStyle:contextual};},
v=>{const women=5+v,men=6+v,a=nCr(women,2)*nCr(men,2);return{subtopic:"Category-constrained selection",prompt:`A four-person task force must contain exactly two women from ${women} and two men from ${men}. How many task forces are possible?`,answer:a,distractors:[nCr(women+men,4),nPr(women,2)*nPr(men,2),a+10],solution:`Select independently: nCr(${women},2)*nCr(${men},2)=${nCr(women,2)}*${nCr(men,2)}=${a}.`,assessmentStyle:multi};},
v=>{const n=7+v,identical=3,a=nCr(n+identical-1,identical);return{subtopic:"Identical-item distribution",prompt:`How many ways can ${identical} identical awards be distributed among ${n} employees if an employee may receive multiple awards?`,answer:a,distractors:[n**identical,nPr(n,identical),nCr(n,identical)],solution:`Use stars and bars for nonnegative allocations: nCr(${n}+${identical}-1,${identical})=${a}.`,assessmentStyle:contextual};},
v=>{const items=8+v,boxes=3,positive=nCr(items-1,boxes-1);return{subtopic:"Positive integer distribution",prompt:`In how many ways can ${items} identical tasks be assigned among ${boxes} teams if every team receives at least one task?`,answer:positive,distractors:[nCr(items+boxes-1,boxes-1),boxes**items,nCr(items,boxes)],solution:`For positive allocations use stars and bars: nCr(${items}-1,${boxes}-1)=nCr(${items-1},${boxes-1})=${positive}.`,assessmentStyle:contextual};},
v=>{const n=7+v,a=fact(n-1)/2;return{subtopic:"Circular arrangement with reflection",prompt:`How many distinct necklace arrangements are possible for ${n} different beads when rotations and mirror images are considered identical?`,answer:a,distractors:[fact(n-1),fact(n),fact(n)/2],solution:`Circular arrangements give (${n}-1)!. Reflection identifies each arrangement with its reverse, so divide by 2: (${n}-1)!/2=${a}.`,assessmentStyle:multi};},
v=>{const n=8+v,a=nCr(n,2)-n;return{subtopic:"Polygon diagonals",prompt:`How many diagonals can be drawn in a convex polygon with ${n} vertices?`,answer:a,distractors:[nCr(n,2),n*(n-1),a+n],solution:`Every vertex pair makes a segment: nCr(${n},2). Remove ${n} sides, leaving ${nCr(n,2)}-${n}=${a} diagonals.`,assessmentStyle:multi};},
v=>{const n=10+v,a=nCr(n,2);return{subtopic:"Handshake count",prompt:`At a placement workshop, each of ${n} participants shakes hands with every other participant exactly once. How many handshakes occur?`,answer:a,distractors:[n*(n-1),n*n,a+n],solution:`Each handshake is an unordered pair. Count pairs with nCr(${n},2)=${a}; this avoids double counting A-B and B-A.`,assessmentStyle:contextual};},
v=>{const right=4+v,up=3+v,a=nCr(right+up,right);return{subtopic:"Shortest grid routes",prompt:`A robot must move ${right} steps right and ${up} steps up to reach a target, with no backward movement. How many shortest routes are possible?`,answer:a,distractors:[right*up,2**(right+up),nPr(right+up,right)],solution:`Every shortest route orders ${right} R moves and ${up} U moves. Choose positions of R: nCr(${right+up},${right})=${a}.`,assessmentStyle:multi};},
v=>{const vowels=3,cons=4+v,a=fact(vowels)*fact(cons+1);return{subtopic:"Vowels kept together",prompt:`A word has ${vowels} distinct vowels and ${cons} distinct consonants. How many arrangements keep all vowels together?`,answer:a,distractors:[fact(vowels+cons),fact(cons)*fact(vowels),a/2],solution:`Treat vowels as one block with ${cons} consonants: (${cons}+1)! block orders. Arrange vowels internally in ${vowels}! ways. Product=${a}.`,assessmentStyle:multi};},
v=>{const math=4+v,tech=3+v,choose=3,a=nCr(math+tech,choose)-nCr(math,choose);return{subtopic:"Selection with required domain",prompt:`A reading list of ${choose} books is chosen from ${math} mathematics and ${tech} technology books. How many lists include at least one technology book?`,answer:a,distractors:[nCr(tech,1)*nCr(math,choose-1),nCr(math+tech,choose),a+tech],solution:`All lists=nCr(${math+tech},${choose}); subtract all-mathematics lists nCr(${math},${choose}). Result=${a}.`,assessmentStyle:multi};},
v=>{const people=6+v,tasks=3,a=nPr(people,tasks);return{subtopic:"Distinct task assignment",prompt:`There are ${tasks} different tasks and ${people} available people. If one person handles at most one task, how many assignments are possible?`,answer:a,distractors:[people**tasks,nCr(people,tasks),fact(tasks)],solution:`Tasks are distinct roles. Select and order ${tasks} people from ${people}: nPr(${people},${tasks})=${a}.`,assessmentStyle:contextual};},
v=>{const total=9+v,r=4,blocked=2,a=nCr(total,r)-nCr(total-blocked,r);return{subtopic:"At least one specified candidate",prompt:`A ${r}-person panel is chosen from ${total} candidates, including two specified experts. How many panels include at least one of those experts?`,answer:a,distractors:[2*nCr(total-1,r-1),nCr(total,r),a+2],solution:`Use complement: all panels nCr(${total},${r}) minus panels excluding both experts nCr(${total-blocked},${r}) = ${a}.`,assessmentStyle:multi};},
];

const probabilityPatterns=[
v=>{const coins=2+v,a=1/2**coins;return{subtopic:"All heads probability",prompt:`${coins} fair coins are tossed independently. What is the probability that every coin shows heads?`,answer:a,distractors:[coins/2,1/coins,1-1/2**coins],solution:`Each head has probability 1/2. Independence gives (1/2)^${coins}=${numberLabel(a)}.`,assessmentStyle:direct};},
v=>{const target=v,a=1/6;return{subtopic:"Single die outcome",prompt:`A fair six-sided die is rolled once. What is the probability of obtaining the specified face ${target}?`,answer:a,distractors:[target/6,1/5,5/6],solution:`There is one favourable face among six equally likely faces, so probability=1/6=${numberLabel(a)}.`,assessmentStyle:direct};},
v=>{const target=4+v;let count=0;for(let a=1;a<=6;a++)for(let b=1;b<=6;b++)if(a+b===target)count++;const p=count/36;return{subtopic:"Two-dice sum",prompt:`Two fair dice are rolled. What is the probability that their sum equals ${target}?`,answer:p,distractors:[target/36,count/12,1-p],solution:`There are 36 ordered outcomes. Exactly ${count} pairs sum to ${target}; probability=${count}/36=${numberLabel(p)}.`,assessmentStyle:contextual};},
v=>{const red=5+v,blue=7+v,p=red/(red+blue);return{subtopic:"Single draw from bag",prompt:`A bag contains ${red} red and ${blue} blue balls. One ball is drawn uniformly. Find the probability that it is red.`,answer:p,distractors:[blue/(red+blue),red/blue,1/(red+blue)],solution:`Favourable outcomes=${red}; total=${red}+${blue}=${red+blue}. Probability=${red}/${red+blue}=${numberLabel(p)}.`,assessmentStyle:direct};},
v=>{const decks=v,total=52*decks,red=26*decks,p=red/total;return{subtopic:"Card colour",prompt:`${decks} complete standard deck${decks===1?" is":"s are"} combined and shuffled. One card is drawn. What is the probability that it is red?`,answer:p,distractors:[13/52,4/52,26/51],solution:`There are ${red} red cards among ${total} cards, so probability=${red}/${total}=${numberLabel(p)}.`,assessmentStyle:direct};},
v=>{const decks=v,total=52*decks,faces=12*decks,p=faces/total;return{subtopic:"Face card",prompt:`${decks} complete deck${decks===1?" is":"s are"} combined and shuffled. What is the probability that one drawn card is a jack, queen, or king?`,answer:p,distractors:[3/52,4/52,16/52],solution:`Each deck has 12 face cards, giving ${faces} among ${total}. Probability=${faces}/${total}=${numberLabel(p)}.`,assessmentStyle:direct};},
v=>{const red=6+v,blue=5+v,p=red/(red+blue)*(red-1)/(red+blue-1);return{subtopic:"Without-replacement probability",prompt:`A bag has ${red} red and ${blue} blue balls. Two balls are drawn without replacement. What is the probability that both are red?`,answer:p,distractors:[(red/(red+blue))**2,red/(red+blue)*blue/(red+blue-1),1-p],solution:`First-red probability=${red}/${red+blue}; then ${red-1}/${red+blue-1}. Multiply to obtain ${numberLabel(p)}.`,assessmentStyle:multi};},
v=>{const red=5+v,total=12+2*v,p=(red/total)**2;return{subtopic:"With-replacement probability",prompt:`A container has ${red} favourable items among ${total}. One item is drawn, replaced, and another is drawn. Find the probability both are favourable.`,answer:p,distractors:[red/total*(red-1)/(total-1),2*red/total,1-p],solution:`Replacement restores the original probability. Independent draws give (${red}/${total})*(${red}/${total})=${numberLabel(p)}.`,assessmentStyle:multi};},
v=>{const p=0.2+0.05*v,n=3,a=1-(1-p)**n;return{subtopic:"At least one success",prompt:`A trial succeeds with probability ${numberLabel(p)} and is repeated independently ${n} times. Find the probability of at least one success.`,answer:a,distractors:[p**n,n*p,(1-p)**n],solution:`Use complement: P(at least one)=1-P(no success)=1-(1-${numberLabel(p)})^${n}=${numberLabel(a)}.`,assessmentStyle:multi};},
v=>{const p=0.3+0.05*v,a=1-p;return{subtopic:"Complement probability",prompt:`An event has probability ${numberLabel(p)}. What is the probability that the event does not occur?`,answer:a,distractors:[p,1/p,p*p],solution:`An event and its complement total 1. Therefore P(not event)=1-${numberLabel(p)}=${numberLabel(a)}.`,assessmentStyle:direct};},
v=>{const pA=0.4+0.05*v,pB=0.25+0.05*v,intersection=0.1+0.02*v,a=intersection/pB;return{subtopic:"Conditional probability",prompt:`For events A and B, P(B)=${numberLabel(pB)} and P(A and B)=${numberLabel(intersection)}. Find P(A given B).`,answer:a,distractors:[intersection/pA,pA*pB,pA+pB-intersection],solution:`Conditional probability P(A|B)=P(A and B)/P(B)=${numberLabel(intersection)}/${numberLabel(pB)}=${numberLabel(a)}.`,assessmentStyle:reverse};},
v=>{const p=0.4+0.05*v,q=0.3+0.02*v,a=p*q;return{subtopic:"Independent events",prompt:`Independent events A and B have probabilities ${numberLabel(p)} and ${numberLabel(q)}. Find the probability that both occur.`,answer:a,distractors:[p+q,p+q-p*q,1-a],solution:`Independence gives P(A and B)=P(A)*P(B)=${numberLabel(p)}*${numberLabel(q)}=${numberLabel(a)}.`,assessmentStyle:contextual};},
v=>{const p=0.25+0.05*v,q=0.2+0.03*v,a=p+q;return{subtopic:"Mutually exclusive events",prompt:`Mutually exclusive events A and B have probabilities ${numberLabel(p)} and ${numberLabel(q)}. What is the probability that either occurs?`,answer:a,distractors:[p*q,p+q-p*q,1-a],solution:`Their intersection is zero, so P(A or B)=P(A)+P(B)=${numberLabel(p)}+${numberLabel(q)}=${numberLabel(a)}.`,assessmentStyle:contextual};},
v=>{const n=3+v,k=2,p=0.5,a=nCr(n,k)*p**k*(1-p)**(n-k);return{subtopic:"Exactly k successes",prompt:`A fair binary trial is repeated ${n} times independently. What is the probability of exactly ${k} successes?`,answer:a,distractors:[p**k,nCr(n,k)*p**k,1-a],solution:`Use binomial probability nCr(${n},${k})*(0.5)^${k}*(0.5)^${n-k}=${numberLabel(a)}.`,assessmentStyle:multi};},
v=>{const n=5,p=0.2+0.05*v,a=n*p;return{subtopic:"Expected successes",prompt:`A success probability of ${numberLabel(p)} applies independently across ${n} trials. What is the expected number of successes?`,answer:a,distractors:[p**n,n/p,1-(1-p)**n],solution:`For a binomial count, expectation=np=${n}*${numberLabel(p)}=${numberLabel(a)}.`,assessmentStyle:contextual};},
v=>{const men=6+v,women=5+v,r=3,p=(nCr(men+women,r)-nCr(men,r))/nCr(men+women,r);return{subtopic:"Random committee composition",prompt:`A ${r}-person committee is selected uniformly from ${men} men and ${women} women. Find the probability that it includes at least one woman.`,answer:p,distractors:[nCr(women,1)*nCr(men,r-1)/nCr(men+women,r),women/(men+women),1-p],solution:`Total committees=nCr(${men+women},${r}). Subtract all-male nCr(${men},${r}); divide by total to get ${numberLabel(p)}.`,assessmentStyle:multi};},
v=>{const defective=3+v,total=20+2*v,p=defective/total;return{subtopic:"Defective item probability",prompt:`A quality lot contains ${total} components, of which ${defective} are defective. One component is sampled uniformly. Find the defect probability.`,answer:p,distractors:[(total-defective)/total,defective/(total-defective),1/total],solution:`Favourable defective outcomes=${defective}; total outcomes=${total}. Probability=${defective}/${total}=${numberLabel(p)}.`,assessmentStyle:contextual};},
v=>{const d=4+v,g=10+v,total=d+g,p=d/total*(d-1)/(total-1);return{subtopic:"Quality sampling without replacement",prompt:`A batch has ${d} defective and ${g} good items. Two items are sampled without replacement. What is the probability both are defective?`,answer:p,distractors:[(d/total)**2,d/total*g/(total-1),1-p],solution:`P(first defective)=${d}/${total}; P(second defective|first)=${d-1}/${total-1}. Multiply to get ${numberLabel(p)}.`,assessmentStyle:multi};},
v=>{const prevalence=0.1+0.02*v,sens=0.8,falsePos=0.1,numer=prevalence*sens,a=numer/(numer+(1-prevalence)*falsePos);return{subtopic:"Bayes screening probability",prompt:`A condition occurs with probability ${numberLabel(prevalence)}. A test is positive with probability ${sens} when present and ${falsePos} when absent. Given a positive result, find the probability the condition is present.`,answer:a,distractors:[sens,prevalence*sens,1-a],solution:`Bayes numerator=${numberLabel(prevalence)}*${sens}. Positive total=numerator+(1-${numberLabel(prevalence)})*${falsePos}. Divide to obtain ${numberLabel(a)}.`,assessmentStyle:multi};},
v=>{const p=0.2+0.05*v,k=3,a=(1-p)**(k-1)*p;return{subtopic:"First success on kth trial",prompt:`Independent trials succeed with probability ${numberLabel(p)}. Find the probability that the first success occurs on trial ${k}.`,answer:a,distractors:[p**k,1-(1-p)**k,(1-p)*p],solution:`The first ${k-1} trials must fail and trial ${k} succeed: (1-${numberLabel(p)})^${k-1}*${numberLabel(p)}=${numberLabel(a)}.`,assessmentStyle:multi};},
v=>{const sectors=8+v,fav=3+v%3,p=fav/sectors;return{subtopic:"Spinner probability",prompt:`A fair spinner has ${sectors} equal sectors, ${fav} of which are marked as winning. What is the probability of landing on a winning sector?`,answer:p,distractors:[1/sectors,(sectors-fav)/sectors,fav/(sectors-fav)],solution:`All sectors are equally likely. Probability=favourable/total=${fav}/${sectors}=${numberLabel(p)}.`,assessmentStyle:contextual};},
v=>{const days=30+v%2,special=5+v,p=special/days;return{subtopic:"Calendar-day selection",prompt:`A day is selected uniformly from a ${days}-day month containing ${special} scheduled review days. Find the probability that a review day is selected.`,answer:p,distractors:[1/days,(days-special)/days,special/(days-special)],solution:`There are ${special} favourable dates among ${days} equally likely dates, so probability=${special}/${days}=${numberLabel(p)}.`,assessmentStyle:contextual};},
v=>{const n=6+v,total=fact(n),together=2*fact(n-1),p=together/total;return{subtopic:"Arrangement probability",prompt:`${n} distinct people are randomly arranged in a row. What is the probability that two specified people stand together?`,answer:p,distractors:[1/fact(n),fact(n-1)/fact(n),1-p],solution:`Favourable arrangements=2*(${n}-1)!; total=${n}!. Ratio=2*(${n}-1)!/${n}!=${numberLabel(p)}.`,assessmentStyle:multi};},
v=>{const low=0.1+0.02*v,medium=0.25,high=1-low-medium,loss=low*1000+medium*4000+high*10000;return{subtopic:"Risk caselet expectation",prompt:`A risk caselet assigns probabilities ${numberLabel(low)}, ${medium}, and ${numberLabel(high)} to losses of Rs 1,000, Rs 4,000, and Rs 10,000. Find the expected loss.`,answer:loss,distractors:[(1000+4000+10000)/3,high*10000,loss+500],solution:`Expected loss=${numberLabel(low)}*1000+${medium}*4000+${numberLabel(high)}*10000=Rs ${numberLabel(loss)}.`,assessmentStyle:multi};},
v=>{const p=0.55+0.03*v,q=0.4,intersection=0.2,a=p+q-intersection;return{subtopic:"Union with overlap",prompt:`Events A and B have probabilities ${numberLabel(p)} and ${q}, with intersection ${intersection}. Find the probability that at least one occurs.`,answer:a,distractors:[p+q,p*q,intersection],solution:`Use P(A union B)=P(A)+P(B)-P(A and B)=${numberLabel(p)}+${q}-${intersection}=${numberLabel(a)}.`,assessmentStyle:multi};},
];

export const permutationPlacementBank=()=>buildPlacementBank(permutationPatterns);
export const probabilityPlacementBank=()=>buildPlacementBank(probabilityPatterns);
