import {
  buildPlacementBank,
  hoursLabel,
  kilometresLabel,
  kmphLabel,
  minutesLabel,
  numberLabel,
} from "./PlacementQuestionFactory.js";

const direct="direct", reverse="reverse", multi="multi-step", contextual="contextual";

const distancePatterns = [
  v=>{const s=36+6*v,t=2+v/2,a=s*t;return{subtopic:"Distance from speed and time",prompt:`A campus shuttle travels at a constant ${s} km/h for ${t} hours. What distance does it cover?`,answer:a,distractors:[s+t,s/t,a+s],format:kilometresLabel,solution:`Distance = speed * time = ${s} * ${t} = ${numberLabel(a)} km.`,assessmentStyle:direct};},
  v=>{const d=180+30*v,s=45+5*v,a=d/s;return{subtopic:"Travel time",prompt:`A vehicle must cover ${d} km at a steady ${s} km/h. How many hours does the journey take?`,answer:a,distractors:[s/d,d-s,a+1],format:hoursLabel,solution:`Time = distance / speed = ${d}/${s} = ${numberLabel(a)} hours.`,assessmentStyle:direct};},
  v=>{const d=150+25*v,t=2+v/2,a=d/t;return{subtopic:"Speed from journey data",prompt:`A delivery team covers ${d} km in ${t} hours without stopping. Calculate its average speed.`,answer:a,distractors:[d*t,d-t,a+5],format:kmphLabel,solution:`Average speed = total distance / total time = ${d}/${t} = ${numberLabel(a)} km/h.`,assessmentStyle:direct};},
  v=>{const s=36+9*v,a=s*5/18;return{subtopic:"Kilometres per hour to metres per second",prompt:`Convert a speed of ${s} km/h into metres per second for use in a timed assessment calculation.`,answer:a,distractors:[s*18/5,s/60,a+2],solution:`Multiply km/h by 5/18: ${s} * 5/18 = ${numberLabel(a)} m/s.`,assessmentStyle:direct};},
  v=>{const s=10+2*v,a=s*18/5;return{subtopic:"Metres per second to kilometres per hour",prompt:`A tracking device reports ${s} metres per second. Convert this reading to kilometres per hour.`,answer:a,distractors:[s*5/18,s*60,a+5],format:kmphLabel,solution:`Multiply m/s by 18/5: ${s} * 18/5 = ${numberLabel(a)} km/h.`,assessmentStyle:direct};},
  v=>{const a=40+4*v,b=60+6*v,avg=2*a*b/(a+b);return{subtopic:"Average speed over equal distances",prompt:`A car covers the first half of a route at ${a} km/h and the equal remaining distance at ${b} km/h. Find the average speed for the whole route.`,answer:avg,distractors:[(a+b)/2,a*b/(a+b),avg+5],format:kmphLabel,solution:`For equal distances, average speed = 2*${a}*${b}/(${a}+${b}) = ${numberLabel(avg)} km/h; the arithmetic mean is not applicable.`,assessmentStyle:contextual};},
  v=>{const s1=35+5*v,s2=55+5*v,t1=2+v%2,t2=3+v%3,a=(s1*t1+s2*t2)/(t1+t2);return{subtopic:"Average speed over unequal times",prompt:`A sales executive drives ${t1} hours at ${s1} km/h and then ${t2} hours at ${s2} km/h. What is the average speed for the complete journey?`,answer:a,distractors:[(s1+s2)/2,(s1*t1+s2*t2)/2,a+5],format:kmphLabel,solution:`Total distance = ${s1}*${t1}+${s2}*${t2}; total time = ${t1}+${t2}. Divide to obtain ${numberLabel(a)} km/h.`,assessmentStyle:multi};},
  v=>{const a=40+5*v,b=50+5*v,ans=a+b;return{subtopic:"Opposite-direction relative speed",prompt:`Two vehicles move in opposite directions at ${a} km/h and ${b} km/h. What is their relative speed?`,answer:ans,distractors:[Math.abs(a-b),(a+b)/2,a*b/(a+b)],format:kmphLabel,solution:`For opposite directions, relative speed = ${a}+${b} = ${ans} km/h.`,assessmentStyle:contextual};},
  v=>{const a=65+5*v,b=40+3*v,ans=a-b;return{subtopic:"Same-direction relative speed",prompt:`Two riders travel in the same direction at ${a} km/h and ${b} km/h. At what rate does the faster rider gain on the slower one?`,answer:ans,distractors:[a+b,(a+b)/2,ans+5],format:kmphLabel,solution:`Same-direction relative speed = ${a}-${b} = ${ans} km/h.`,assessmentStyle:contextual};},
  v=>{const d=180+30*v,a=40+5*v,b=50+5*v,ans=d/(a+b);return{subtopic:"Meeting from opposite ends",prompt:`Two colleagues start simultaneously from cities ${d} km apart and travel toward each other at ${a} km/h and ${b} km/h. After how many hours do they meet?`,answer:ans,distractors:[d/Math.abs(a-b),d/a,ans+1],format:hoursLabel,solution:`Closing speed = ${a}+${b}. Meeting time = ${d}/(${a}+${b}) = ${numberLabel(ans)} hours.`,assessmentStyle:contextual};},
  v=>{const slow=40+4*v,fast=60+4*v,delay=1+v%2,ans=fast*delay/(fast-slow);return{subtopic:"Delayed catch-up",prompt:`A bus leaves at ${slow} km/h. ${delay} hour later, a car follows on the same route at ${fast} km/h. How many hours after the car starts will it catch the bus?`,answer:ans,distractors:[slow*delay/(fast-slow),fast/(fast-slow),ans+1],format:hoursLabel,solution:`Bus lead = ${slow}*${delay}. Relative speed = ${fast}-${slow}. Catch-up time = lead/relative speed = ${numberLabel(ans)} hours.`,assessmentStyle:multi};},
  v=>{const slow=36+4*v,delay=2,catchTime=3+v%2,fast=slow*(delay+catchTime)/catchTime;return{subtopic:"Required catch-up speed",prompt:`A truck travels at ${slow} km/h and has a ${delay}-hour head start. A car must catch it exactly ${catchTime} hours after starting. What constant speed must the car maintain?`,answer:fast,distractors:[slow*delay/catchTime,slow+delay*catchTime,fast+5],format:kmphLabel,solution:`At catch-up the truck has travelled ${slow}*(${delay}+${catchTime}). Divide that distance by the car's ${catchTime} hours to obtain ${numberLabel(fast)} km/h.`,assessmentStyle:reverse};},
  v=>{const track=400+40*v,a=8+v,b=6+v,ans=track/(a-b)/60;return{subtopic:"Circular track same direction",prompt:`Two runners move around a ${track}-metre circular track in the same direction at ${a} m/s and ${b} m/s. After how many minutes does the faster runner first lap the other?`,answer:ans,distractors:[track/(a+b)/60,track/a/60,ans+1],format:minutesLabel,solution:`One lap is gained at relative speed ${a}-${b} m/s. Time = ${track}/(${a}-${b}) seconds; divide by 60 to get ${numberLabel(ans)} minutes.`,assessmentStyle:multi};},
  v=>{const track=420+60*v,a=7+v,b=5+v,ans=track/(a+b)/60;return{subtopic:"Circular track opposite direction",prompt:`Two runners start together on a ${track}-metre circular track in opposite directions at ${a} m/s and ${b} m/s. When do they first meet again?`,answer:ans,distractors:[track/Math.abs(a-b)/60,track/a/60,ans+1],format:minutesLabel,solution:`They close one full lap at ${a}+${b} m/s. Meeting time = ${track}/(${a}+${b}) seconds = ${numberLabel(ans)} minutes.`,assessmentStyle:multi};},
  v=>{const race=1000+100*v,aSpeed=10+v,bSpeed=8+v,head=100+10*v,aTime=race/aSpeed,bDistance=aTime*bSpeed+head,margin=race-bDistance;return{subtopic:"Race with head start",prompt:`In a ${race}-metre race, A runs at ${aSpeed} m/s while B runs at ${bSpeed} m/s and receives a ${head}-metre head start. By how many metres does the winner finish ahead?`,answer:Math.abs(margin),distractors:[head,(aSpeed-bSpeed)*aTime,Math.abs(margin)+20],solution:`A's time = ${race}/${aSpeed}. In that time B covers ${aTime}*${bSpeed} plus the ${head}-metre head start. Compare this position with ${race}; margin = ${numberLabel(Math.abs(margin))} metres.`,assessmentStyle:multi};},
  v=>{const d=240+30*v,s=40+5*v,inc=10+5*v,old=d/s,newT=d/(s*(1+inc/100)),save=(old-newT)*60;return{subtopic:"Time saved by speed increase",prompt:`A journey of ${d} km is normally made at ${s} km/h. If speed increases by ${inc}%, how many minutes are saved?`,answer:save,distractors:[old-newT,inc/100*old*60,save+10],format:minutesLabel,solution:`Old time = ${d}/${s}; new time = ${d}/(${s}*(1+${inc}/100)). Subtract and multiply by 60 to obtain ${numberLabel(save)} minutes saved.`,assessmentStyle:multi};},
  v=>{const d=300+30*v,deadline=5+v/2,ans=d/deadline;return{subtopic:"Speed required for deadline",prompt:`A logistics team must cover ${d} km within ${deadline} hours, including no planned stops. What minimum average speed is required?`,answer:ans,distractors:[d*(deadline),d/(deadline+1),ans+5],format:kmphLabel,solution:`Required speed = distance/deadline = ${d}/${deadline} = ${numberLabel(ans)} km/h.`,assessmentStyle:reverse};},
  v=>{const running=60+5*v,runMin=45,stopMin=15,ans=running*runMin/(runMin+stopMin);return{subtopic:"Average speed with stoppages",prompt:`A bus runs at ${running} km/h for ${runMin} minutes and then stops for ${stopMin} minutes in every hour-long cycle. What is its average speed including stoppage time?`,answer:ans,distractors:[running*runMin/60,running-stopMin,ans+5],format:kmphLabel,solution:`In each cycle distance = ${running}*${runMin}/60 km, while elapsed time = (${runMin}+${stopMin})/60 hour. Divide distance by elapsed time to get ${numberLabel(ans)} km/h.`,assessmentStyle:multi};},
  v=>{const d1=100+20*v,s1=40+5*v,d2=150+20*v,s2=60+5*v,ans=(d1+d2)/(d1/s1+d2/s2);return{subtopic:"Multi-leg journey",prompt:`A consultant travels ${d1} km at ${s1} km/h and then ${d2} km at ${s2} km/h. What is the average speed across both legs?`,answer:ans,distractors:[(s1+s2)/2,(d1*s1+d2*s2)/(d1+d2),ans+5],format:kmphLabel,solution:`Total distance = ${d1}+${d2}; total time = ${d1}/${s1}+${d2}/${s2}. Divide the totals to obtain ${numberLabel(ans)} km/h.`,assessmentStyle:multi};},
  v=>{const d=180+20*v,slow=40+4*v,fast=60+4*v,late=d/slow,early=d/fast,diff=(late-early)*60;return{subtopic:"Late-early schedule difference",prompt:`For the same ${d}-km route, travelling at ${slow} km/h reaches the destination later than travelling at ${fast} km/h. What is the difference between the two travel times in minutes?`,answer:diff,distractors:[late-early,d/(fast-slow),diff+10],format:minutesLabel,solution:`Slow time = ${d}/${slow}; fast time = ${d}/${fast}. Subtract the hours and multiply by 60 to get ${numberLabel(diff)} minutes.`,assessmentStyle:reverse};},
  v=>{const walkway=2+v/2,person=5+v/2,length=210+30*v,ans=length/(walkway+person);return{subtopic:"Moving walkway",prompt:`A person walks at ${person} m/s relative to a moving walkway that moves forward at ${walkway} m/s. How many seconds are needed to cover a ${length}-metre walkway?`,answer:ans,distractors:[length/person,length/walkway,ans+5],solution:`Ground speed = ${person}+${walkway} m/s. Time = ${length}/(${person}+${walkway}) = ${numberLabel(ans)} seconds.`,assessmentStyle:contextual};},
  v=>{const out=50+5*v,back=40+5*v,d=100+20*v,ans=d/out+d/back;return{subtopic:"Out-and-back travel time",prompt:`A field officer travels ${d} km outward at ${out} km/h and returns the same distance at ${back} km/h. Find total travel time.`,answer:ans,distractors:[2*d/((out+back)/2),d/out,ans+1],format:hoursLabel,solution:`Outward time = ${d}/${out}; return time = ${d}/${back}. Add both to get ${numberLabel(ans)} hours.`,assessmentStyle:multi};},
  v=>{const directD=180+20*v,detour=30+5*v,s=50+5*v,ans=(directD+detour)/s-directD/s;return{subtopic:"Detour delay",prompt:`A road closure adds ${detour} km to a usual ${directD}-km trip. If the vehicle maintains ${s} km/h throughout, how many additional hours does the detour require?`,answer:ans,distractors:[detour/s*60,directD/s,ans+1],format:hoursLabel,solution:`Detour time minus normal time = (${directD}+${detour})/${s}-${directD}/${s} = ${detour}/${s} = ${numberLabel(ans)} hours.`,assessmentStyle:multi};},
  v=>{const stops=3+v%3,stop=8+v,totalD=240+20*v,running=60+5*v,elapsed=totalD/running+stops*stop/60,ans=totalD/elapsed;return{subtopic:"Delivery route caselet",prompt:`A delivery caselet gives ${totalD} km of driving at ${running} km/h plus ${stops} stops of ${stop} minutes each. What is the average speed over the complete elapsed journey?`,answer:ans,distractors:[running,totalD/(totalD/running+stop/60),ans+5],format:kmphLabel,solution:`Driving time = ${totalD}/${running}; stopped time = ${stops}*${stop}/60 hours. Divide ${totalD} by their sum to obtain ${numberLabel(ans)} km/h.`,assessmentStyle:multi};},
  v=>{const east=30+5*v,north=40+5*v,time=2+v/2,ans=Math.hypot(east*time,north*time);return{subtopic:"Perpendicular-route separation",prompt:`Two vehicles leave the same junction simultaneously. One travels east at ${east} km/h and the other north at ${north} km/h. How far apart are they after ${time} hours?`,answer:ans,distractors:[(east+north)*time,Math.abs(east-north)*time,ans+10],format:kilometresLabel,solution:`East displacement = ${east}*${time}; north displacement = ${north}*${time}. By Pythagoras, separation = sqrt((${east*time})^2+(${north*time})^2) = ${numberLabel(ans)} km.`,assessmentStyle:multi};},
];

const trainBoatPatterns = [
  v=>{const len=120+20*v,s=54+9*(v%3),ans=len/(s*5/18);return{subtopic:"Train crossing a pole",prompt:`A train ${len} metres long moves at ${s} km/h. How many seconds does it take to pass a stationary pole?`,answer:ans,distractors:[len/s,len*(s*5/18),ans+5],solution:`Convert speed to ${numberLabel(s*5/18)} m/s. Time = train length/speed = ${len}/${numberLabel(s*5/18)} = ${numberLabel(ans)} seconds.`,assessmentStyle:direct};},
  v=>{const len=140+20*v,platform=180+30*v,s=54+9*(v%3),ans=(len+platform)/(s*5/18);return{subtopic:"Train crossing a platform",prompt:`A ${len}-metre train crosses a ${platform}-metre platform at ${s} km/h. Find the crossing time in seconds.`,answer:ans,distractors:[platform/(s*5/18),len/(s*5/18),ans+5],solution:`Distance to clear = ${len}+${platform}. Convert speed to ${numberLabel(s*5/18)} m/s, then divide total distance by speed to get ${numberLabel(ans)} seconds.`,assessmentStyle:multi};},
  v=>{const len=150+20*v,person=6+v,train=54+9*(v%3),rel=train*5/18-person,ans=len/rel;return{subtopic:"Train overtaking a runner",prompt:`A ${len}-metre train at ${train} km/h overtakes a runner moving in the same direction at ${person} m/s. How many seconds does the train take to pass the runner completely?`,answer:ans,distractors:[len/(train*5/18+person),len/(train*5/18),ans+5],solution:`Train speed = ${numberLabel(train*5/18)} m/s; same-direction relative speed = ${numberLabel(train*5/18)}-${person}. Divide ${len} by that relative speed to obtain ${numberLabel(ans)} seconds.`,assessmentStyle:multi};},
  v=>{const l1=120+20*v,l2=150+20*v,s1=45+9*(v%3),s2=54+9*(v%2),ans=(l1+l2)/((s1+s2)*5/18);return{subtopic:"Two trains opposite directions",prompt:`Trains ${l1} m and ${l2} m long move in opposite directions at ${s1} km/h and ${s2} km/h. How many seconds do they take to cross each other?`,answer:ans,distractors:[(l1+l2)/(s1*5/18),l1/(s1*5/18),ans+5],solution:`Total clearing distance = ${l1}+${l2}; opposite relative speed = (${s1}+${s2})*5/18 m/s. Divide to get ${numberLabel(ans)} seconds.`,assessmentStyle:multi};},
  v=>{const l1=180+20*v,l2=120+20*v,s1=72+9*v,s2=45+9*(v%3),ans=(l1+l2)/((s1-s2)*5/18);return{subtopic:"Two trains same direction",prompt:`A ${l1}-metre train at ${s1} km/h overtakes a ${l2}-metre train at ${s2} km/h in the same direction. Find the crossing time.`,answer:ans,distractors:[(l1+l2)/((s1+s2)*5/18),l1/((s1-s2)*5/18),ans+5],solution:`Clearing distance = ${l1}+${l2}; relative speed = (${s1}-${s2})*5/18 m/s. Time is distance/relative speed = ${numberLabel(ans)} seconds.`,assessmentStyle:multi};},
  v=>{const s=54+9*(v%3),time=12+2*v,len=time*s*5/18;return{subtopic:"Train length from pole time",prompt:`A train moving at ${s} km/h passes a pole in ${time} seconds. Find the train's length.`,answer:len,distractors:[s*time,time/(s*5/18),len+20],solution:`Convert ${s} km/h to ${numberLabel(s*5/18)} m/s. Length = speed*time = ${numberLabel(s*5/18)}*${time} = ${numberLabel(len)} metres.`,assessmentStyle:reverse};},
  v=>{const len=160+20*v,platform=200+20*v,time=20+2*v,s=(len+platform)/time*18/5;return{subtopic:"Train speed from platform time",prompt:`A ${len}-metre train clears a ${platform}-metre platform in ${time} seconds. What is its speed in km/h?`,answer:s,distractors:[len/time*18/5,(len+platform)/time,s+9],format:kmphLabel,solution:`Distance = ${len}+${platform}. Speed = distance/${time} m/s, then multiply by 18/5 to obtain ${numberLabel(s)} km/h.`,assessmentStyle:reverse};},
  v=>{const len=140+20*v,bridge=300+30*v,s=63+9*(v%3),ans=(len+bridge)/(s*5/18);return{subtopic:"Train crossing a bridge",prompt:`A train ${len} metres long crosses a ${bridge}-metre bridge at ${s} km/h. Calculate the time from engine entry until the last coach leaves.`,answer:ans,distractors:[bridge/(s*5/18),len/(s*5/18),ans+5],solution:`The train must cover ${len}+${bridge} metres. At ${numberLabel(s*5/18)} m/s, time = (${len}+${bridge})/${numberLabel(s*5/18)} = ${numberLabel(ans)} seconds.`,assessmentStyle:contextual};},
  v=>{const len=180+20*v,tunnel=500+50*v,s=72+9*(v%2),ans=(len+tunnel)/(s*5/18);return{subtopic:"Train through a tunnel",prompt:`A ${len}-metre train enters a ${tunnel}-metre tunnel at ${s} km/h. How many seconds pass before the entire train exits?`,answer:ans,distractors:[tunnel/(s*5/18),len/(s*5/18),ans+5],solution:`Clearance distance = train length + tunnel length = ${len}+${tunnel}. Divide by ${numberLabel(s*5/18)} m/s to obtain ${numberLabel(ans)} seconds.`,assessmentStyle:contextual};},
  v=>{const d=180+30*v,s=60+5*v,stop=10+v,ans=d/s+stop/60;return{subtopic:"Train journey with halt",prompt:`A train covers ${d} km at ${s} km/h and makes one scheduled halt of ${stop} minutes. What is the total elapsed journey time?`,answer:ans,distractors:[d/s,(d+stop)/s,ans+1],format:hoursLabel,solution:`Running time = ${d}/${s} hours. Halt time = ${stop}/60 hour. Add both to get ${numberLabel(ans)} hours.`,assessmentStyle:multi};},
  v=>{const down=18+v,up=10+v,still=(down+up)/2;return{subtopic:"Boat speed in still water",prompt:`A boat travels downstream at ${down} km/h and upstream at ${up} km/h. Find its speed in still water.`,answer:still,distractors:[down-up,(down-up)/2,(down+up)],format:kmphLabel,solution:`Still-water speed = (downstream + upstream)/2 = (${down}+${up})/2 = ${numberLabel(still)} km/h.`,assessmentStyle:direct};},
  v=>{const down=20+v,up=12+v,current=(down-up)/2;return{subtopic:"Stream speed",prompt:`A motorboat's downstream and upstream speeds are ${down} km/h and ${up} km/h. What is the stream's speed?`,answer:current,distractors:[down-up,(down+up)/2,current+2],format:kmphLabel,solution:`Stream speed = (downstream-upstream)/2 = (${down}-${up})/2 = ${numberLabel(current)} km/h.`,assessmentStyle:direct};},
  v=>{const still=14+v,current=3+v%3,ans=still+current;return{subtopic:"Downstream speed",prompt:`A boat moves at ${still} km/h in still water and the stream flows at ${current} km/h. Find the downstream speed.`,answer:ans,distractors:[still-current,still*current,ans+2],format:kmphLabel,solution:`Downstream speed = still-water speed + stream speed = ${still}+${current} = ${ans} km/h.`,assessmentStyle:direct};},
  v=>{const still=16+v,current=3+v%3,ans=still-current;return{subtopic:"Upstream speed",prompt:`A boat's still-water speed is ${still} km/h and the current is ${current} km/h. Find its upstream speed.`,answer:ans,distractors:[still+current,still/current,ans+2],format:kmphLabel,solution:`Upstream speed = still-water speed - current speed = ${still}-${current} = ${ans} km/h.`,assessmentStyle:direct};},
  v=>{const d=48+8*v,still=14+v,current=2+v%3,ans=d/(still+current);return{subtopic:"Downstream travel time",prompt:`A boat covers ${d} km downstream. Its still-water speed is ${still} km/h and the current is ${current} km/h. How long does the trip take?`,answer:ans,distractors:[d/still,d/(still-current),ans+1],format:hoursLabel,solution:`Downstream speed = ${still}+${current}. Time = ${d}/(${still}+${current}) = ${numberLabel(ans)} hours.`,assessmentStyle:contextual};},
  v=>{const d=36+6*v,still=15+v,current=3,ans=d/(still-current);return{subtopic:"Upstream travel time",prompt:`A boat travels ${d} km upstream with a still-water speed of ${still} km/h against a ${current} km/h current. Find the travel time.`,answer:ans,distractors:[d/(still+current),d/still,ans+1],format:hoursLabel,solution:`Upstream speed = ${still}-${current}. Time = ${d}/(${still}-${current}) = ${numberLabel(ans)} hours.`,assessmentStyle:contextual};},
  v=>{const d=60+10*v,still=15+v,current=3+v%2,ans=d/(still+current)+d/(still-current);return{subtopic:"Boat round trip",prompt:`A boat travels ${d} km downstream and returns the same distance upstream. Its still-water speed is ${still} km/h and current speed ${current} km/h. Find total time.`,answer:ans,distractors:[2*d/still,2*d/(still+current),ans+1],format:hoursLabel,solution:`Downstream time = ${d}/(${still}+${current}); upstream time = ${d}/(${still}-${current}). Add them to obtain ${numberLabel(ans)} hours.`,assessmentStyle:multi};},
  v=>{const down=18+v,up=12+v,d=72+12*v,ans=d/down-d/up;return{subtopic:"Upstream-downstream time difference",prompt:`For a river route of ${d} km, a boat moves downstream at ${down} km/h and upstream at ${up} km/h. How many hours longer does the upstream trip take?`,answer:Math.abs(ans),distractors:[d/(down-up),d/down+d/up,Math.abs(ans)+1],format:hoursLabel,solution:`Compute upstream time ${d}/${up} and downstream time ${d}/${down}. Subtract the smaller from the larger to obtain ${numberLabel(Math.abs(ans))} hours.`,assessmentStyle:multi};},
  v=>{const still=15+v,current=3,d=54+9*v,delay=1,ans=d/(still-current)+delay;return{subtopic:"Upstream trip with stoppage",prompt:`A boat goes ${d} km upstream at still-water speed ${still} km/h against a ${current} km/h current and stops for ${delay} hour. Find total elapsed time.`,answer:ans,distractors:[d/(still-current),d/(still+current)+delay,ans+1],format:hoursLabel,solution:`Upstream speed = ${still}-${current}; running time = ${d}/(${still}-${current}). Add the ${delay}-hour stop to get ${numberLabel(ans)} hours.`,assessmentStyle:multi};},
  v=>{const current=3+v%3,time=4+v,ans=current*time;return{subtopic:"Raft drift distance",prompt:`A powerless raft drifts with a stream flowing at ${current} km/h. How far does it travel in ${time} hours?`,answer:ans,distractors:[current+time,current/time,ans+3],format:kilometresLabel,solution:`A raft moves at stream speed. Distance = ${current}*${time} = ${ans} km.`,assessmentStyle:direct};},
  v=>{const d=72+12*v,current=3+v%2,total=9+v/2;const A=2*total,B=-2*d,C=-2*total*current*current,still=(-B+Math.sqrt(B*B-4*A*C))/(2*A);return{subtopic:"Still-water speed from round-trip time",prompt:`A boat covers ${d} km downstream and ${d} km upstream in a total of ${total} hours. The current is ${current} km/h. Find the boat's still-water speed.`,answer:still,distractors:[d/total+current,d/total,still+2],format:kmphLabel,solution:`Let still speed be x. Solve ${d}/(x+${current}) + ${d}/(x-${current}) = ${total}. The positive quadratic root gives ${numberLabel(still)} km/h.`,assessmentStyle:reverse};},
  v=>{const still=18+v,current=4,d=84+12*v,out=d/(still+current),back=d/(still-current),ans=(2*d)/(out+back);return{subtopic:"Average speed for river round trip",prompt:`A boat with still-water speed ${still} km/h travels ${d} km downstream and the same distance upstream in a ${current} km/h current. Find average speed for the round trip.`,answer:ans,distractors:[still,(still+current+still-current)/2,ans+2],format:kmphLabel,solution:`Total distance = ${2*d}. Total time = ${d}/(${still}+${current}) + ${d}/(${still}-${current}). Divide to obtain ${numberLabel(ans)} km/h.`,assessmentStyle:multi};},
  v=>{const width=300+30*v,boat=5+v,current=2+v%2,ans=width/boat;return{subtopic:"River crossing time",prompt:`A boat is aimed perpendicular to a river bank. Its speed relative to water is ${boat} m/s and river width is ${width} metres. How many seconds does it take to reach the opposite bank?`,answer:ans,distractors:[width/(boat+current),width/current,ans+10],solution:`The current changes downstream drift but not perpendicular component. Crossing time = width/perpendicular boat speed = ${width}/${boat} = ${numberLabel(ans)} seconds.`,assessmentStyle:contextual};},
  v=>{const width=240+30*v,boat=6+v,current=2+v%3,time=width/boat,drift=current*time;return{subtopic:"Downstream drift while crossing",prompt:`A boat heads perpendicular across a ${width}-metre river at ${boat} m/s relative to water while the current is ${current} m/s. How far downstream does it drift?`,answer:drift,distractors:[width*current/(boat+current),width/current,drift+20],solution:`Crossing time = ${width}/${boat}. Downstream drift = ${current}*(${width}/${boat}) = ${numberLabel(drift)} metres.`,assessmentStyle:multi};},
  v=>{const train=160+20*v,platform=220+20*v,s=72,time=(train+platform)/(s*5/18),halt=5+v,total=time/60+halt;return{subtopic:"Rail operation caselet",prompt:`A rail caselet states that a ${train}-metre train crosses a ${platform}-metre platform at ${s} km/h and then halts for ${halt} minutes. What total time in minutes elapses from entry to departure?`,answer:total,distractors:[time/60,halt+train/(s*5/18)/60,total+1],format:minutesLabel,solution:`Crossing time = (${train}+${platform})/(${s}*5/18) seconds. Divide by 60 and add the ${halt}-minute halt to get ${numberLabel(total)} minutes.`,assessmentStyle:multi};},
];

export const timeDistancePlacementBank=()=>buildPlacementBank(distancePatterns);
export const trainsBoatsPlacementBank=()=>buildPlacementBank(trainBoatPatterns);
