import { buildPlacementBank, moneyLabel, numberLabel, percentLabel } from "./PlacementQuestionFactory.js";

const direct="direct",reverse="reverse",multi="multi-step",contextual="contextual",caselet="caselet-di";
const mean=a=>a.reduce((s,x)=>s+x,0)/a.length;
const variance=a=>{const m=mean(a);return mean(a.map(x=>(x-m)**2));};

const statisticsPatterns=[
v=>{const data=[10+v,14+v,18+v,22+v,26+v],a=mean(data);return{subtopic:"Arithmetic mean",prompt:`Find the arithmetic mean of the observations ${data.join(", ")}.`,answer:a,distractors:[data.reduce((s,x)=>s+x,0),a+2,a-2],solution:`Add all observations to get ${data.reduce((s,x)=>s+x,0)}, then divide by ${data.length}. Mean=${a}.`,assessmentStyle:direct};},
v=>{const data=[5+v,8+v,11+v,14+v,17+v],a=data[2];return{subtopic:"Median of odd count",prompt:`Determine the median of the ordered data set ${data.join(", ")}.`,answer:a,distractors:[mean(data),data[1],data[3]],solution:`There are ${data.length} ordered values, so the median is the (${data.length}+1)/2=${3}rd value, ${a}.`,assessmentStyle:direct};},
v=>{const data=[4+v,7+v,10+v,13+v,16+v,19+v],a=(data[2]+data[3])/2;return{subtopic:"Median of even count",prompt:`Calculate the median of the ordered observations ${data.join(", ")}.`,answer:a,distractors:[data[2],data[3],mean(data)+1],solution:`For ${data.length} values, average the two central observations ${data[2]} and ${data[3]}: median=(${data[2]}+${data[3]})/2=${a}.`,assessmentStyle:direct};},
v=>{const mode=6+v,data=[mode-2,mode,mode,mode,mode+1,mode+3],a=mode;return{subtopic:"Mode",prompt:`Identify the mode of the data set ${data.join(", ")}.`,answer:a,distractors:[mean(data),mode+1,mode-2],solution:`The value ${mode} appears three times, more frequently than every other observation, so the mode is ${mode}.`,assessmentStyle:direct};},
v=>{const data=[12+v,18+v,25+v,31+v,40+v],a=Math.max(...data)-Math.min(...data);return{subtopic:"Range",prompt:`Find the range of the observations ${data.join(", ")}.`,answer:a,distractors:[Math.max(...data),Math.min(...data),a+2],solution:`Range=maximum-minimum=${Math.max(...data)}-${Math.min(...data)}=${a}.`,assessmentStyle:direct};},
v=>{const scores=[60+v,75+v,85+v],weights=[2,3,5],a=scores.reduce((s,x,i)=>s+x*weights[i],0)/10;return{subtopic:"Weighted mean",prompt:`A candidate scores ${scores[0]}, ${scores[1]}, and ${scores[2]} in sections weighted ${weights[0]}, ${weights[1]}, and ${weights[2]}. Find the weighted mean score.`,answer:a,distractors:[mean(scores),scores.reduce((s,x)=>s+x,0)/10,a+2],solution:`Weighted total=${scores[0]}*2+${scores[1]}*3+${scores[2]}*5. Divide by total weight 10 to obtain ${numberLabel(a)}.`,assessmentStyle:multi};},
v=>{const n1=20+v,n2=30+v,m1=60+v,m2=70+v,a=(n1*m1+n2*m2)/(n1+n2);return{subtopic:"Combined mean",prompt:`Batch A has ${n1} trainees averaging ${m1}; Batch B has ${n2} trainees averaging ${m2}. Find the combined average.`,answer:a,distractors:[(m1+m2)/2,a+2,a-2],solution:`Combined total=${n1}*${m1}+${n2}*${m2}. Divide by ${n1}+${n2}=${n1+n2} to get ${numberLabel(a)}.`,assessmentStyle:multi};},
v=>{const f1=2+v,f2=3+v,target=22,unknown=(target*(f1+f2)-10*f1-20*f2)/(30-target);return{subtopic:"Missing frequency",prompt:`Values 10, 20, and 30 have frequencies ${f1}, ${f2}, and x. If their mean is ${target}, find x.`,answer:unknown,distractors:[f1+f2,target,unknown+2],solution:`Set (10*${f1}+20*${f2}+30x)/(${f1}+${f2}+x)=${target}. Expand and isolate x to obtain ${numberLabel(unknown)}.`,assessmentStyle:reverse};},
v=>{const mids=[10,20,30,40],freq=[2+v,3+v,4+v,2+v],total=freq.reduce((s,x)=>s+x,0),a=mids.reduce((s,x,i)=>s+x*freq[i],0)/total;return{subtopic:"Grouped-data mean",prompt:`Class midpoints ${mids.join(", ")} have frequencies ${freq.join(", ")}. Estimate the grouped mean.`,answer:a,distractors:[mean(mids),total,a+2],solution:`Compute sum(f*x)=${mids.reduce((s,x,i)=>s+x*freq[i],0)} and sum(f)=${total}; grouped mean=${numberLabel(a)}.`,assessmentStyle:multi};},
v=>{const data=[2+v,4+v,6+v,8+v],a=variance(data);return{subtopic:"Population variance",prompt:`Treating ${data.join(", ")} as a population, calculate its variance.`,answer:a,distractors:[Math.sqrt(a),a*data.length,a+2],solution:`Mean=${mean(data)}. Squared deviations sum to ${a*data.length}; divide by population size ${data.length}, giving variance ${a}.`,assessmentStyle:multi};},
v=>{const data=[3+v,5+v,7+v,9+v],a=Math.sqrt(variance(data));return{subtopic:"Population standard deviation",prompt:`Find the population standard deviation of ${data.join(", ")}.`,answer:a,distractors:[variance(data),a*data.length,a+1],solution:`Mean=${mean(data)}; population variance=${variance(data)}. Standard deviation=sqrt(${variance(data)})=${numberLabel(a)}.`,assessmentStyle:multi};},
v=>{const m=40+5*v,sd=4+v,a=sd/m*100;return{subtopic:"Coefficient of variation",prompt:`A process has mean output ${m} and standard deviation ${sd}. Find its coefficient of variation.`,answer:a,distractors:[m/sd,sd/m,a+2],format:percentLabel,solution:`CV=(standard deviation/mean)*100=(${sd}/${m})*100=${numberLabel(a)}%.`,assessmentStyle:contextual};},
v=>{const data=[2+v,4+v,6+v,8+v,10+v,12+v,14+v],q1=data[1],q3=data[5],a=q3-q1;return{subtopic:"Interquartile range",prompt:`For the ordered data ${data.join(", ")}, use the median-of-halves method and find the interquartile range.`,answer:a,distractors:[q1,q3,data.at(-1)-data[0]],solution:`Lower-half median Q1=${q1}; upper-half median Q3=${q3}. IQR=Q3-Q1=${q3}-${q1}=${a}.`,assessmentStyle:multi};},
v=>{const below=18+v,total=30+2*v,a=below/total*100;return{subtopic:"Percentile rank",prompt:`In a group of ${total} observations, ${below} values lie below a particular score. Using the basic percentage-below definition, find its percentile rank.`,answer:a,distractors:[below/total,total-below,a+5],format:percentLabel,solution:`Percentile rank=values below/total*100=${below}/${total}*100=${numberLabel(a)}%.`,assessmentStyle:contextual};},
v=>{const freq=[3+v,5+v,7+v,4+v],a=freq.reduce((s,x)=>s+x,0);return{subtopic:"Total frequency",prompt:`A frequency table lists class frequencies ${freq.join(", ")}. How many observations are represented in total?`,answer:a,distractors:[Math.max(...freq),mean(freq),a+4],solution:`Add every class frequency: ${freq.join("+")}=${a} observations.`,assessmentStyle:direct};},
v=>{const share=20+5*v,a=share/100*360;return{subtopic:"Pie-chart angle",prompt:`A category represents ${share}% of a data set. What central angle should represent it in a pie chart?`,answer:a,distractors:[share*180/100,360-share,a+10],solution:`Pie angle=share/100*360=${share}/100*360=${a} degrees.`,assessmentStyle:contextual};},
v=>{const freq=20+2*v,width=5+v,a=freq/width;return{subtopic:"Frequency density",prompt:`A histogram class has frequency ${freq} and class width ${width}. Calculate its frequency density.`,answer:a,distractors:[freq*width,width/freq,a+2],solution:`Frequency density=frequency/class width=${freq}/${width}=${numberLabel(a)}.`,assessmentStyle:contextual};},
v=>{const data=[100+5*v,110+5*v,120+5*v],a=mean(data);return{subtopic:"Moving average",prompt:`Monthly demand for three consecutive months is ${data.join(", ")} units. Find the three-month moving average.`,answer:a,distractors:[data.at(-1)-data[0],data.reduce((s,x)=>s+x,0),a+5],solution:`Three-month moving average=(${data.join("+")})/3=${a}.`,assessmentStyle:contextual};},
v=>{const base=80+5*v,current=100+10*v,a=current/base*100;return{subtopic:"Simple price index",prompt:`A commodity's base-period price is ${base} and current price is ${current}. Compute the simple price index with base 100.`,answer:a,distractors:[(current-base)/base*100,base/current*100,a+10],solution:`Price index=current/base*100=${current}/${base}*100=${numberLabel(a)}.`,assessmentStyle:contextual};},
v=>{const old=500+50*v,newV=600+70*v,a=(newV-old)/old*100;return{subtopic:"Growth rate from series",prompt:`A time series rises from ${old} units to ${newV} units. Find the percentage growth over the interval.`,answer:a,distractors:[newV/old*100,(newV-old)/newV*100,a+5],format:percentLabel,solution:`Growth=(new-old)/old*100=(${newV}-${old})/${old}*100=${numberLabel(a)}%.`,assessmentStyle:contextual};},
v=>{const x=[1,2,3,4],y=x.map(n=>n*(2+v));return{subtopic:"Perfect positive correlation",prompt:`Paired observations are x=[${x.join(", ")}] and y=[${y.join(", ")}]. What is their Pearson correlation coefficient?`,answer:1,distractors:[0,-1,2+v],solution:`Every y value equals ${2+v}*x with a positive constant. All points lie exactly on an increasing straight line, so r=1.`,assessmentStyle:direct};},
v=>{const favourable=12+v,total=40+2*v,a=favourable/total;return{subtopic:"Empirical probability",prompt:`An outcome occurred ${favourable} times in ${total} recorded trials. Estimate its empirical probability.`,answer:a,distractors:[(total-favourable)/total,favourable/(total-favourable),a+0.1],solution:`Empirical probability=observed favourable count/total trials=${favourable}/${total}=${numberLabel(a)}.`,assessmentStyle:contextual};},
v=>{const data=[20+v,22+v,24+v,26+v],old=mean(data),outlier=60+v,newMean=(data.reduce((s,x)=>s+x,0)+outlier)/5,a=newMean-old;return{subtopic:"Outlier effect on mean",prompt:`The mean of ${data.join(", ")} is compared with the mean after adding outlier ${outlier}. By how much does the mean increase?`,answer:a,distractors:[outlier-old,newMean,a+2],solution:`Old mean=${old}. New mean=(${data.reduce((s,x)=>s+x,0)}+${outlier})/5=${numberLabel(newMean)}. Increase=${numberLabel(newMean)}-${old}=${numberLabel(a)}.`,assessmentStyle:multi};},
v=>{const n=20+v,reported=50+v,wrong=30+v,right=60+v,a=reported+(right-wrong)/n;return{subtopic:"Corrected mean",prompt:`The mean of ${n} entries was reported as ${reported}, but ${wrong} was used instead of ${right}. Find the corrected mean.`,answer:a,distractors:[reported+right-wrong,reported,a+1],solution:`Correct total=reported total-wrong+right=${n}*${reported}-${wrong}+${right}. Divide by ${n}; corrected mean=${numberLabel(a)}.`,assessmentStyle:reverse};},
v=>{const n1=20+v,n2=25+v,m1=50+v,m2=60+v,var1=9,var2=16,combinedMean=(n1*m1+n2*m2)/(n1+n2),pooled=(n1*(var1+(m1-combinedMean)**2)+n2*(var2+(m2-combinedMean)**2))/(n1+n2);return{subtopic:"Combined population variance",prompt:`Groups of sizes ${n1} and ${n2} have means ${m1}, ${m2} and variances ${var1}, ${var2}. Find the variance of the combined population.`,answer:pooled,distractors:[(var1+var2)/2,(n1*var1+n2*var2)/(n1+n2),pooled+2],solution:`Combined mean=${numberLabel(combinedMean)}. Add each group's within variance and squared mean shift: [${n1}(${var1}+shift1^2)+${n2}(${var2}+shift2^2)]/${n1+n2}=${numberLabel(pooled)}.`,assessmentStyle:multi};},
];

const diPatterns=[
v=>{const sales=[120+10*v,150+10*v,180+10*v,210+10*v],a=Math.max(...sales);return{subtopic:"Table maximum lookup",prompt:`Quarterly sales table: Q1=${sales[0]}, Q2=${sales[1]}, Q3=${sales[2]}, Q4=${sales[3]}. What is the highest quarterly sales figure?`,answer:a,distractors:[mean(sales),Math.min(...sales),sales.reduce((s,x)=>s+x,0)],solution:`Compare the four table values directly. The maximum of ${sales.join(", ")} is ${a}.`,assessmentStyle:caselet};},
v=>{const a1=100+10*v,a2=130+15*v,g=(a2-a1)/a1*100;return{subtopic:"Quarterly percentage change",prompt:`A dashboard shows output rising from ${a1} units in Q1 to ${a2} units in Q2. Calculate the percentage increase.`,answer:g,distractors:[a2/a1*100,(a2-a1)/a2*100,g+5],format:percentLabel,solution:`Increase=${a2}-${a1}. Divide by Q1 base ${a1} and multiply by 100 to obtain ${numberLabel(g)}%.`,assessmentStyle:direct};},
v=>{const shares=[20+v,25+v,30+v],other=100-shares.reduce((s,x)=>s+x,0);return{subtopic:"Pie-chart missing share",prompt:`A market-share pie chart lists A=${shares[0]}%, B=${shares[1]}%, and C=${shares[2]}%. What percentage belongs to all other firms?`,answer:other,distractors:[shares.reduce((s,x)=>s+x,0),100-shares[0],other+5],format:percentLabel,solution:`Listed share=${shares.join("+")}=${shares.reduce((s,x)=>s+x,0)}%. Subtract from 100% to get ${other}%.`,assessmentStyle:reverse};},
v=>{const budget=500000+50000*v,shares=[30,25,20],remaining=25,a=budget*remaining/100;return{subtopic:"Budget residual",prompt:`A budget caselet allocates ${shares[0]}% to salaries, ${shares[1]}% to equipment, and ${shares[2]}% to training from Rs ${budget}. Find the unallocated amount.`,answer:a,distractors:[budget*shares[0]/100,budget*(100-shares[0])/100,a+10000],format:moneyLabel,solution:`Allocated share=${shares.join("+")}=${75}%, so residual=${remaining}%. Amount=${budget}*${remaining}/100=Rs ${a}.`,assessmentStyle:multi};},
v=>{const depts=[20+v,30+v,25+v,35+v],a=depts.reduce((s,x)=>s+x,0);return{subtopic:"Headcount table total",prompt:`Department headcounts are Engineering=${depts[0]}, Sales=${depts[1]}, Support=${depts[2]}, Operations=${depts[3]}. Find total headcount.`,answer:a,distractors:[Math.max(...depts),mean(depts),a-depts[0]],solution:`Add all department values: ${depts.join("+")}=${a} employees.`,assessmentStyle:caselet};},
v=>{const planned=1000+100*v,actual=850+90*v,a=(planned-actual)/planned*100;return{subtopic:"Production shortfall",prompt:`A production chart shows a target of ${planned} units and actual output of ${actual}. What is the shortfall as a percentage of target?`,answer:a,distractors:[actual/planned*100,(planned-actual)/actual*100,a+5],format:percentLabel,solution:`Shortfall=${planned}-${actual}. Divide by target ${planned} and multiply by 100 to get ${numberLabel(a)}%.`,assessmentStyle:reverse};},
v=>{const produced=2000+200*v,defects=40+5*v,a=defects/produced*100;return{subtopic:"Defect-rate table",prompt:`A quality table records ${produced} units produced and ${defects} defective units. Find the defect rate.`,answer:a,distractors:[(produced-defects)/produced*100,defects/(produced-defects)*100,a+1],format:percentLabel,solution:`Defect rate=defects/produced*100=${defects}/${produced}*100=${numberLabel(a)}%.`,assessmentStyle:caselet};},
v=>{const opening=500+50*v,received=200+20*v,sold=300+30*v,a=opening+received-sold;return{subtopic:"Inventory movement",prompt:`An inventory table lists opening stock ${opening}, receipts ${received}, and issues ${sold}. Find closing stock.`,answer:a,distractors:[opening-received+sold,opening+received,a+50],solution:`Closing=opening+receipts-issues=${opening}+${received}-${sold}=${a}.`,assessmentStyle:multi};},
v=>{const price=50+5*v,volume=1000+100*v,a=price*volume;return{subtopic:"Price-volume revenue",prompt:`A sales table records unit price Rs ${price} and volume ${volume} units. Calculate total revenue.`,answer:a,distractors:[price+volume,volume/price,a+1000],format:moneyLabel,solution:`Revenue=unit price*volume=${price}*${volume}=Rs ${a}.`,assessmentStyle:caselet};},
v=>{const values=[100+10*v,115+10*v,130+10*v,150+10*v],a=values.at(-1)-values[0];return{subtopic:"Line-chart absolute growth",prompt:`A line chart reports values ${values.join(", ")} across four years. What is the absolute increase from the first to the last year?`,answer:a,distractors:[values.at(-1)/values[0]*100,values.reduce((s,x)=>s+x,0),a+10],solution:`Absolute increase=last-first=${values.at(-1)}-${values[0]}=${a}.`,assessmentStyle:caselet};},
v=>{const a1=60+5*v,b1=40+5*v,a2=75+5*v,b2=55+5*v,growth=(a2+b2)-(a1+b1);return{subtopic:"Stacked-category growth",prompt:`A stacked chart gives Year 1 categories A=${a1}, B=${b1}; Year 2 gives A=${a2}, B=${b2}. Find growth in the combined total.`,answer:growth,distractors:[a2-a1,b2-b1,a2+b2],solution:`Year1 total=${a1}+${b1}; Year2 total=${a2}+${b2}. Growth=(${a2}+${b2})-(${a1}+${b1})=${growth}.`,assessmentStyle:multi};},
v=>{const north=120+10*v,south=90+10*v,a=north/south;return{subtopic:"Regional ratio",prompt:`A regional table reports North=${north} units and South=${south} units. Find the North-to-South ratio as a numerical multiple.`,answer:a,distractors:[south/north,north-south,a+0.5],solution:`Requested multiple=North/South=${north}/${south}=${numberLabel(a)}.`,assessmentStyle:direct};},
v=>{const start=100+10*v,end=144+12*v,a=(Math.sqrt(end/start)-1)*100;return{subtopic:"Two-year CAGR",prompt:`A business metric grows from ${start} to ${end} over two years. Find the compound annual growth rate.`,answer:a,distractors:[(end-start)/start/2*100,(end/start-1)*100,a+5],format:percentLabel,solution:`CAGR=[(end/start)^(1/2)-1]*100=[(${end}/${start})^(1/2)-1]*100=${numberLabel(a)}%.`,assessmentStyle:reverse};},
v=>{const scores=[70+v,80+v,90+v],weights=[20,30,50],a=scores.reduce((s,x,i)=>s+x*weights[i],0)/100;return{subtopic:"Weighted score dashboard",prompt:`A dashboard weights scores ${scores.join(", ")} at ${weights.join("%, ")}%. Find the overall weighted score.`,answer:a,distractors:[mean(scores),scores.reduce((s,x)=>s+x,0),a+2],solution:`Weighted score=(${scores[0]}*20+${scores[1]}*30+${scores[2]}*50)/100=${numberLabel(a)}.`,assessmentStyle:multi};},
v=>{const values=[80+v,90+v,100+v,110+v],a=mean(values);return{subtopic:"Chart average",prompt:`Four monthly values shown on a chart are ${values.join(", ")}. Calculate their arithmetic average.`,answer:a,distractors:[values.reduce((s,x)=>s+x,0),Math.max(...values),a+5],solution:`Total=${values.join("+")}=${values.reduce((s,x)=>s+x,0)}. Divide by 4 to get ${a}.`,assessmentStyle:direct};},
v=>{const old=200+20*v,newV=250+25*v,a=(newV-old)/old*100;return{subtopic:"Indexed percentage change",prompt:`An index moves from ${old} to ${newV}. Calculate the percentage change using the earlier index as base.`,answer:a,distractors:[newV/old*100,(newV-old)/newV*100,a+5],format:percentLabel,solution:`Percentage change=(new-old)/old*100=(${newV}-${old})/${old}*100=${numberLabel(a)}%.`,assessmentStyle:direct};},
v=>{const units=1000+100*v,share=30+v,price=50+v,a=units*share/100*price;return{subtopic:"Combined chart revenue",prompt:`A volume chart shows ${units} total units; a pie chart assigns ${share}% to Product A, priced at Rs ${price}. Find Product A revenue.`,answer:a,distractors:[units*price,units*share/100,share*price],format:moneyLabel,solution:`Product A units=${units}*${share}/100. Multiply by Rs ${price}: revenue=Rs ${numberLabel(a)}.`,assessmentStyle:multi};},
v=>{const rows=[[20+v,30+v],[25+v,35+v]],a=rows[0][1]+rows[1][1];return{subtopic:"Cross-table column total",prompt:`A two-row table is [[${rows[0].join(",")}],[${rows[1].join(",")}]]. Find the total of the second column.`,answer:a,distractors:[rows[0][0]+rows[1][0],rows.flat().reduce((s,x)=>s+x,0),a+5],solution:`Second-column entries are ${rows[0][1]} and ${rows[1][1]}. Add them: ${rows[0][1]}+${rows[1][1]}=${a}.`,assessmentStyle:direct};},
v=>{const total=500+50*v,known=[100+10*v,120+10*v,140+10*v],a=total-known.reduce((s,x)=>s+x,0);return{subtopic:"Missing table value",prompt:`A category total is ${total}. Three listed components are ${known.join(", ")}; the fourth is missing. Find the missing value.`,answer:a,distractors:[total-known[0],mean(known),a+20],solution:`Missing=total-sum(known)=${total}-(${known.join("+")})=${a}.`,assessmentStyle:reverse};},
v=>{const values=[50+v,80+2*v,65+v,95+2*v],a=Math.max(...values)-Math.min(...values);return{subtopic:"Maximum-minimum spread",prompt:`A comparative chart lists ${values.join(", ")}. What is the spread between its maximum and minimum values?`,answer:a,distractors:[Math.max(...values),Math.min(...values),mean(values)],solution:`Maximum=${Math.max(...values)}, minimum=${Math.min(...values)}; spread=${Math.max(...values)}-${Math.min(...values)}=${a}.`,assessmentStyle:direct};},
v=>{const values=[100+v,140+v,120+v,160+v],sorted=[...values].sort((a,b)=>b-a),a=sorted[1];return{subtopic:"Second-highest ranking",prompt:`Four branch scores are ${values.join(", ")}. Which numerical score ranks second highest?`,answer:a,distractors:[sorted[0],sorted[2],sorted[3]],solution:`Sort descending: ${sorted.join(", ")}. The second entry is ${a}.`,assessmentStyle:direct};},
v=>{const total=800+80*v,part=200+20*v,a=part/total*100;return{subtopic:"Contribution share",prompt:`A division contributes ${part} units to a company total of ${total}. What percentage of the total comes from that division?`,answer:a,distractors:[total/part,part/(total-part)*100,a+5],format:percentLabel,solution:`Contribution share=part/total*100=${part}/${total}*100=${numberLabel(a)}%.`,assessmentStyle:direct};},
v=>{const target=1200+100*v,actual=1000+80*v,a=target-actual;return{subtopic:"Target gap",prompt:`A KPI dashboard shows target ${target} and actual ${actual}. How many additional units are needed to meet the target exactly?`,answer:a,distractors:[target+actual,actual/target*100,a+20],solution:`Required gap=target-actual=${target}-${actual}=${a} units.`,assessmentStyle:reverse};},
v=>{const applicants=1000+100*v,screen=70,interview=40,offers=50,a=applicants*screen/100*interview/100*offers/100;return{subtopic:"Recruitment funnel caselet",prompt:`A recruitment funnel starts with ${applicants} applicants; ${screen}% clear screening, ${interview}% of those clear interviews, and ${offers}% of finalists accept. How many accept?`,answer:a,distractors:[applicants*(screen+interview+offers)/300,applicants*screen/100,applicants*offers/100],solution:`Apply stages sequentially: ${applicants}*${screen}/100*${interview}/100*${offers}/100=${numberLabel(a)} acceptances.`,assessmentStyle:multi};},
v=>{const unitsA=500+50*v,priceA=40+v,unitsB=300+30*v,priceB=60+v,a=unitsA*priceA+unitsB*priceB;return{subtopic:"Two-table revenue inference",prompt:`A volume table gives A=${unitsA}, B=${unitsB}; a price table gives A=Rs ${priceA}, B=Rs ${priceB}. Find combined revenue.`,answer:a,distractors:[(unitsA+unitsB)*(priceA+priceB),unitsA*priceA,unitsB*priceB],format:moneyLabel,solution:`Revenue A=${unitsA}*${priceA}; revenue B=${unitsB}*${priceB}. Add them to obtain Rs ${a}.`,assessmentStyle:multi};},
];

export const statisticsPlacementBank=()=>buildPlacementBank(statisticsPatterns);
export const dataInterpretationPlacementBank=()=>buildPlacementBank(diPatterns);
