import {
  buildPlacementBank,
  daysLabel,
  hoursLabel,
  litresLabel,
  moneyLabel,
  numberLabel,
  percentLabel,
  lcmValue,
} from "./PlacementQuestionFactory.js";

const direct = "direct";
const reverse = "reverse";
const multi = "multi-step";
const contextual = "contextual";

const mixturePatterns = [
  v => { const a=20+2*v,b=50+2*v,x=10+v,y=15+v,ans=(a*x+b*y)/(x+y); return {subtopic:"Weighted concentration",prompt:`A laboratory combines ${x} litres of a ${a}% solution with ${y} litres of a ${b}% solution. What is the concentration of the resulting mixture?`,answer:ans,distractors:[(a+b)/2,ans+2,ans-2],format:percentLabel,solution:`Pure material equals ${x} x ${a}/100 + ${y} x ${b}/100. Divide that sum by ${x+y} litres and multiply by 100 to obtain ${numberLabel(ans)}%.`,assessmentStyle:direct}; },
  v => { const low=18+v,high=54+v,target=30+v,ans=(high-target)/(target-low); return {subtopic:"Alligation parts",prompt:`A manufacturer must blend solutions of ${low}% and ${high}% strength to obtain a ${target}% solution. How many parts of the weaker solution are required per part of the stronger solution?`,answer:ans,distractors:[1/ans,(high-low)/(target-low),ans+1],solution:`By alligation, weaker:stronger = (${high}-${target}):(${target}-${low}). Therefore weaker parts per stronger part = ${high-target}/${target-low} = ${numberLabel(ans)}.`,assessmentStyle:contextual}; },
  v => { const p1=40+2*v,p2=70+3*v,q1=12+v,q2=8+v,ans=(p1*q1+p2*q2)/(q1+q2); return {subtopic:"Weighted mean price",prompt:`A retailer mixes ${q1} kg of grain costing Rs ${p1} per kg with ${q2} kg costing Rs ${p2} per kg. Find the average cost per kilogram of the blend.`,answer:ans,distractors:[(p1+p2)/2,ans+3,ans-3],format:moneyLabel,solution:`Total cost is ${q1} x ${p1} + ${q2} x ${p2}. Divide by the total mass ${q1+q2} kg to get Rs ${numberLabel(ans)} per kg.`,assessmentStyle:direct}; },
  v => { const vol=40+5*v,c=20+v,t=35+v,ans=vol*(t-c)/(100-t); return {subtopic:"Pure solute addition",prompt:`A tank contains ${vol} litres of a ${c}% chemical solution. How many litres of pure chemical must be added to raise its concentration to ${t}%?`,answer:ans,distractors:[vol*(t-c)/100,ans+2,ans-2],format:litresLabel,solution:`Let x litres be added. Then (${c}/100 x ${vol} + x)/(${vol}+x) = ${t}/100. Rearranging gives x = ${vol} x (${t}-${c})/(100-${t}) = ${numberLabel(ans)} litres.`,assessmentStyle:reverse}; },
  v => { const vol=50+5*v,c=60+v,t=40+v,ans=vol*(c-t)/t; return {subtopic:"Dilution with water",prompt:`A processing unit has ${vol} litres of a ${c}% concentrate. How much water must be added so that the concentration becomes ${t}%?`,answer:ans,distractors:[vol*(c-t)/100,ans+5,ans-5],format:litresLabel,solution:`The pure material remains ${vol} x ${c}/100. If x litres of water is added, ${vol*c/100}/(${vol}+x) = ${t}/100. Solving gives x = ${numberLabel(ans)} litres.`,assessmentStyle:reverse}; },
  v => { const vol=80+5*v,c=25+v,t=40+v,ans=vol*(1-c/t); return {subtopic:"Concentration by evaporation",prompt:`A vessel holds ${vol} litres of a ${c}% salt solution. Only water evaporates. How many litres must evaporate for the solution to become ${t}% salt?`,answer:ans,distractors:[vol*(t-c)/100,ans+4,ans-4],format:litresLabel,solution:`Salt quantity stays ${vol*c/100} litres. Required final volume is (${vol} x ${c})/${t}; subtract it from ${vol} to obtain ${numberLabel(ans)} litres evaporated.`,assessmentStyle:reverse}; },
  v => { const vol=100+10*v,c=70-v,x=10+2*v,ans=c*(1-x/vol); return {subtopic:"Single replacement dilution",prompt:`From a tank containing ${vol} litres of a ${c}% solution, ${x} litres are removed and replaced with water. What percentage of active material remains in the final mixture?`,answer:ans,distractors:[c-x/vol*100,c*(1+x/vol),ans+3],format:percentLabel,solution:`Removal leaves the fraction 1-${x}/${vol} of the active material. Replacement adds no active material, so final concentration = ${c} x (1-${x}/${vol}) = ${numberLabel(ans)}%.`,assessmentStyle:multi}; },
  v => { const vol=120+10*v,c=80-v,x=12+v,n=2+v%2,ans=c*(1-x/vol)**n; return {subtopic:"Repeated replacement",prompt:`A tank contains ${vol} litres of a ${c}% solution. The operation of removing ${x} litres and replacing it with water is performed ${n} times. Find the final concentration.`,answer:ans,distractors:[c*(1-n*x/vol),c*(1-x/vol),ans+2],format:percentLabel,solution:`Each operation retains the fraction 1-${x}/${vol}. After ${n} operations the retained fraction is (1-${x}/${vol})^${n}; multiply by ${c}% to obtain ${numberLabel(ans)}%.`,assessmentStyle:multi}; },
  v => { const vol=100+10*v,c=64,target=36,ans=vol*(1-Math.sqrt(target/c)); return {subtopic:"Replacement quantity from target",prompt:`A tank contains ${vol} litres of a ${c}% solution. An equal quantity is removed and replaced with water twice, leaving a ${target}% solution. Find the quantity replaced each time.`,answer:ans,distractors:[vol*(1-target/c),ans+5,ans-5],format:litresLabel,solution:`If x litres is replaced each time, ${target}/${c} = (1-x/${vol})^2. Take the square root, then solve x = ${vol}(1-sqrt(${target}/${c})) = ${numberLabel(ans)} litres.`,assessmentStyle:reverse}; },
  v => { const vol=90+10*v,c=30+v,x=10+v,add=70+v,ans=c*(1-x/vol)+add*x/vol; return {subtopic:"Replacement by stronger solution",prompt:`A vessel has ${vol} litres of a ${c}% solution. If ${x} litres are withdrawn and replaced with a ${add}% solution, what is the new concentration?`,answer:ans,distractors:[c+(add-c)*x/100,(c+add)/2,ans+2],format:percentLabel,solution:`After withdrawal, active material is ${c}/100 x (${vol}-${x}). The replacement contributes ${add}/100 x ${x}. Add both amounts, divide by ${vol}, then multiply by 100 to get ${numberLabel(ans)}%.`,assessmentStyle:multi}; },
  v => { const vol=60+5*v,c=45+v,ans=c*vol/100; return {subtopic:"Pure component quantity",prompt:`A quality-control sample contains ${vol} litres of a ${c}% solution. How many litres of pure active ingredient are present in the sample?`,answer:ans,distractors:[vol*(100-c)/100,c,ans+3],format:litresLabel,solution:`Pure ingredient equals total volume x concentration fraction = ${vol} x ${c}/100 = ${numberLabel(ans)} litres. The remaining liquid is solvent.`,assessmentStyle:direct}; },
  v => { const milk=40+5*v,water=10+v,ratioDen=2+v%2,ans=milk*ratioDen-water; return {subtopic:"Milk-water target ratio",prompt:`A can contains ${milk} litres of milk and ${water} litres of water. How much water must be added so that the final milk-to-water ratio becomes 1:${ratioDen}?`,answer:ans,distractors:[milk/ratioDen-water,milk-water,ans+5],format:litresLabel,solution:`Milk remains ${milk} litres. For ratio 1:${ratioDen}, final water must be ${milk} x ${ratioDen} = ${milk*ratioDen} litres. Subtract existing water ${water}; addition = ${numberLabel(ans)} litres.`,assessmentStyle:reverse}; },
  v => { const milk=50+5*v,water=40+3*v,targetDen=0.5,ans=water-milk*targetDen; return {subtopic:"Selective solvent removal",prompt:`A dairy blend contains ${milk} litres of milk and ${water} litres of water. If only water can be removed, how much should be removed to make the milk-to-water ratio 2:1?`,answer:ans,distractors:[water-milk*2,milk-water,ans+4],format:litresLabel,solution:`For a 2:1 ratio, final water must equal ${milk}/2 = ${milk*targetDen} litres. Existing water is ${water} litres, so remove ${numberLabel(ans)} litres.`,assessmentStyle:contextual}; },
  v => { const a=30+v,b=70-v,x=20+v,y=15+v,ans=(a*x+b*y)/(x+y); return {subtopic:"Alloy composition",prompt:`An engineering unit melts ${x} kg of an alloy containing ${a}% copper with ${y} kg of another alloy containing ${b}% copper. Find the copper percentage in the final alloy.`,answer:ans,distractors:[(a+b)/2,ans+4,ans-4],format:percentLabel,solution:`Copper mass is ${x} x ${a}/100 + ${y} x ${b}/100. Divide by total alloy mass ${x+y} kg and multiply by 100 to obtain ${numberLabel(ans)}%.`,assessmentStyle:contextual}; },
  v => { const q1=10+v,q2=12+v,q3=8+v,c1=20+v,c2=45+v,c3=70-v,ans=(q1*c1+q2*c2+q3*c3)/(q1+q2+q3); return {subtopic:"Three-source blend",prompt:`A plant combines ${q1} litres at ${c1}%, ${q2} litres at ${c2}%, and ${q3} litres at ${c3}% concentration. What is the concentration of the combined batch?`,answer:ans,distractors:[(c1+c2+c3)/3,ans+3,ans-3],format:percentLabel,solution:`Add active quantities ${q1} x ${c1}/100, ${q2} x ${c2}/100 and ${q3} x ${c3}/100. Divide by total volume ${q1+q2+q3}, giving ${numberLabel(ans)}%.`,assessmentStyle:direct}; },
  v => { const base=30+5*v,c1=20+v,c2=65+v,target=35+v,ans=base*(target-c1)/(c2-target); return {subtopic:"Unknown stronger quantity",prompt:`A batch has ${base} litres of a ${c1}% solution. How many litres of a ${c2}% solution must be mixed with it to obtain a ${target}% blend?`,answer:ans,distractors:[base*(target-c1)/(c2-c1),ans+5,ans-5],format:litresLabel,solution:`Let x be the stronger quantity. Equate active material: ${base*c1/100} + ${c2}/100 x = ${target}/100(${base}+x). Solving gives x = ${numberLabel(ans)} litres.`,assessmentStyle:reverse}; },
  v => { const vol=50+5*v,added=8+v,target=40+v,initial=(target*(vol+added)-100*added)/vol; return {subtopic:"Original concentration",prompt:`After ${added} litres of pure chemical is added to ${vol} litres of an unknown solution, the mixture becomes ${target}% strong. Find the original concentration.`,answer:initial,distractors:[target-added/vol*100,target+added,initial+3],format:percentLabel,solution:`Let original strength be c%. Active balance gives c/100 x ${vol} + ${added} = ${target}/100 x (${vol+added}). Rearrange to obtain c = ${numberLabel(initial)}%.`,assessmentStyle:reverse}; },
  v => { const cheap=45+v,costly=75+2*v,q1=20+v,q2=10+v,profit=15+v,cp=(cheap*q1+costly*q2)/(q1+q2),ans=cp*(1+profit/100); return {subtopic:"Blend selling price",prompt:`A merchant mixes ${q1} kg at Rs ${cheap} per kg with ${q2} kg at Rs ${costly} per kg and wants ${profit}% profit on the entire blend. What selling price per kg is required?`,answer:ans,distractors:[cp+profit,(cheap+costly)/2*(1+profit/100),ans+5],format:moneyLabel,solution:`Weighted cost per kg = (${q1} x ${cheap} + ${q2} x ${costly})/${q1+q2} = ${numberLabel(cp)}. Multiply by 1+${profit}/100 to get Rs ${numberLabel(ans)}.`,assessmentStyle:multi}; },
  v => { const milk=50+5*v,water=10+v,ans=water/milk*100; return {subtopic:"Adulteration profit",prompt:`A vendor buys ${milk} litres of milk, adds ${water} litres of free water, and sells the mixture at the milk's cost price per litre. Ignoring other costs, find the profit percentage.`,answer:ans,distractors:[water/(milk+water)*100,milk/water*100,ans+5],format:percentLabel,solution:`Saleable volume = ${milk}+${water}. Cost is for ${milk} litres, so profit units = ${milk+water}-${milk} = ${water}; profit% = ${water}/${milk} * 100 = ${numberLabel(ans)}%.`,assessmentStyle:multi}; },
  v => { const vol=100+10*v,c=50+v,remove=10+v,add=6+v,ans=(c*(vol-remove)/100+add)/(vol-remove+add)*100; return {subtopic:"Drain then enrich",prompt:`A tank holds ${vol} litres of a ${c}% solution. First ${remove} litres are drained; then ${add} litres of pure solute are added. What is the final concentration?`,answer:ans,distractors:[c*(1-remove/vol)+add,ans+4,ans-4],format:percentLabel,solution:`After draining, active amount is ${c}/100 x (${vol}-${remove}). Add ${add} litres of pure solute, then divide by final volume ${vol-remove+add} and multiply by 100 to obtain ${numberLabel(ans)}%.`,assessmentStyle:multi}; },
  v => { const vol=80+5*v,c=40+v,loss=12+v,ans=c*vol/(vol-loss); return {subtopic:"Solvent leakage",prompt:`A container has ${vol} litres of a ${c}% solution. During transport, ${loss} litres of only solvent leaks out. What concentration does the remaining liquid have?`,answer:ans,distractors:[c*vol/(vol+loss),c+loss/vol*100,ans+3],format:percentLabel,solution:`Active material = ${vol} * ${c}/100 litres, while new volume = ${vol}-${loss}. Divide the active amount by that new volume and multiply by 100 to get ${numberLabel(ans)}%.`,assessmentStyle:multi}; },
  v => { const q=25+v,c=32+v,ans=q*c/100; return {subtopic:"Component inventory",prompt:`A production batch contains ${q} tonnes of material at ${c}% grade. Calculate the tonnes of graded component available for downstream processing.`,answer:ans,distractors:[q*(100-c)/100,c,ans+2],solution:`Available graded component = ${q} x ${c}/100 = ${numberLabel(ans)} tonnes. This is a direct component inventory calculation.`,assessmentStyle:direct}; },
  v => { const vol=100+10*v,c=60,remove=20+v,water=10+v,finalVol=vol-remove+water,ans=c*(vol-remove)/finalVol; return {subtopic:"Unequal drain and refill",prompt:`A tank has ${vol} litres of a ${c}% solution. It loses ${remove} litres of well-mixed liquid and receives only ${water} litres of water. Find the resulting concentration.`,answer:ans,distractors:[c*(1-remove/vol),c*(vol-remove)/(vol+water),ans+3],format:percentLabel,solution:`Active material after draining is ${c}/100 x (${vol}-${remove}). The final volume is ${vol}-${remove}+${water} = ${finalVol}. Divide and multiply by 100 to obtain ${numberLabel(ans)}%.`,assessmentStyle:multi}; },
  v => { const a=20+v,b=50+v,c=80-v,q1=12+v,q2=8+v,q3=10+v,ans=(a*q1+b*q2+c*q3)/(q1+q2+q3); return {subtopic:"Procurement blend caselet",prompt:`A procurement caselet lists three inputs: ${q1} units at ${a}% grade, ${q2} units at ${b}% grade, and ${q3} units at ${c}% grade. What is the weighted grade of the complete order?`,answer:ans,distractors:[(a+b+c)/3,ans+5,ans-5],format:percentLabel,solution:`Compute graded units ${q1} x ${a}/100 + ${q2} x ${b}/100 + ${q3} x ${c}/100. Divide by total units ${q1+q2+q3} and multiply by 100, giving ${numberLabel(ans)}%.`,assessmentStyle:multi}; },
  v => { const vol=100+10*v,c=72-v,first=10+v,second=8+v,afterFirst=c*(1-first/vol),ans=afterFirst*(1-second/vol); return {subtopic:"Unequal successive replacements",prompt:`A tank contains ${vol} litres of a ${c}% solution. First ${first} litres and later ${second} litres are separately removed and replaced with water, mixing fully after each operation. Find the final concentration.`,answer:ans,distractors:[c*(1-(first+second)/vol),afterFirst,ans+3],format:percentLabel,solution:`The first operation retains the factor 1-${first}/${vol}; the second retains 1-${second}/${vol}. Multiply ${c} x (1-${first}/${vol}) x (1-${second}/${vol}) to obtain ${numberLabel(ans)}%.`,assessmentStyle:multi}; },
];

const workPatterns = [
  v => { const d=8+2*v; return {subtopic:"Individual work rate",prompt:`A technician can complete a calibration assignment alone in ${d} days. What fraction of the assignment is completed per day?`,answer:1/d,distractors:[d,1/(d+1),2/d],solution:`Daily work rate is total work 1 divided by ${d} days, so the technician completes 1/${d} of the assignment each day.`,assessmentStyle:direct}; },
  v => { const a=8+2*v,b=12+3*v,ans=a*b/(a+b); return {subtopic:"Combined completion time",prompt:`Analyst A can finish a report in ${a} days and Analyst B in ${b} days. Working together at constant rates, how many days will they take?`,answer:ans,distractors:[(a+b)/2,a+b,Math.min(a,b)],format:daysLabel,solution:`Their combined rate is 1/${a} + 1/${b} = (${a+b})/${a*b}. Invert the rate to get ${numberLabel(ans)} days.`,assessmentStyle:direct}; },
  v => { const a=12+2*v,b=18+3*v,c=a*b/(a+b); return {subtopic:"Unknown individual time",prompt:`Two associates together complete a task in ${numberLabel(c)} days. One associate alone needs ${a} days. How many days would the other associate need alone?`,answer:b,distractors:[a-c,a+c,b+3],format:daysLabel,solution:`Other rate = 1/${numberLabel(c)} - 1/${a}. Taking the reciprocal gives ${b} days; adding this rate back to 1/${a} reproduces the team rate.`,assessmentStyle:reverse}; },
  v => { const ratio=2+v%3,slow=18+3*v,fast=slow/ratio; return {subtopic:"Efficiency-time inversion",prompt:`Employee A is ${ratio} times as efficient as Employee B. If B needs ${slow} days for a task, how many days will A need for the same task?`,answer:fast,distractors:[slow*ratio,slow-ratio,fast+2],format:daysLabel,solution:`Time is inversely proportional to efficiency. Divide B's time ${slow} by ${ratio}; A therefore needs ${numberLabel(fast)} days.`,assessmentStyle:direct}; },
  v => { const total=15+3*v,worked=4+v,ans=worked/total*100; return {subtopic:"Work fraction completed",prompt:`A contractor can finish a project in ${total} days at a constant rate. After working alone for ${worked} days, what percentage of the project is complete?`,answer:ans,distractors:[worked/total,total-worked,ans+5],format:percentLabel,solution:`The contractor completes 1/${total} per day. In ${worked} days the completed fraction is ${worked}/${total}; multiply by 100 to obtain ${numberLabel(ans)}%.`,assessmentStyle:direct}; },
  v => { const a=12+2*v,b=18+3*v,x=3+v,remaining=1-x/a,ans=remaining*b; return {subtopic:"Handover after partial work",prompt:`A can complete an assignment in ${a} days and works alone for ${x} days. B, who can complete it in ${b} days, then finishes the remainder alone. How many days does B work?`,answer:ans,distractors:[b-x,(1-x/b)*a,ans+2],format:daysLabel,solution:`A completes ${x}/${a}, leaving 1-${x}/${a}. B's daily rate is 1/${b}, so B's time = (1-${x}/${a}) x ${b} = ${numberLabel(ans)} days.`,assessmentStyle:multi}; },
  v => { const a=12+2*v,b=18+3*v,delay=2+v,ans=delay+(1-delay/a)/(1/a+1/b); return {subtopic:"Worker joins later",prompt:`A starts a project that would take ${a} days alone. After ${delay} days, B joins; B alone would take ${b} days. Find the total project duration from A's start.`,answer:ans,distractors:[a*b/(a+b),delay+a*b/(a+b),ans+2],format:daysLabel,solution:`A first completes ${delay}/${a}, leaving 1-${delay}/${a}. The joint rate is 1/${a}+1/${b}; divide the remainder by this rate, then add ${delay} days to obtain ${numberLabel(ans)}.`,assessmentStyle:multi}; },
  v => { const a=10+2*v,b=15+3*v,together=3+v,remaining=1-together*(1/a+1/b),ans=together+remaining*a; return {subtopic:"Worker leaves before completion",prompt:`A and B can finish a task alone in ${a} and ${b} days. They work together for ${together} days, after which B leaves. How many days from the start does A take to finish the task?`,answer:ans,distractors:[together+remaining*b,a-together,ans+2],format:daysLabel,solution:`Joint work in ${together} days is ${together}(1/${a}+1/${b}). Subtract from 1, divide the remainder by A's rate 1/${a}, then add ${together}; total = ${numberLabel(ans)} days.`,assessmentStyle:multi}; },
  v => { const a=6+v,b=8+v,total=lcmValue(a,b),ra=total/a,rb=total/b; let rem=total,days=0; while(rem>0){rem-=days%2===0?ra:rb;days++;} return {subtopic:"Alternate-day working",prompt:`A can finish a task in ${a} days and B in ${b} days. They work on alternate days starting with A, each at the stated constant rate. On which day is the task completed?`,answer:days,distractors:[days-1,days+1,a*b/(a+b)],format:daysLabel,solution:`Use ${total} work units. A's rate = ${total}/${a} = ${ra}, and B's rate = ${total}/${b} = ${rb}. Alternately subtract ${ra} and ${rb}; the remaining work reaches zero on day ${days}.`,assessmentStyle:multi}; },
  v => { const men=12+2*v,days=18+v,newMen=men+6,ans=men*days/newMen; return {subtopic:"Workforce scaling",prompt:`A site requires ${men} workers for ${days} days to complete a fixed job. If productivity per worker is unchanged and ${newMen} workers are assigned, how many days are required?`,answer:ans,distractors:[days*newMen/men,days-(newMen-men),ans+2],format:daysLabel,solution:`For fixed work, workers x days is constant. Required days = ${men} x ${days}/${newMen} = ${numberLabel(ans)} days.`,assessmentStyle:direct}; },
  v => { const men=15+v,days=12+v,hours=8,newMen=men+5,newHours=10,ans=men*days*hours/(newMen*newHours); return {subtopic:"Workers-days-hours",prompt:`A project needs ${men} workers for ${days} days at ${hours} hours daily. With ${newMen} equally efficient workers working ${newHours} hours daily, how many days will the same project take?`,answer:ans,distractors:[men*days/newMen,days*hours/newHours,ans+2],format:daysLabel,solution:`Work is proportional to workers x days x hours. Set ${men} x ${days} x ${hours} = ${newMen} x d x ${newHours}; solving gives d = ${numberLabel(ans)} days.`,assessmentStyle:multi}; },
  v => { const men=8+v,women=12+v,equiv=2,ans=men+women/equiv; return {subtopic:"Equivalent workforce",prompt:`Two women together perform the same daily work as one man. A team has ${men} men and ${women} women. Express its daily capacity as an equivalent number of men.`,answer:ans,distractors:[men+women*equiv,men+women,ans+2],solution:`Since two women equal one man, ${women} women equal ${women}/${equiv} men. Add ${men} men to get an equivalent workforce of ${numberLabel(ans)} men.`,assessmentStyle:contextual}; },
  v => { const a=2+v,b=3+v,daysA=8+v,daysB=6+v,total=10000+1000*v,wa=a*daysA,wb=b*daysB,ans=total*wa/(wa+wb); return {subtopic:"Work and wages",prompt:`A and B are paid Rs ${total} for a contract. Their daily efficiencies are in the ratio ${a}:${b}; A works ${daysA} days and B ${daysB} days. What is A's fair share?`,answer:ans,distractors:[total*a/(a+b),total*daysA/(daysA+daysB),ans+500],format:moneyLabel,solution:`Payment follows work contribution. A:B contribution = ${a} x ${daysA} : ${b} x ${daysB} = ${wa}:${wb}. A's share is ${total} x ${wa}/(${wa}+${wb}) = Rs ${numberLabel(ans)}.`,assessmentStyle:multi}; },
  v => { const a=12+v,b=18+v,c=24+v,ans=1/(1/a+1/b+1/c); return {subtopic:"Three-person team rate",prompt:`Three engineers can complete a migration alone in ${a}, ${b}, and ${c} days respectively. If all work together continuously, how many days are required?`,answer:ans,distractors:[(a+b+c)/3,a*b/(a+b),ans+2],format:daysLabel,solution:`Add the three rates: 1/${a}+1/${b}+1/${c}. The reciprocal of this combined rate is ${numberLabel(ans)} days.`,assessmentStyle:contextual}; },
  v => { const a=12+2*v,b=18+3*v,c=24+4*v,pair=1/a+1/b,total=pair+1/c,ans=1/(total-pair); return {subtopic:"Third worker from team data",prompt:`A and B have individual completion times of ${a} and ${b} days. With worker C, the team rate becomes ${numberLabel(total)} of the job per day. How many days would C need alone?`,answer:ans,distractors:[1/total,a+b,ans+3],format:daysLabel,solution:`C's rate = ${numberLabel(total)} - 1/${a} - 1/${b} = ${numberLabel(1/c)}. Invert that rate to obtain ${numberLabel(ans)} days.`,assessmentStyle:reverse}; },
  v => { const a=10+v,b=15+v,x=2+v,y=3+v,done=x/a+y*(1/a+1/b),ans=done*100; return {subtopic:"Overlapping work schedule",prompt:`A can finish a task in ${a} days and B in ${b} days. A works alone for ${x} days, then both work for ${y} more days. What percentage of the task is completed?`,answer:ans,distractors:[(x+y)/a*100,y*(1/a+1/b)*100,ans+5],format:percentLabel,solution:`A's solo contribution is ${x}/${a}. Joint contribution is ${y}(1/${a}+1/${b}). Add the fractions and multiply by 100 to obtain ${numberLabel(ans)}%.`,assessmentStyle:multi}; },
  v => { const machines=6+v,hours=8+v,units=720+60*v,newMachines=machines+3,newHours=hours+2,ans=units*newMachines*newHours/(machines*hours); return {subtopic:"Machine output scaling",prompt:`${machines} identical machines produce ${units} components in ${hours} hours. At the same rate, how many components will ${newMachines} machines produce in ${newHours} hours?`,answer:ans,distractors:[units*newMachines/machines,units*newHours/hours,ans+60],solution:`Output is proportional to machines x hours. New output = ${units} x ${newMachines}/${machines} x ${newHours}/${hours} = ${numberLabel(ans)} components.`,assessmentStyle:contextual}; },
  v => { const days=20+v,increase=20+5*v,ans=days/(1+increase/100); return {subtopic:"Efficiency improvement",prompt:`A process normally takes ${days} hours. After automation, its operating rate improves by ${increase}%. Assuming the same work volume, what is the new completion time?`,answer:ans,distractors:[days*(1-increase/100),days-increase/100,ans+2],format:hoursLabel,solution:`New rate multiplier is 1+${increase}/100. Since time is inversely proportional to rate, new time = ${days}/(1+${increase}/100) = ${numberLabel(ans)} hours.`,assessmentStyle:reverse}; },
  v => { const workers=20+2*v,days=15+v,reduced=workers-5,ans=workers*days/reduced; return {subtopic:"Reduced workforce delay",prompt:`A ${workers}-person team is scheduled to finish a project in ${days} days. If only ${reduced} equally productive people remain from the start, how many days will completion require?`,answer:ans,distractors:[days*reduced/workers,days+5,ans+2],format:daysLabel,solution:`Total person-days remain ${workers} x ${days}. Divide by the reduced team size ${reduced}; completion time becomes ${numberLabel(ans)} days.`,assessmentStyle:reverse}; },
  v => { const workers=18+v,phase=4+v,totalDays=14+v,added=6,work=workers*totalDays,remaining=work-workers*phase,ans=phase+remaining/(workers+added); return {subtopic:"Staff added mid-project",prompt:`${workers} workers can complete a contract in ${totalDays} days. After ${phase} days, ${added} equally efficient workers join. Find the actual total duration from project start.`,answer:ans,distractors:[work/(workers+added),totalDays-phase,ans+2],format:daysLabel,solution:`Total work is ${workers} x ${totalDays} person-days. Initial work is ${workers} x ${phase}; divide the remainder by ${workers+added}, then add ${phase}. Total duration = ${numberLabel(ans)} days.`,assessmentStyle:multi}; },
  v => { const work=2400+200*v,perWorker=20+2*v,days=8+v,ans=work/(perWorker*days); return {subtopic:"Required team size",prompt:`A warehouse must process ${work} packages in ${days} days. Each worker consistently processes ${perWorker} packages per day. What minimum team size is required?`,answer:ans,distractors:[work/perWorker,work/days,ans+2],solution:`One worker processes ${perWorker} x ${days} packages during the deadline. Divide ${work} by that capacity: required workers = ${numberLabel(ans)}.`,assessmentStyle:reverse}; },
  v => { const workers=25+v,absent=5+v%3,days=12+v,ans=workers*days/(workers-absent)-days; return {subtopic:"Absenteeism delay",prompt:`A team of ${workers} workers would finish an assignment in ${days} days. If ${absent} workers are absent throughout and all rates are equal, by how many days is completion delayed?`,answer:ans,distractors:[absent,workers*days/(workers-absent),ans+2],format:daysLabel,solution:`Scheduled work is ${workers} x ${days} person-days. New duration is that total divided by ${workers-absent}; subtract ${days} to obtain a delay of ${numberLabel(ans)} days.`,assessmentStyle:multi}; },
  v => { const a=16+2*v,b=24+3*v,ans=(1/a+1/b)*100; return {subtopic:"One-day team contribution",prompt:`Two reviewers need ${a} and ${b} days individually to check the same document set. What percentage of the set do they check in one day when working together?`,answer:ans,distractors:[100/(a+b),100/a,ans+2],format:percentLabel,solution:`Their one-day fraction is 1/${a}+1/${b}. Multiply this combined rate by 100 to obtain ${numberLabel(ans)}% of the document set.`,assessmentStyle:direct}; },
  v => { const workDays=3,restDays=1,rateDays=12+v,cycles=2+v%2,workDone=cycles*workDays/rateDays,remaining=1-workDone,ans=cycles*(workDays+restDays)+remaining*rateDays; return {subtopic:"Work-rest cycle",prompt:`A specialist working continuously would finish a task in ${rateDays} days. Instead, the specialist works ${workDays} days and rests ${restDays} day repeatedly. After ${cycles} complete work-rest cycles, how many calendar days from the start are needed to finish?`,answer:ans,distractors:[rateDays+cycles,cycles*workDays+remaining*rateDays,ans+1],format:daysLabel,solution:`Each cycle completes ${workDays}/${rateDays}. After ${cycles} cycles, remaining work is 1-${cycles*workDays}/${rateDays}. Add ${cycles*(workDays+restDays)} calendar days and ${numberLabel(remaining*rateDays)} final workdays to get ${numberLabel(ans)}.`,assessmentStyle:multi}; },
  v => { const team=10+v,hours=6+v,days=8+v,rate=5+v,total=team*hours*days*rate; return {subtopic:"Team productivity caselet",prompt:`A project caselet states that ${team} associates work ${hours} hours daily for ${days} days, and each completes ${rate} records per hour. How many records does the team complete?`,answer:total,distractors:[team*days*rate,hours*days*rate,total+100],solution:`Daily team output is ${team} * ${hours} * ${rate}. Multiply by ${days} days: total = ${team} * ${hours} * ${rate} * ${days} = ${total} records.`,assessmentStyle:multi}; },
];

const pipePatterns = [
  v => { const h=6+v; return {subtopic:"Single inlet rate",prompt:`An inlet pipe fills an empty tank in ${h} hours. What fraction of the tank does the pipe fill in one hour?`,answer:1/h,distractors:[h,1/(h+1),2/h],solution:`One complete tank divided by ${h} hours gives an hourly filling rate of 1/${h} tank.`,assessmentStyle:direct}; },
  v => { const a=6+v,b=9+v,ans=a*b/(a+b); return {subtopic:"Two inlet pipes",prompt:`Pipe A fills a cistern in ${a} hours and Pipe B in ${b} hours. If both are opened together, how long will the empty cistern take to fill?`,answer:ans,distractors:[(a+b)/2,a+b,Math.min(a,b)],format:hoursLabel,solution:`Combined filling rate = 1/${a}+1/${b}. Inverting this rate gives ${numberLabel(ans)} hours for one full cistern.`,assessmentStyle:direct}; },
  v => { const fill=8+v,drain=18+2*v,ans=1/(1/fill-1/drain); return {subtopic:"Inlet with outlet",prompt:`An inlet fills a tank in ${fill} hours while a drain empties a full tank in ${drain} hours. With both open, how long does an empty tank take to fill?`,answer:ans,distractors:[fill*drain/(fill+drain),fill+drain,ans+2],format:hoursLabel,solution:`Net rate is 1/${fill}-1/${drain}, because the drain opposes filling. Invert the positive net rate to obtain ${numberLabel(ans)} hours.`,assessmentStyle:direct}; },
  v => { const fill=10+v,leak=20+2*v,net=1/(1/fill-1/leak); return {subtopic:"Unknown leak time",prompt:`A pipe alone fills a tank in ${fill} hours, but with a leak open the tank fills in ${numberLabel(net)} hours. In how many hours would the leak empty a full tank?`,answer:leak,distractors:[net-fill,fill+net,leak+4],format:hoursLabel,solution:`Leak rate = inlet rate - net rate = 1/${fill}-1/${numberLabel(net)}. The reciprocal of this difference is ${leak} hours.`,assessmentStyle:reverse}; },
  v => { const a=8+v,b=12+v,delay=2+v%2,ans=delay+(1-delay/a)/(1/a+1/b); return {subtopic:"Second inlet opened later",prompt:`Pipe A can fill a tank in ${a} hours and starts alone. After ${delay} hours, Pipe B, which fills it in ${b} hours, is opened. Find total filling time from the start.`,answer:ans,distractors:[a*b/(a+b),delay+a*b/(a+b),ans+2],format:hoursLabel,solution:`A first fills ${delay}/${a}, leaving 1-${delay}/${a}. Divide the remainder by 1/${a}+1/${b}, then add ${delay}; total time is ${numberLabel(ans)} hours.`,assessmentStyle:multi}; },
  v => { const a=6+v,b=10+v,together=2+v%2,remaining=1-together*(1/a+1/b),ans=together+remaining/a; return {subtopic:"One inlet closed early",prompt:`Two pipes fill a tank individually in ${a} and ${b} hours. Both run for ${together} hours, then the slower pipe is closed. How long from the start until the tank is full?`,answer:ans,distractors:[together+remaining*b,a-together,ans+2],format:hoursLabel,solution:`Joint filling is ${together}(1/${a}+1/${b}). Subtract from 1, divide the remainder by 1/${a}, and add ${together}; total = ${numberLabel(ans)} hours.`,assessmentStyle:multi}; },
  v => { const a=7+v,b=11+v,total=lcmValue(a,b),ra=total/a,rb=total/b; let rem=total,h=0; while(rem>0){rem-=h%2===0?ra:rb;h++;} return {subtopic:"Alternate inlet operation",prompt:`Two inlet pipes can fill a tank in ${a} and ${b} hours. They are opened for alternate one-hour periods, beginning with the faster pipe. During which hour is the tank filled?`,answer:h,distractors:[h-1,h+1,a*b/(a+b)],format:hoursLabel,solution:`Represent the tank by ${total} units. Faster-pipe rate = ${total}/${a} = ${ra}; slower-pipe rate = ${total}/${b} = ${rb}. Alternately subtract these amounts until zero is reached during hour ${h}.`,assessmentStyle:multi}; },
  v => { const h=8+v,elapsed=3+v%3,ans=elapsed/h*100; return {subtopic:"Tank fraction filled",prompt:`A pipe fills an empty tank uniformly in ${h} hours. After operating for ${elapsed} hours without leakage, what percentage of the tank is filled?`,answer:ans,distractors:[elapsed/h,h-elapsed,ans+5],format:percentLabel,solution:`Filled fraction is operating time divided by full time = ${elapsed}/${h}. Multiply by 100 to obtain ${numberLabel(ans)}%.`,assessmentStyle:direct}; },
  v => { const capacity=1200+200*v,rate=150+20*v,ans=capacity/rate; return {subtopic:"Volumetric filling rate",prompt:`A storage tank has capacity ${capacity} litres. A pump supplies ${rate} litres per hour at a constant rate. How many hours are required to fill the empty tank?`,answer:ans,distractors:[capacity-rate,rate/capacity,ans+2],format:hoursLabel,solution:`Time equals volume divided by volumetric rate: ${capacity}/${rate} = ${numberLabel(ans)} hours.`,assessmentStyle:direct}; },
  v => { const a=8+v,drain=20+2*v,openAfter=2+v%2,ans=openAfter+(1-openAfter/a)/(1/a-1/drain); return {subtopic:"Drain opened after delay",prompt:`An inlet fills a tank in ${a} hours. After it runs alone for ${openAfter} hours, a drain that empties the full tank in ${drain} hours is opened. Find total filling time.`,answer:ans,distractors:[1/(1/a-1/drain),openAfter+a,ans+2],format:hoursLabel,solution:`Initial fill is ${openAfter}/${a}. Remaining fraction is 1-${openAfter}/${a}. Net later rate is 1/${a}-1/${drain}; divide the remainder by this rate and add ${openAfter}, giving ${numberLabel(ans)} hours.`,assessmentStyle:multi}; },
  v => { const a=6+v,b=10+v,c=24+2*v,ans=1/(1/a+1/b-1/c); return {subtopic:"Two inlets and outlet",prompt:`Two inlets fill a tank in ${a} and ${b} hours, while an outlet empties it in ${c} hours. If all three are open from empty, how long will filling take?`,answer:ans,distractors:[1/(1/a+1/b+1/c),a*b/(a+b),ans+2],format:hoursLabel,solution:`Net rate = 1/${a}+1/${b}-1/${c}. The reciprocal of this net positive rate is ${numberLabel(ans)} hours.`,assessmentStyle:contextual}; },
  v => { const a=8+v,fraction=(2+v%3)/5,ans=a*fraction; return {subtopic:"Time to target level",prompt:`A constant-rate inlet fills a tank in ${a} hours. Starting empty, how many hours are needed to reach ${numberLabel(fraction*100)}% of capacity?`,answer:ans,distractors:[a/fraction,a*(1-fraction),ans+1],format:hoursLabel,solution:`At constant rate, time is proportional to filled fraction. Required time = ${a} x ${numberLabel(fraction)} = ${numberLabel(ans)} hours.`,assessmentStyle:contextual}; },
  v => { const normal=8+v,actual=12+v,ans=1/(1/normal-1/actual); return {subtopic:"Leak detected from delay",prompt:`A pump should fill a tank in ${normal} hours, but an unnoticed leak makes the actual time ${actual} hours. In how many hours could the leak empty a full tank by itself?`,answer:ans,distractors:[actual-normal,normal+actual,ans+3],format:hoursLabel,solution:`Leak rate equals expected inlet rate minus observed net rate: 1/${normal}-1/${actual}. Invert the difference to get ${numberLabel(ans)} hours.`,assessmentStyle:reverse}; },
  v => { const ratio=2+v%3,slow=15+3*v,fast=slow/ratio; return {subtopic:"Pipe efficiency ratio",prompt:`Pipe A delivers water at ${ratio} times Pipe B's rate. If B fills the tank in ${slow} hours, how many hours would A require alone?`,answer:fast,distractors:[slow*ratio,slow-ratio,fast+2],format:hoursLabel,solution:`Filling time is inversely proportional to delivery rate. Divide ${slow} by ${ratio}; A requires ${numberLabel(fast)} hours.`,assessmentStyle:contextual}; },
  v => { const a=8+v,b=12+v,c=20+v,phase1=2,phase2=2,filled=phase1/a+phase2*(1/a+1/b-1/c),ans=filled*100; return {subtopic:"Scheduled valve sequence",prompt:`Pipe A fills in ${a} hours, B in ${b} hours, and outlet C empties in ${c} hours. A runs alone for ${phase1} hours, then all three run for ${phase2} hours. What percentage is filled?`,answer:ans,distractors:[phase1/a*100,phase2*(1/a+1/b-1/c)*100,ans+5],format:percentLabel,solution:`First phase contributes ${phase1}/${a}. Second phase contributes ${phase2}(1/${a}+1/${b}-1/${c}). Add both fractions and multiply by 100 to obtain ${numberLabel(ans)}%.`,assessmentStyle:multi}; },
  v => { const fill=10+v,stop=2+v%2,run=fill,ans=run+stop; return {subtopic:"Maintenance interruption",prompt:`A pump needs ${fill} operating hours to fill a tank. During the process it is stopped for scheduled maintenance lasting ${stop} hours. What is total elapsed time from start to full tank?`,answer:ans,distractors:[fill-stop,fill*stop,ans+2],format:hoursLabel,solution:`The pump still needs ${run} active operating hours. Add the ${stop}-hour interruption: elapsed time = ${run}+${stop} = ${ans} hours.`,assessmentStyle:contextual}; },
  v => { const fill=6+v,drain=14+v,on=2,off=1,netCycle=on/fill-off/drain,cycles=2+v%2,ans=(netCycle*cycles)*100; return {subtopic:"Cyclic inlet-outlet operation",prompt:`An inlet fills a tank in ${fill} hours and an outlet empties it in ${drain} hours. For each cycle, the inlet runs ${on} hours and then only the outlet runs ${off} hour. After ${cycles} complete cycles, what percentage is filled?`,answer:ans,distractors:[cycles*on/fill*100,cycles*(on/fill+off/drain)*100,ans+5],format:percentLabel,solution:`Net fraction per cycle is ${on}/${fill}-${off}/${drain}. Multiply by ${cycles} cycles and then by 100 to obtain ${numberLabel(ans)}%.`,assessmentStyle:multi}; },
  v => { const a=8+v,b=12+v,ans=a*b/(a+b); return {subtopic:"Equivalent single pipe",prompt:`Two identical-operation inlets fill a tank separately in ${a} and ${b} hours. What single-pipe filling time would have the same rate as both operating together?`,answer:ans,distractors:[a+b,(a+b)/2,Math.min(a,b)],format:hoursLabel,solution:`Equivalent rate is 1/${a}+1/${b}. Its reciprocal ${a*b}/(${a}+${b}) equals ${numberLabel(ans)} hours.`,assessmentStyle:reverse}; },
  v => { const fraction=(2+v%3)/5,fill=8+v,drain=20+v,ans=(1-fraction)/(1/fill-1/drain); return {subtopic:"Partially filled tank",prompt:`A tank is already ${numberLabel(fraction*100)}% full. An inlet fills the whole tank in ${fill} hours while a drain empties it in ${drain} hours. With both open, how long to fill the remainder?`,answer:ans,distractors:[1/(1/fill-1/drain),fraction/(1/fill-1/drain),ans+2],format:hoursLabel,solution:`Remaining fraction is 1-${numberLabel(fraction)}. Net rate is 1/${fill}-1/${drain}. Divide the remaining fraction by the net rate to obtain ${numberLabel(ans)} hours.`,assessmentStyle:multi}; },
  v => { const capacity=2000+200*v,inlet=300+20*v,outlet=80+10*v,ans=capacity/(inlet-outlet); return {subtopic:"Net litres per minute",prompt:`A reservoir of ${capacity} litres receives ${inlet} litres per minute while ${outlet} litres per minute is simultaneously discharged. Starting empty, how many minutes until full?`,answer:ans,distractors:[capacity/inlet,capacity/outlet,ans+2],solution:`Net inflow = ${inlet}-${outlet} = ${inlet-outlet} litres per minute. Time = ${capacity}/${inlet-outlet} = ${numberLabel(ans)} minutes.`,assessmentStyle:contextual}; },
  v => { const a=6+v,b=9+v,target=0.75,ans=target/(1/a+1/b); return {subtopic:"Multiple inlets to partial capacity",prompt:`Two pipes fill a tank in ${a} and ${b} hours. If both start together, how many hours are needed to fill exactly 75% of the tank?`,answer:ans,distractors:[1/(1/a+1/b),target*a*b,ans+1],format:hoursLabel,solution:`Combined rate is 1/${a}+1/${b}. Time for ${target} tank = ${target}/(1/${a}+1/${b}) = ${numberLabel(ans)} hours.`,assessmentStyle:contextual}; },
  v => { const a=8+v,b=14+v,first=2+v%2,filled=first/a,ans=first+(1-filled)/(1/a+1/b); return {subtopic:"Staggered pump schedule",prompt:`Pump A fills a tank in ${a} hours and runs alone for ${first} hours. Pump B, which fills it in ${b} hours, then joins until completion. Find the full elapsed time.`,answer:ans,distractors:[a*b/(a+b),first+a*b/(a+b),ans+2],format:hoursLabel,solution:`A supplies ${first}/${a}, leaving 1-${first}/${a}. Divide the remainder by 1/${a}+1/${b}, then add ${first}. Elapsed time is ${numberLabel(ans)} hours.`,assessmentStyle:multi}; },
  v => { const source=1500+100*v,target=1200+100*v,rate=100+10*v,ans=(source-target)/rate; return {subtopic:"Controlled tank transfer",prompt:`A source tank contains ${source} litres. Liquid is transferred out at ${rate} litres per minute with no inflow. How many minutes until only ${target} litres remain?`,answer:ans,distractors:[source/rate,target/rate,ans+2],solution:`Volume removed must be ${source}-${target} = ${source-target} litres. Divide by ${rate} litres per minute to get ${numberLabel(ans)} minutes.`,assessmentStyle:reverse}; },
  v => { const fill=7+v,leak=18+v,start=3,filled=start/fill,ans=start+(1-filled)/(1/fill-1/leak); return {subtopic:"Leak begins mid-fill",prompt:`A pipe fills a tank in ${fill} hours. After ${start} hours, a leak that empties a full tank in ${leak} hours begins and remains open. Find total filling time.`,answer:ans,distractors:[1/(1/fill-1/leak),start+fill,ans+2],format:hoursLabel,solution:`Before leakage, ${start}/${fill} is filled. Remaining fraction is 1-${start}/${fill}; later net rate is 1/${fill}-1/${leak}. Divide, then add ${start}, obtaining ${numberLabel(ans)} hours.`,assessmentStyle:multi}; },
  v => { const capacity=1000+100*v,a=140+10*v,b=100+10*v,out=40+5*v,minutes=4+v,ans=Math.min(100,(a+b-out)*minutes/capacity*100); return {subtopic:"Reservoir operations caselet",prompt:`A reservoir caselet gives capacity ${capacity} litres, two inflows of ${a} and ${b} litres per minute, and one discharge of ${out} litres per minute. From empty, what percentage is filled after ${minutes} minutes?`,answer:ans,distractors:[(a+b)*minutes/capacity*100,(a-out)*minutes/capacity*100,ans+5],format:percentLabel,solution:`Net inflow is ${a}+${b}-${out} = ${a+b-out} litres per minute. Multiply by ${minutes}, divide by ${capacity}, and multiply by 100 to get ${numberLabel(ans)}%.`,assessmentStyle:multi}; },
];

export const mixturePlacementBank = () => buildPlacementBank(mixturePatterns);
export const timeWorkPlacementBank = () => buildPlacementBank(workPatterns);
export const pipesPlacementBank = () => buildPlacementBank(pipePatterns);
