import React from "react";
import { supportsQuestionVisual } from "./VisualCoverage";

const palette = ["#4f46e5", "#0891b2", "#f59e0b", "#10b981", "#ec4899", "#7c3aed"];
const numbers = text => [...String(text).matchAll(/-?\d+(?:\.\d+)?/g)].map(match => Number(match[0])).filter(Number.isFinite);
const unique = values => [...new Set(values)];
const words = text => unique([...String(text).matchAll(/\b[A-Z][a-z]{2,}\b/g)].map(match => match[0])).filter(word => !["Statements", "Conclusions", "Select", "Which", "How", "What", "Find", "Campus", "Panel", "Meeting", "Sprint", "Assessment", "Six", "Five", "Round", "Gate", "Role", "Plan", "Product", "Team", "Service", "Desk", "Interview", "Queue", "Coding", "Contest", "Orientation", "Day", "Map", "Codebook", "Family", "Concept", "Reasoning", "Verification", "Final"].includes(word));

function Frame({ title, caption, children }) {
  return <figure style={{ margin:"16px 0 20px", border:"1px solid #dbe4f0", borderRadius:14, background:"linear-gradient(180deg,#ffffff,#f8fafc)", padding:"12px 12px 9px", overflow:"hidden" }}>
    <div style={{ display:"flex", justifyContent:"space-between", gap:12, alignItems:"center", marginBottom:8 }}><strong style={{ fontSize:12, color:"#334155", letterSpacing:.3 }}>{title}</strong><span style={{ fontSize:10, color:"#64748b", fontWeight:800 }}>VISUAL AID</span></div>
    <div role="img" aria-label={caption} style={{ width:"100%", overflowX:"auto" }}>{children}</div>
    <figcaption style={{ color:"#64748b", fontSize:11, lineHeight:1.45, marginTop:7 }}>{caption}</figcaption>
  </figure>;
}

const Svg = ({ children, height=220, viewBox="0 0 720 220" }) => <svg viewBox={viewBox} style={{ width:"100%", minWidth:300, height:"auto", maxHeight:height }} aria-hidden="true">{children}</svg>;

function DataChart({ item }) {
  const assigned=[...item.q.matchAll(/=\s*(?:Rs\s*)?(\d+(?:\.\d+)?)/gi)].map(match=>Number(match[1])), values = (assigned.length>=2?assigned:numbers(item.q)).filter(value => value >= 0).slice(0, 6);
  const chartValues = values.length > 1 ? values : [20, 35, 28, 46];
  const max = Math.max(...chartValues, 1);
  const isLine = /line|growth|trend|index|cagr/i.test(item.subtopic);
  const isPie = /pie|budget residual/i.test(item.q+item.subtopic);
  const isTable = /table|headcount|inventory|frequency|two-row|two-table/i.test(item.q+item.subtopic);
  const points = chartValues.map((value, index) => `${80 + index * (540 / Math.max(1, chartValues.length - 1))},${178 - value / max * 128}`).join(" ");
  if(isPie){
    const pieValues=/budget/i.test(item.subtopic)?numbers(item.q).filter(value=>value>0&&value<=100).slice(0,4):chartValues.slice(0,4), segments=pieValues.map((value,index,array)=>({value,index,offset:-array.slice(0,index).reduce((sum,current)=>sum+current,0)*3.77}));
    return <Frame title="Pie-chart stimulus" caption="The coloured sectors show only the listed shares; the unlabelled grey sector is the unknown remainder."><Svg>
      <circle cx="260" cy="112" r="65" fill="none" stroke="#cbd5e1" strokeWidth="54"/>
      {segments.map(({value,index,offset})=><circle key={index} cx="260" cy="112" r="65" fill="none" stroke={palette[index]} strokeWidth="54" strokeDasharray={`${Math.min(100,value)*3.77} 377`} strokeDashoffset={offset} transform="rotate(-90 260 112)"/>)}
      <circle cx="260" cy="112" r="31" fill="#fff"/><text x="260" y="117" textAnchor="middle" fontSize="14" fontWeight="800" fill="#475569">100%</text>
      {pieValues.map((value,index)=><g key={index}><rect x="410" y={55+index*32} width="18" height="18" rx="4" fill={palette[index]}/><text x="440" y={69+index*32} fontSize="14" fill="#334155">Category {String.fromCharCode(65+index)} · {value}%</text></g>)}
      <rect x="410" y={55+pieValues.length*32} width="18" height="18" rx="4" fill="#cbd5e1"/><text x="440" y={69+pieValues.length*32} fontSize="14" fill="#334155">Other · ?</text>
    </Svg></Frame>;
  }
  if(isTable)return <Frame title="Data table" caption={`Table generated from the figures stated in the question: ${chartValues.join(", ")}.`}><Svg>{chartValues.map((value,index)=>{const cols=Math.min(3,chartValues.length),x=95+(index%cols)*175,y=45+Math.floor(index/cols)*75;return <g key={index}><rect x={x} y={y} width="160" height="60" rx="8" fill={`${palette[index%palette.length]}18`} stroke={palette[index%palette.length]} strokeWidth="3"/><text x={x+80} y={y+23} textAnchor="middle" fontSize="11" fill="#64748b">Value {index+1}</text><text x={x+80} y={y+46} textAnchor="middle" fontSize="18" fontWeight="900" fill="#334155">{value}</text></g>})}</Svg></Frame>;
  if(/recruitment funnel/i.test(item.subtopic))return <Frame title="Recruitment funnel" caption="Apply every conversion rate to the survivors from the immediately preceding stage."><Svg>{chartValues.slice(0,4).map((value,index)=>{const width=520-index*95,x=360-width/2,y=32+index*44;return <g key={index}><path d={`M${x} ${y} H${x+width} L${x+width-28} ${y+36} H${x+28} Z`} fill={palette[index]} opacity={.2+index*.15} stroke={palette[index]} strokeWidth="2"/><text x="360" y={y+23} textAnchor="middle" fontSize="13" fontWeight="800" fill="#334155">Stage {index+1}: {value}{index?"%":" applicants"}</text></g>})}</Svg></Frame>;
  if(/stacked/i.test(item.subtopic))return <Frame title="Stacked comparison" caption="Each column total is the sum of its coloured category segments."><Svg>{[[chartValues[0],chartValues[1]],[chartValues[2],chartValues[3]]].map((pair,index)=>{const total=pair.reduce((a,b)=>a+(b||0),0),scale=120/Math.max(...chartValues.slice(0,4),1),x=235+index*230;return <g key={index}><rect x={x} y={180-(pair[0]||0)*scale} width="105" height={(pair[0]||0)*scale} fill={palette[0]}/><rect x={x} y={180-total*scale} width="105" height={(pair[1]||0)*scale} fill={palette[1]}/><text x={x+52} y="203" textAnchor="middle" fontSize="13">Year {index+1}</text><text x={x+52} y={174-total*scale} textAnchor="middle" fontSize="13" fontWeight="800">{total}</text></g>})}<line x1="120" y1="180" x2="610" y2="180" stroke="#94a3b8" strokeWidth="2"/></Svg></Frame>;
  return <Frame title="Data representation" caption={`Chart generated from the figures stated in the question: ${chartValues.join(", ")}.`}><Svg>
    {[0,1,2,3].map(i=><line key={i} x1="60" y1={50+i*42} x2="660" y2={50+i*42} stroke="#e2e8f0" />)}
    {isLine ? <><polyline points={points} fill="none" stroke="#4f46e5" strokeWidth="5" strokeLinejoin="round" />{chartValues.map((value,index)=><g key={index}><circle cx={80+index*(540/Math.max(1,chartValues.length-1))} cy={178-value/max*128} r="7" fill={palette[index%palette.length]} /><text x={80+index*(540/Math.max(1,chartValues.length-1))} y={198} textAnchor="middle" fontSize="13" fill="#475569">{value}</text></g>)}</> : chartValues.map((value,index)=>{const width=500/chartValues.length,x=90+index*(width+12),h=value/max*128;return <g key={index}><rect x={x} y={178-h} width={width} height={h} rx="7" fill={palette[index%palette.length]} opacity=".88"/><text x={x+width/2} y={170-h} textAnchor="middle" fontSize="13" fontWeight="700" fill="#334155">{value}</text><text x={x+width/2} y="199" textAnchor="middle" fontSize="12" fill="#64748b">V{index+1}</text></g>})}
    <line x1="60" y1="178" x2="670" y2="178" stroke="#94a3b8" strokeWidth="2" />
  </Svg></Frame>;
}

function Geometry({ item }) {
  const s=item.subtopic.toLowerCase();
  const raw=numbers(item.q).filter(n=>n>0).slice(0,4), vals=/path around/.test(s)&&raw.length>=3?[raw[1],raw[2],raw[0]]:raw, label=i=>vals[i]??"?";
  let figure;
  if(/semicircle/.test(s)) figure=<><path d="M245 155 A105 105 0 0 1 455 155 Z" fill="#eef2ff" stroke="#4f46e5" strokeWidth="4"/><line x1="350" y1="155" x2="455" y2="155" stroke="#ef4444" strokeWidth="3"/><text x="397" y="146" fontSize="15" fill="#b91c1c">r={label(0)}</text></>;
  else if(/circle|sector|arc/.test(s)) figure=<><circle cx="350" cy="112" r="78" fill="#eef2ff" stroke="#4f46e5" strokeWidth="4"/><line x1="350" y1="112" x2="428" y2="112" stroke="#ef4444" strokeWidth="4"/><text x="386" y="103" fontSize="15" fill="#b91c1c">r={label(0)}</text>{/sector|arc/.test(s)&&<path d="M350 112 L428 112 A78 78 0 0 0 389 44 Z" fill="#fef3c7" stroke="#f59e0b" strokeWidth="3"/>}</>;
  else if(/heron/.test(s)) figure=<><path d="M350 35 L205 185 L495 185 Z" fill="#ecfeff" stroke="#0891b2" strokeWidth="4"/><text x="270" y="105" fontSize="15" fill="#334155">{label(0)}</text><text x="430" y="105" fontSize="15" fill="#334155">{label(1)}</text><text x="350" y="207" textAnchor="middle" fontSize="15" fill="#334155">{label(2)}</text></>;
  else if(/equilateral/.test(s)) figure=<><path d="M350 35 L205 185 L495 185 Z" fill="#ecfeff" stroke="#0891b2" strokeWidth="4"/><text x="350" y="207" textAnchor="middle" fontSize="15" fill="#334155">each side={label(0)}</text></>;
  else if(/cone/.test(s)) figure=<><ellipse cx="350" cy="175" rx="105" ry="27" fill="#cffafe" stroke="#0891b2" strokeWidth="4"/><path d="M245 175 L350 30 L455 175" fill="#ecfeff" fillOpacity=".7" stroke="#0891b2" strokeWidth="4"/><line x1="350" y1="30" x2="350" y2="175" stroke="#ef4444" strokeDasharray="7 6" strokeWidth="3"/><text x="360" y="110" fontSize="15" fill="#b91c1c">h={label(1)}</text><text x="390" y="168" fontSize="15" fill="#334155">r={label(0)}</text></>;
  else if(/triangle/.test(s)) figure=<><path d="M350 35 L205 185 L495 185 Z" fill="#ecfeff" stroke="#0891b2" strokeWidth="4"/><line x1="350" y1="35" x2="350" y2="185" stroke="#ef4444" strokeDasharray="7 6" strokeWidth="3"/><text x="355" y="112" fontSize="15" fill="#b91c1c">h={label(1)}</text><text x="350" y="207" textAnchor="middle" fontSize="15" fill="#334155">base={label(0)}</text></>;
  else if(/cylinder/.test(s)) figure=<><ellipse cx="350" cy="50" rx="92" ry="27" fill="#dbeafe" stroke="#2563eb" strokeWidth="4"/><path d="M258 50 V172 M442 50 V172" stroke="#2563eb" strokeWidth="4"/><ellipse cx="350" cy="172" rx="92" ry="27" fill="#bfdbfe" stroke="#2563eb" strokeWidth="4"/><text x="451" y="115" fontSize="15" fill="#334155">h={label(1)}</text><text x="350" y="45" textAnchor="middle" fontSize="15" fill="#334155">r={label(0)}</text></>;
  else if(/melting/.test(s)) figure=<>{[0,1,2].map(i=><circle key={i} cx={175+i*70} cy="112" r="28" fill="#ede9fe" stroke="#7c3aed" strokeWidth="3"/>)}<text x="280" y="190" textAnchor="middle" fontSize="14" fill="#334155">small r={label(0)}</text><path d="M390 112 H470" stroke="#64748b" strokeWidth="4" markerEnd="url(#meltArrow)"/><circle cx="565" cy="112" r="70" fill="#dbeafe" stroke="#2563eb" strokeWidth="4"/><text x="565" y="117" textAnchor="middle" fontSize="14" fontWeight="800">large r={label(1)}</text><defs><marker id="meltArrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#64748b"/></marker></defs></>;
  else if(/sphere/.test(s)) figure=<><circle cx="350" cy="112" r="82" fill="#ede9fe" stroke="#7c3aed" strokeWidth="4"/><ellipse cx="350" cy="112" rx="82" ry="25" fill="none" stroke="#a78bfa" strokeDasharray="7 5" strokeWidth="3"/><line x1="350" y1="112" x2="432" y2="112" stroke="#ef4444" strokeWidth="3"/><text x="384" y="103" fontSize="15" fill="#b91c1c">r={label(0)}</text></>;
  else if(/rhombus/.test(s)) figure=<><path d="M350 35 L505 112 L350 189 L195 112 Z" fill="#f0fdf4" stroke="#059669" strokeWidth="4"/><line x1="195" y1="112" x2="505" y2="112" stroke="#ef4444" strokeDasharray="7 5" strokeWidth="3"/><line x1="350" y1="35" x2="350" y2="189" stroke="#f59e0b" strokeDasharray="7 5" strokeWidth="3"/><text x="350" y="104" textAnchor="middle" fontSize="14" fill="#b91c1c">d₁={label(0)}</text><text x="358" y="72" fontSize="14" fill="#92400e">d₂={label(1)}</text></>;
  else if(/trapezium/.test(s)) figure=<><path d="M250 45 L450 45 L525 185 L175 185 Z" fill="#ecfeff" stroke="#0891b2" strokeWidth="4"/><line x1="350" y1="45" x2="350" y2="185" stroke="#ef4444" strokeDasharray="7 5" strokeWidth="3"/><text x="350" y="35" textAnchor="middle" fontSize="14" fill="#334155">a={label(0)}</text><text x="350" y="207" textAnchor="middle" fontSize="14" fill="#334155">b={label(1)}</text><text x="360" y="120" fontSize="14" fill="#b91c1c">h={label(2)}</text></>;
  else if(/square/.test(s)) figure=<><rect x="265" y="30" width="170" height="170" fill="#f0fdf4" stroke="#059669" strokeWidth="4"/><line x1="265" y1="200" x2="435" y2="30" stroke="#ef4444" strokeDasharray="7 5" strokeWidth="3"/><text x="350" y="218" textAnchor="middle" fontSize="14" fill="#334155">side={label(0)}</text></>;
  else if(/tank/.test(s)) figure=<><path d="M245 75 L390 40 L485 92 L340 128 Z M245 75 V170 L340 207 V128 M340 207 L485 170 V92" fill="#e0f2fe" stroke="#0369a1" strokeWidth="4" strokeLinejoin="round"/><text x="350" y="218" textAnchor="middle" fontSize="14" fill="#334155">L={label(0)} · W={label(1)}</text><text x="350" y="158" textAnchor="middle" fontSize="14" fontWeight="800" fill="#0f4c75">liquid volume={label(2)} cubic units</text></>;
  else if(/cube|cuboid/.test(s)) figure=<><path d="M245 75 L390 40 L485 92 L340 128 Z M245 75 V170 L340 207 V128 M340 207 L485 170 V92" fill="#e0f2fe" stroke="#0369a1" strokeWidth="4" strokeLinejoin="round"/><text x="360" y="218" fontSize="14" fill="#334155">{vals.join(" × ")}</text></>;
  else figure=<><rect x="205" y="50" width="290" height="135" rx="3" fill="#ecfdf5" stroke="#059669" strokeWidth="4"/><text x="350" y="207" textAnchor="middle" fontSize="15" fill="#334155">length={label(0)}</text><text x="505" y="120" fontSize="15" fill="#334155">width={label(1)}</text>{/path/.test(s)&&<rect x="185" y="30" width="330" height="175" fill="none" stroke="#f59e0b" strokeWidth="14" opacity=".7"/>}</>;
  return <Frame title="Dimension diagram" caption="Not to scale. All displayed dimensions come from the question statement."><Svg>{figure}</Svg></Frame>;
}

function ProbabilityVisual({ item }) {
  const text=(item.q+" "+item.subtopic).toLowerCase(), vals=numbers(item.q).filter(value=>value>=0);
  if(/two-dice|two dice/.test(text)){const target=vals.find(value=>value>=2&&value<=12);return <Frame title="Two-dice sample space" caption="Rows represent Die 1 and columns Die 2; highlighted cells match the requested total where applicable."><Svg>{Array.from({length:36},(_,i)=>{const a=Math.floor(i/6)+1,b=i%6+1,x=170+(i%6)*55,y=35+Math.floor(i/6)*29,active=target&&a+b===target;return <g key={i}><rect x={x} y={y} width="51" height="25" rx="4" fill={active?"#fef3c7":"#f8fafc"} stroke={active?"#f59e0b":"#cbd5e1"}/><text x={x+25} y={y+17} textAnchor="middle" fontSize="10" fill="#334155">{a}+{b}</text></g>})}</Svg></Frame>}
  if(/die|dice/.test(text))return <Frame title="Die outcome space" caption="A fair die has six equally likely faces; retain only faces satisfying the question condition."><Svg>{Array.from({length:6},(_,i)=><g key={i}><rect x={70+i*105} y="65" width="82" height="82" rx="13" fill={`${palette[i]}18`} stroke={palette[i]} strokeWidth="3"/><text x={111+i*105} y="116" textAnchor="middle" fontSize="26" fontWeight="900" fill="#334155">{i+1}</text></g>)}</Svg></Frame>;
  if(/card|face card/.test(text)){const suits=["♠","♥","♦","♣"];return <Frame title="Card-space model" caption="Separate rank and suit conditions before counting favourable cards from the 52-card deck."><Svg>{suits.map((suit,i)=><g key={suit}><rect x={130+i*125} y="40" width="88" height="135" rx="10" fill="#fff" stroke={i===1||i===2?"#ef4444":"#334155"} strokeWidth="3"/><text x={174+i*125} y="95" textAnchor="middle" fontSize="34" fill={i===1||i===2?"#ef4444":"#334155"}>{suit}</text><text x={174+i*125} y="144" textAnchor="middle" fontSize="15" fontWeight="800">13 cards</text></g>)}</Svg></Frame>}
  if(/bag|ball|defective|sampling|draw/.test(text))return <Frame title="Urn / sample model" caption={`Counts shown in the prompt (${vals.slice(0,4).join(", ")}) define the population before each draw.`}><Svg><path d="M235 42 H485 L455 190 H265 Z" fill="#f8fafc" stroke="#475569" strokeWidth="4"/>{Array.from({length:12},(_,i)=><circle key={i} cx={290+(i%4)*47} cy={82+Math.floor(i/4)*42} r="15" fill={palette[i%3]} opacity=".8"/>)}<text x="360" y="213" textAnchor="middle" fontSize="13" fill="#334155">without replacement: denominator changes · with replacement: resets</text></Svg></Frame>;
  if(/spinner/.test(text))return <Frame title="Spinner model" caption="The sector count and marked outcomes determine the favourable fraction."><Svg><circle cx="360" cy="110" r="88" fill="#fff" stroke="#7c3aed" strokeWidth="4"/>{Array.from({length:8},(_,i)=>{const a=i*Math.PI/4;return <line key={i} x1="360" y1="110" x2={360+88*Math.cos(a)} y2={110+88*Math.sin(a)} stroke={palette[i%palette.length]} strokeWidth="3"/>})}<path d="M360 110 L420 54" stroke="#ef4444" strokeWidth="7" strokeLinecap="round"/><circle cx="360" cy="110" r="8" fill="#334155"/></Svg></Frame>;
  if(/calendar-day/.test(text))return <Frame title="Day selection space" caption="Treat each listed day as one selectable outcome and count the days satisfying the condition."><Svg>{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((day,i)=><g key={day}><rect x={48+i*91} y="70" width="78" height="82" rx="10" fill={`${palette[i%palette.length]}18`} stroke={palette[i%palette.length]} strokeWidth="3"/><text x={87+i*91} y="118" textAnchor="middle" fontSize="14" fontWeight="800">{day}</text></g>)}</Svg></Frame>;
  if(/committee|arrangement/.test(text))return <Frame title="Selection model" caption="Distinguish choosing members from arranging selected members into roles or positions."><Svg>{Array.from({length:7},(_,i)=><g key={i}><circle cx={90+i*90} cy="85" r="26" fill={`${palette[i%palette.length]}25`} stroke={palette[i%palette.length]} strokeWidth="3"/><path d={`M${60+i*90} 165 Q${90+i*90} 105 ${120+i*90} 165`} fill={`${palette[i%palette.length]}25`} stroke={palette[i%palette.length]} strokeWidth="3"/></g>)}</Svg></Frame>;
  if(/coin|success|complement|conditional|independent|bayes|mutually|union|risk|expected/.test(text))return <Frame title="Event tree" caption="Follow branches in sequence: multiply along a path and add mutually exclusive completed paths."><Svg><circle cx="105" cy="112" r="13" fill="#334155"/><path d="M118 112 L270 60 M118 112 L270 164 M285 60 L440 35 M285 60 L440 87 M285 164 L440 139 M285 164 L440 191" fill="none" stroke="#7c3aed" strokeWidth="4"/>{[[280,60,"Success"],[280,164,"Other"],[470,35,"S"],[470,87,"F"],[470,139,"S"],[470,191,"F"]].map(([x,y,label],i)=><g key={i}><circle cx={x} cy={y} r="16" fill={palette[i%palette.length]}/><text x={x+26} y={y+5} fontSize="12" fill="#334155">{label}</text></g>)}</Svg></Frame>;
  return <Frame title="Outcome grid" caption="Organise equally likely outcomes before counting favourable cases."><Svg>{[0,1,2,3].map(i=><g key={i}><rect x={95+i*140} y="55" width="110" height="105" rx="14" fill={palette[i]} opacity=".12" stroke={palette[i]} strokeWidth="3"/><text x={150+i*140} y="118" textAnchor="middle" fontSize="18" fontWeight="800" fill={palette[i]}>Case {i+1}</text></g>)}</Svg></Frame>;
}

function MotionVisual({ item, train=false }) {
  const vals=numbers(item.q).filter(n=>n>0).slice(0,5), circular=/circular|track|lap/i.test(item.subtopic), boat=/boat|stream|river|upstream|downstream/i.test(item.q+item.subtopic), twoTrains=/two trains/i.test(item.subtopic), routeTrain=/journey with halt|rail operation/i.test(item.subtopic);
  if(/kilometres per hour to|metres per second to/i.test(item.subtopic))return null;
  if(circular)return <Frame title="Circular-track model" caption="The marked path represents one complete lap; use relative speed in the stated direction."><Svg><ellipse cx="360" cy="112" rx="245" ry="78" fill="#f8fafc" stroke="#7c3aed" strokeWidth="12"/><circle cx="130" cy="88" r="12" fill="#ef4444"/><circle cx="170" cy="158" r="12" fill="#2563eb"/><text x="360" y="117" textAnchor="middle" fontSize="20" fontWeight="800" fill="#475569">{vals[0]??"?"} m track</text></Svg></Frame>;
  if(twoTrains)return <Frame title="Relative train crossing" caption="Add both train lengths for clearance; combine speeds according to their directions."><Svg><line x1="60" y1="172" x2="660" y2="172" stroke="#64748b" strokeWidth="5"/><g><rect x="90" y="92" width="210" height="67" rx="8" fill="#dbeafe" stroke="#2563eb" strokeWidth="4"/><circle cx="140" cy="166" r="14" fill="#334155"/><circle cx="255" cy="166" r="14" fill="#334155"/><text x="195" y="82" textAnchor="middle" fontSize="14">{vals[0]??"?"} m · {vals[2]??"?"} km/h</text></g><g><rect x="420" y="92" width="210" height="67" rx="8" fill="#fef3c7" stroke="#f59e0b" strokeWidth="4"/><circle cx="465" cy="166" r="14" fill="#334155"/><circle cx="580" cy="166" r="14" fill="#334155"/><text x="525" y="82" textAnchor="middle" fontSize="14">{vals[1]??"?"} m · {vals[3]??"?"} km/h</text></g><path d="M315 125 H395" stroke="#ef4444" strokeWidth="5" strokeDasharray="8 5"/></Svg></Frame>;
  const visualTitle=routeTrain?"Rail journey model":boat?"Stream-direction model":train?"Crossing-distance model":"Route model";
  return <Frame title={visualTitle} caption="Use the labelled lengths, speeds and directions exactly as stated; the drawing is not to scale."><Svg><line x1="80" y1="160" x2="650" y2="160" stroke="#94a3b8" strokeWidth="5"/>{boat?<><path d="M80 185 Q160 160 240 185 T400 185 T560 185" fill="none" stroke="#38bdf8" strokeWidth="6"/><path d="M275 120 L395 120 L425 145 L250 145 Z" fill="#f59e0b"/><text x="340" y="103" textAnchor="middle" fontSize="16" fill="#334155">stream → · figures {vals.slice(0,3).join(" / ")}</text></>:train?<><rect x="150" y="91" width="245" height="65" rx="8" fill="#dbeafe" stroke="#2563eb" strokeWidth="4"/><circle cx="205" cy="162" r="15" fill="#334155"/><circle cx="345" cy="162" r="15" fill="#334155"/><rect x="440" y="135" width="160" height="25" fill="#fcd34d"/><text x="272" y="82" textAnchor="middle" fontSize="15" fill="#334155">{routeTrain?`route ${vals[0]??"?"} km`:`train ${vals[0]??"?"} m`}</text></>:<><circle cx="115" cy="150" r="12" fill="#2563eb"/><circle cx="615" cy="150" r="12" fill="#ef4444"/><path d="M145 130 H560" stroke="#4f46e5" strokeWidth="5" markerEnd="url(#arrow)"/><text x="350" y="112" textAnchor="middle" fontSize="17" fill="#334155">distance {vals[0]??"?"} · speed {vals[1]??"?"}</text></>}<defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#4f46e5"/></marker></defs></Svg></Frame>;
}

function MixtureVisual({ item }) {
  const vals=numbers(item.q).filter(n=>n>=0).slice(0,8), text=(item.q+item.subtopic).toLowerCase(), commercial=/price|cost|profit|merchant|retailer|vendor/.test(text), solid=/alloy|grain|kg|tonnes|material/.test(text), alligation=/alligation/.test(text);
  if(commercial)return <Frame title="Weighted-cost inputs" caption="Keep quantity and unit cost paired; calculate total cost before dividing or applying profit."><Svg>{[0,1].map(i=>{const x=135+i*330;return <g key={i}><path d={`M${x} 65 Q${x+80} 20 ${x+160} 65 L${x+145} 185 H${x+15} Z`} fill={`${palette[i]}25`} stroke={palette[i]} strokeWidth="4"/><text x={x+80} y="112" textAnchor="middle" fontSize="15" fontWeight="800" fill="#334155">Input {i+1}</text><text x={x+80} y="140" textAnchor="middle" fontSize="13" fill="#475569">figures: {vals.slice(i*2,i*2+2).join(" · ")}</text></g>})}<text x="360" y="118" textAnchor="middle" fontSize="30" fill="#64748b">+</text></Svg></Frame>;
  if(alligation){const strengths=vals.filter(value=>value<=100).slice(0,3);return <Frame title="Alligation line" caption="Place the target strength between the weaker and stronger inputs, then cross-subtract."><Svg><line x1="120" y1="112" x2="600" y2="112" stroke="#64748b" strokeWidth="5"/>{strengths.map((value,i)=>{const x=150+i*210;return <g key={i}><circle cx={x} cy="112" r="37" fill={`${palette[i]}25`} stroke={palette[i]} strokeWidth="4"/><text x={x} y="117" textAnchor="middle" fontSize="16" fontWeight="900">{value}%</text><text x={x} y="174" textAnchor="middle" fontSize="12" fill="#64748b">{i===0?"weaker":i===1?"stronger":"target"}</text></g>})}</Svg></Frame>}
  if(solid)return <Frame title="Material blend" caption="Mass and composition stay paired for each solid input before the weighted blend is calculated."><Svg>{[0,1,2].map(i=>{const x=105+i*210;return <g key={i}><rect x={x} y="55" width="135" height="115" rx="18" fill={`${palette[i]}25`} stroke={palette[i]} strokeWidth="4"/><text x={x+67} y="103" textAnchor="middle" fontSize="14" fontWeight="800">Batch {i+1}</text><text x={x+67} y="132" textAnchor="middle" fontSize="12">{vals.slice(i*2,i*2+2).join(" · ")||"result"}</text></g>})}</Svg></Frame>;
  const volume=vals[0]??"?", concentration=vals[1]??"?", operations=vals.slice(2,5).join(" · ");
  return <Frame title="Solution-tank balance" caption="The first two labels are the stated starting volume and concentration; later figures describe the operation or target."><Svg><path d="M190 35 H430 L405 185 H215 Z" fill="#fff" stroke="#475569" strokeWidth="4"/><path d="M205 95 H415 L402 185 H218 Z" fill="#38bdf8" opacity=".45"/><text x="310" y="130" textAnchor="middle" fontSize="18" fontWeight="900" fill="#0f4c75">{volume} L · {concentration}%</text><path d="M470 112 H585" stroke="#7c3aed" strokeWidth="5" markerEnd="url(#mixArrow)"/><text x="525" y="92" textAnchor="middle" fontSize="13" fill="#475569">operation</text><text x="525" y="145" textAnchor="middle" fontSize="12" fill="#334155">{operations||"mix / replace"}</text><defs><marker id="mixArrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#7c3aed"/></marker></defs></Svg></Frame>;
}

function SetMap({ item, revealed }) {
  if(!revealed)return null;
  const premiseText=item.q.split("Conclusions:")[0], premises=[...premiseText.matchAll(/(All|Some|No)\s+([a-z]+)\s+(?:are|is)(\s+not)?\s+(?:a\s+|an\s+)?([a-z]+)/gi)].slice(0,3).map(match=>({type:`${match[1].toLowerCase()}${match[3]?"-not":""}`,a:match[2],b:match[4]}));
  return <Frame title="Solved Venn checks" caption="Each panel is a minimal diagram of one premise; combine only deductions forced across the panels."><Svg>{premises.map((premise,i)=>{const x=125+i*225;return <g key={i}><rect x={x-90} y="30" width="180" height="165" rx="14" fill="#fff" stroke="#e2e8f0" strokeWidth="2"/><text x={x} y="52" textAnchor="middle" fontSize="12" fontWeight="900" fill="#475569">{premise.type.toUpperCase()}</text>{premise.type==="all"?<><circle cx={x} cy="122" r="55" fill="#dbeafe" stroke="#2563eb" strokeWidth="3"/><circle cx={x} cy="125" r="27" fill="#ede9fe" stroke="#7c3aed" strokeWidth="3"/><text x={x} y="129" textAnchor="middle" fontSize="11" fontWeight="800">{premise.a}</text><text x={x} y="82" textAnchor="middle" fontSize="11" fontWeight="800">{premise.b}</text></>:premise.type==="no"?<><circle cx={x-38} cy="125" r="38" fill="#fee2e2" stroke="#ef4444" strokeWidth="3"/><circle cx={x+42} cy="125" r="38" fill="#dbeafe" stroke="#2563eb" strokeWidth="3"/><text x={x-38} y="130" textAnchor="middle" fontSize="10" fontWeight="800">{premise.a}</text><text x={x+42} y="130" textAnchor="middle" fontSize="10" fontWeight="800">{premise.b}</text></>:premise.type==="some-not"?<><circle cx={x+25} cy="125" r="48" fill="#dbeafe" stroke="#2563eb" strokeWidth="3"/><circle cx={x-48} cy="125" r="8" fill="#ef4444"/><text x={x+25} y="130" textAnchor="middle" fontSize="10" fontWeight="800">{premise.b}</text><text x={x-48} y="153" textAnchor="middle" fontSize="10" fontWeight="800">some {premise.a}</text></>:<><circle cx={x-25} cy="125" r="48" fill="#ede9fe" fillOpacity=".7" stroke="#7c3aed" strokeWidth="3"/><circle cx={x+25} cy="125" r="48" fill="#dbeafe" fillOpacity=".7" stroke="#2563eb" strokeWidth="3"/><circle cx={x} cy="125" r="7" fill="#ef4444"/><text x={x-47} y="130" textAnchor="middle" fontSize="10" fontWeight="800">{premise.a}</text><text x={x+47} y="130" textAnchor="middle" fontSize="10" fontWeight="800">{premise.b}</text></>}</g>})}</Svg></Frame>;
}

function FamilyMap({ item }) {
  const rows=[], add=(left,relation,right)=>{if(left&&right&&!rows.some(row=>row.left===left&&row.relation===relation&&row.right===right))rows.push({left,relation,right});};
  for(const match of item.q.matchAll(/([A-Z][a-z]+)\s+is\s+(?:the\s+)?(?:only\s+)?(mother|father|brother|sister|son|daughter|child)\s+of\s+([A-Z][a-z]+)/g))add(match[1],`${match[2]} of`,match[3]);
  for(const match of item.q.matchAll(/([A-Z][a-z]+)\s+is\s+([A-Z][a-z]+)'s\s+(?:only\s+)?(mother|father|brother|sister|son|daughter|child)/g))add(match[1],`${match[3]} of`,match[2]);
  for(const match of item.q.matchAll(/([A-Z][a-z]+)\s+is\s+married\s+to\s+([A-Z][a-z]+)/g))add(match[1],"married to",match[2]);
  for(const match of item.q.matchAll(/([A-Z][a-z]+)\s+and\s+([A-Z][a-z]+)\s+are\s+(married|sisters|brothers)/g))add(match[1],match[3]==="married"?"married to":`${match[3].slice(0,-1)} of`,match[2]);
  for(const match of item.q.matchAll(/([A-Z][a-z]+),\s+who\s+is\s+(?:the\s+)?(mother|father|brother|sister|son|daughter)\s+of\s+([A-Z][a-z]+)/g))add(match[1],`${match[2]} of`,match[3]);
  const children=item.q.match(/Their children are son ([A-Z][a-z]+) and daughter ([A-Z][a-z]+)/), spouses=item.q.match(/([A-Z][a-z]+) is married to ([A-Z][a-z]+)/);
  if(children&&spouses){add(children[1],"son of",spouses[1]);add(children[2],"daughter of",spouses[1]);}
  const people=words(item.q).filter(name=>!["Codebook","In"].includes(name)).slice(-5);
  if(/only son of my mother/i.test(item.q)&&people.length>=3){add(people[0],"sister of",people[1]);add(people[1],"father of",people[2]);}
  if(/points to.+daughter of my only son/i.test(item.q)&&people.length>=3){add(people[2],"son of",people[0]);add(people[1],"daughter of",people[2]);}
  if(/In a code/i.test(item.q)){
    const expression=item.q.match(/\bin\s+([A-Z][a-z]+)\s+\S+\s+([A-Z][a-z]+)\s+\S+\s+([A-Z][a-z]+)\??$/), coded=expression?.slice(1)??people.slice(0,3);
    rows.length=0;
    if(/Coded relation 1/i.test(item.subtopic)){add(coded[0],"brother of",coded[1]);add(coded[1],"mother of",coded[2]);}
    else {add(coded[0],"daughter of",coded[1]);add(coded[1],"father of",coded[2]);}
  }
  const displayed=rows.slice(0,4), height=displayed.length>3?305:250;
  return <Frame title="Family-relation map" caption="Each arrow preserves the exact direction of a relationship stated in the question; coded links must be decoded using its supplied legend."><Svg height={height} viewBox={`0 0 720 ${height}`}>{displayed.length?displayed.map((row,i)=>{const y=25+i*67;return <g key={`${row.left}-${row.right}-${i}`}><rect x="75" y={y} width="165" height="48" rx="12" fill={`${palette[i]}20`} stroke={palette[i]} strokeWidth="3"/><text x="157" y={y+30} textAnchor="middle" fontSize="15" fontWeight="800" fill="#334155">{row.left}</text><line x1="245" y1={y+24} x2="465" y2={y+24} stroke="#94a3b8" strokeWidth="3"/><path d={`M465 ${y+24} l-12 -7 v14 z`} fill="#94a3b8"/><text x="355" y={y+17} textAnchor="middle" fontSize="12" fontWeight="700" fill="#7c3aed">{row.relation}</text><rect x="480" y={y} width="165" height="48" rx="12" fill={`${palette[(i+2)%palette.length]}20`} stroke={palette[(i+2)%palette.length]} strokeWidth="3"/><text x="562" y={y+30} textAnchor="middle" fontSize="15" fontWeight="800" fill="#334155">{row.right}</text></g>}):people.map((name,i)=>{const x=80+i*125;return <g key={name}><rect x={x} y="82" width="108" height="54" rx="12" fill={`${palette[i]}20`} stroke={palette[i]} strokeWidth="3"/><text x={x+54} y="114" textAnchor="middle" fontSize="13" fontWeight="800" fill="#334155">{name}</text></g>})}</Svg></Frame>;
}

function DirectionMap({ item }) {
  const moves=[...item.q.matchAll(/(\d+(?:\.\d+)?)\s*m\s*(north|south|east|west)/gi)].map(m=>({n:Number(m[1]),d:m[2].toLowerCase()}));
  let x=0,y=0,pts=[[0,0]];for(const move of moves){if(move.d==="north")y+=move.n;if(move.d==="south")y-=move.n;if(move.d==="east")x+=move.n;if(move.d==="west")x-=move.n;pts.push([x,y]);}
  const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),map=([px,py])=>[90+(px-minX)/(maxX-minX||1)*500,180-(py-minY)/(maxY-minY||1)*125],line=pts.map(map).map(p=>p.join(",")).join(" ");
  return <Frame title="Route map" caption="The polyline follows every movement in order; the dashed line is the final displacement."><Svg><text x="630" y="35" fontSize="13" fill="#334155">N ↑</text><polyline points={line} fill="none" stroke="#4f46e5" strokeWidth="6" strokeLinejoin="round" strokeLinecap="round"/>{pts.map((p,i)=>{const [cx,cy]=map(p);return <g key={i}><circle cx={cx} cy={cy} r={i===0||i===pts.length-1?8:5} fill={i===0?"#10b981":i===pts.length-1?"#ef4444":"#4f46e5"}/><text x={cx+8} y={cy-8} fontSize="11" fill="#475569">{i===0?"Start":i===pts.length-1?"Finish":i}</text></g>})}{pts.length>1&&<line x1={map(pts[0])[0]} y1={map(pts[0])[1]} x2={map(pts.at(-1))[0]} y2={map(pts.at(-1))[1]} stroke="#ef4444" strokeWidth="3" strokeDasharray="7 5"/>}</Svg></Frame>;
}

function SeatingMap({ item, revealed }) {
  const circular=/circular table/i.test(item.q), orderMatch=item.solution.match(/(?:order is|order, up to rotation, is|schedule is)\s+([A-Za-z]+(?:\s*(?:–|→|>|,|=)\s*[A-Za-z]+){5})/i), parsed=orderMatch?.[1].split(/\s*(?:–|→|>|,|=)\s*/).filter(Boolean), namesInSolution=parsed?.length>=6?parsed:words(item.solution).filter(name=>words(item.q).includes(name)).slice(0,6), labels=revealed&&namesInSolution.length>=6?namesInSolution:Array.from({length:6},(_,i)=>`Seat ${i+1}`);
  return <Frame title={revealed?"Solved seating layout":"Seating workspace"} caption={revealed?"Use the final layout to verify neighbours, positions and opposite seats.":"Numbered seats are provided as a scratch layout; place candidates from the constraints."}><Svg>{circular?<><ellipse cx="360" cy="112" rx="145" ry="70" fill="#f1f5f9" stroke="#7c3aed" strokeWidth="4"/>{labels.map((label,i)=>{const a=Math.PI*2*i/6-Math.PI/2,x=360+225*Math.cos(a),y=112+92*Math.sin(a);return <g key={i}><circle cx={x} cy={y} r="34" fill="#fff" stroke={palette[i]} strokeWidth="4"/><text x={x} y={y+4} textAnchor="middle" fontSize="11" fontWeight="800" fill="#334155">{label}</text></g>})}</>:labels.map((label,i)=>{const x=48+i*108;return <g key={i}><rect x={x} y="74" width="92" height="76" rx="13" fill="#fff" stroke={palette[i]} strokeWidth="4"/><text x={x+46} y="116" textAnchor="middle" fontSize="11" fontWeight="800" fill="#334155">{label}</text><text x={x+46} y="174" textAnchor="middle" fontSize="12" fill="#64748b">{i+1}</text></g>})}</Svg></Frame>;
}

function ScheduleGrid({ item, revealed }) {
  const days=["Mon","Tue","Wed","Thu","Fri","Sat"], assignments=[...item.solution.matchAll(/(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday)=([A-Za-z]+)/g)].map(match=>match[1]), projectNames=assignments.length>=6?assignments:words(item.q).filter(word=>!days.includes(word.slice(0,3))).slice(0,6), labels=revealed&&projectNames.length>=6?projectNames:Array(6).fill("?");
  return <Frame title={revealed?"Solved schedule grid":"Scheduling grid"} caption={revealed?"Read the final allocation from left to right and recheck every gap condition.":"Fill fixed days first, then exact gaps, followed by general before/after conditions."}><Svg>{days.map((day,i)=>{const x=45+i*110;return <g key={day}><rect x={x} y="58" width="96" height="104" rx="10" fill={labels[i]==="?"?"#f8fafc":`${palette[i]}18`} stroke={palette[i]} strokeWidth="3"/><text x={x+48} y="86" textAnchor="middle" fontSize="13" fontWeight="900" fill={palette[i]}>{day}</text><text x={x+48} y="126" textAnchor="middle" fontSize="11" fontWeight="700" fill="#334155">{labels[i]}</text></g>})}</Svg></Frame>;
}

function ClockFace({ item }) {
  const match=item.q.match(/(?:At|time is|actual time is)\s*(\d{1,2}):(\d{2})/i),h=Number(match?.[1]??10),m=Number(match?.[2]??10),minute=-Math.PI/2+m/60*2*Math.PI,hour=-Math.PI/2+(h%12+m/60)/12*2*Math.PI;
  const hand=(angle,length)=>[360+Math.cos(angle)*length,112+Math.sin(angle)*length];const mp=hand(minute,75),hp=hand(hour,48);
  return <Frame title="Analogue clock" caption={`Clock face drawn for ${h}:${String(m).padStart(2,"0")}; the hour hand includes its minute-by-minute movement.`}><Svg><circle cx="360" cy="112" r="103" fill="#fff" stroke="#7c3aed" strokeWidth="5"/>{Array.from({length:12},(_,i)=>{const a=-Math.PI/2+i/12*2*Math.PI,x=360+Math.cos(a)*88,y=112+Math.sin(a)*88;return <text key={i} x={x} y={y+5} textAnchor="middle" fontSize="13" fill="#475569">{i||12}</text>})}<line x1="360" y1="112" x2={hp[0]} y2={hp[1]} stroke="#0f172a" strokeWidth="7" strokeLinecap="round"/><line x1="360" y1="112" x2={mp[0]} y2={mp[1]} stroke="#ef4444" strokeWidth="4" strokeLinecap="round"/><circle cx="360" cy="112" r="7" fill="#4f46e5"/></Svg></Frame>;
}

function CalendarVisual({ item }) {
  const dateMatch=item.q.match(/(\d{2})-(\d{2})-(\d{4})/), vals=numbers(item.q), highlighted=Number(dateMatch?.[1]??0), month=Number(dateMatch?.[2]??1), year=Number(dateMatch?.[3]??vals.find(value=>value>1900)??new Date().getFullYear()), weekdays=["S","M","T","W","T","F","S"], firstWeekday=dateMatch?new Date(Date.UTC(year,month-1,1)).getUTCDay():0, daysInMonth=dateMatch?new Date(Date.UTC(year,month,0)).getUTCDate():31;
  return <Frame title={/leap/i.test(item.q)?"Leap-year timeline":"Calendar workspace"} caption={/leap/i.test(item.q)?"Apply the complete divisibility-by-4, century and 400-year rules to the shown interval.":"Reduce day shifts modulo seven and mark the target date on the weekday grid."}><Svg>
    {/leap/i.test(item.q)?<>
      {Array.from({length:6},(_,i)=>{const y=(vals[0]??year)+i*4;return <g key={y}><circle cx={95+i*105} cy="105" r="28" fill={y%400===0||(y%4===0&&y%100!==0)?"#dcfce7":"#f1f5f9"} stroke={palette[i]} strokeWidth="3"/><text x={95+i*105} y="110" textAnchor="middle" fontSize="13" fontWeight="800" fill="#334155">{y}</text></g>})}
      <line x1="95" y1="145" x2="620" y2="145" stroke="#94a3b8" strokeWidth="3"/>
    </>:<>
      {weekdays.map((day,i)=><text key={i} x={170+i*62} y="36" textAnchor="middle" fontSize="13" fontWeight="900" fill="#64748b">{day}</text>)}
      {Array.from({length:daysInMonth},(_,i)=>{const day=i+1,slot=firstWeekday+i,x=140+(slot%7)*62,y=48+Math.floor(slot/7)*32,active=day===highlighted;return <g key={i}><rect x={x} y={y} width="58" height="28" rx="5" fill={active?"#ede9fe":"#f8fafc"} stroke={active?"#7c3aed":"#e2e8f0"}/><text x={x+29} y={y+19} textAnchor="middle" fontSize="11" fontWeight={active?"900":"500"} fill="#334155">{day}</text></g>})}
      <text x="70" y="118" textAnchor="middle" fontSize="18" fontWeight="900" fill="#7c3aed">{dateMatch?`${dateMatch[2]}/${year}`:`+${vals.at(-1)??"n"} days`}</text>
    </>}
  </Svg></Frame>;
}

function SpatialVisual({ item }) {
  const vals=numbers(item.q);
  if(/cube net/.test(item.q.toLowerCase())){const faceLabels=unique([...item.q.matchAll(/\b[A-F]\d?\b/g)].map(match=>match[0])).slice(0,6);while(faceLabels.length<6)faceLabels.push(String.fromCharCode(65+faceLabels.length));return <Frame title="Cube net" caption="Trace shared edges before identifying opposite faces."><Svg>{[[260,75],[330,75],[400,75],[470,75],[330,5],[330,145]].map(([x,y],i)=><g key={i}><rect x={x} y={y} width="70" height="70" fill={`${palette[i]}22`} stroke={palette[i]} strokeWidth="3"/><text x={x+35} y={y+41} textAnchor="middle" fontSize="16" fontWeight="800">{faceLabels[i]}</text></g>)}</Svg></Frame>}
  if(/paper|fold/.test(item.q.toLowerCase()))return <Frame title="Paper-fold model" caption="Each half-fold doubles the layer count; punches away from creases reproduce symmetrically."><Svg>{[0,1,2].map(i=><rect key={i} x={220+i*18} y={35+i*15} width="280" height="145" rx="4" fill="#ede9fe" stroke="#7c3aed" strokeWidth="3" opacity={.45+i*.2}/>)}<circle cx="380" cy="112" r="10" fill="#ef4444"/><text x="360" y="207" textAnchor="middle" fontSize="14" fill="#475569">folds/layers from question: {vals.slice(0,2).join(" · ")}</text></Svg></Frame>;
  if(/arrow|rotation/.test(item.q.toLowerCase()))return <Frame title="Rotation tracker" caption="Reduce repeated rotations modulo four quarter-turns."><Svg>{[0,1,2,3].map((_,i)=><g key={i} transform={`translate(${165+i*135} 110) rotate(${i*90})`}><path d="M-35 8 H25 V27 L60 0 L25 -27 V-8 H-35 Z" fill={palette[i]}/></g>)}</Svg></Frame>;
  if(/figure series/.test(item.q.toLowerCase())){const shapes=[...item.q.matchAll(/(circle|triangle|square|star|pentagon|diamond)/gi)].map(m=>m[1]).slice(0,5);return <Frame title="Figure sequence" caption="Track the constant jump through the stated shape cycle."><Svg>{shapes.map((shape,i)=><g key={i}><rect x={65+i*125} y="62" width="95" height="95" rx="16" fill={`${palette[i]}18`} stroke={palette[i]} strokeWidth="3"/><text x={112+i*125} y="116" textAnchor="middle" fontSize="13" fontWeight="800" fill="#334155">{shape}</text>{i<4&&<text x={174+i*125} y="116" fontSize="22" fill="#64748b">→</text>}</g>)}</Svg></Frame>}
  return <Frame title="Painted-cube model" caption="Separate corner, edge, face-centre and internal cubes before counting."><Svg><path d="M255 65 L390 28 L495 83 L360 122 Z M255 65 V165 L360 208 V122 M360 208 L495 165 V83" fill="#dbeafe" stroke="#2563eb" strokeWidth="4"/><path d="M300 53 V180 M345 41 V198 M405 36 V193 M450 60 V180 M255 100 L360 142 L495 103 M255 135 L360 172 L495 135" fill="none" stroke="#60a5fa" strokeWidth="2" opacity=".8"/></Svg></Frame>;
}

export default function QuestionVisual({ item, kind, revealed=false }) {
  if(!item || !supportsQuestionVisual(kind))return null;
  if(kind==="dataInterpretation")return <DataChart item={item}/>;
  if(kind==="mensuration")return <Geometry item={item}/>;
  if(kind==="probability")return <ProbabilityVisual item={item}/>;
  if(kind==="distance")return <MotionVisual item={item}/>;
  if(kind==="trainsBoats")return <MotionVisual item={item} train/>;
  if(kind==="mixture")return <MixtureVisual item={item}/>;
  if(kind==="syllogisms")return <SetMap item={item} revealed={revealed}/>;
  if(kind==="bloodRelations")return <FamilyMap item={item}/>;
  if(kind==="directionSense")return <DirectionMap item={item}/>;
  if(kind==="seatingArrangements")return <SeatingMap item={item} revealed={revealed}/>;
  if(kind==="analyticalPuzzles")return <ScheduleGrid item={item} revealed={revealed}/>;
  if(kind==="clocksCalendars")return /clock|analogue|mirror/i.test(item.q)?<ClockFace item={item}/>:<CalendarVisual item={item}/>;
  if(kind==="nonVerbalSpatial")return <SpatialVisual item={item}/>;
  return null;
}
