import { buildLogicalBank } from "./LogicalQuestionFactory.js";

const make=(subtopic,argument,correct,distractors,explanation,style="contextual")=>({
  subtopic,prompt:`Argument: ${argument} Which option states the assumption or inference most strongly supported by the argument?`,
  correct,distractors,explanation,assessmentStyle:style,
  shortcut:"Use the denial test for assumptions: negate an option and check whether the argument's recommendation or claim collapses.",
  commonMistake:"Do not select an attractive consequence that is stronger than the evidence or merely repeats background information.",
});

const patterns=[
v=>make("Recommendation feasibility",`The company should move Training ${v} online because this will reduce venue expenses.`,`The online format can deliver the required training without venue use.`,["Every employee prefers online learning.","Venue expenses are the company's largest cost.","Online training has no implementation cost."],"The saving claim requires training to remain deliverable without the venue; preferences, cost ranking, and zero setup cost are unnecessary."),
v=>make("Advertisement need",`Use App ${v} to receive instant alerts about placement deadlines.`,`Some intended users value receiving placement-deadline alerts promptly.`,["All other apps provide incorrect alerts.","Every placement deadline changes daily.","The app guarantees selection in placements."],"An advertisement for alerts presumes a relevant user need, not competitor failure, daily changes, or a selection guarantee."),
v=>make("Policy effectiveness",`Installing access gates will reduce unauthorised entry into Building ${v}.`,`A meaningful portion of unauthorised entry currently occurs through points the gates can control.`,["No authorised person will ever forget a badge.","The building has no other security measure.","Unauthorised entry will become impossible."],"The proposed control must address an actual route of entry; perfection and absence of other controls are not required."),
v=>make("Causal inference limitation",`Teams using Tool ${v} finished projects faster in an observational report.`,`Tool use and faster completion were associated in the observed teams.`,["The tool caused every improvement.","Teams without the tool were poorly managed.","The tool will improve every future project."],"The observation supports association, while causal and universal predictions exceed the evidence."),
v=>make("Survey inference",`${65+v}% of ${400+20*v} surveyed graduates preferred flexible work.`,`A majority of the surveyed graduates preferred flexible work.`,["A majority of all graduates everywhere prefer flexible work.","Flexible work raises productivity.","Every respondent understood flexible work identically."],"The percentage supports a claim only about the surveyed sample, not the global population or causal effects."),
v=>make("Budget proposal",`The department should lease Device ${v} rather than buy it because the project lasts only six months.`,`The six-month leasing cost is expected to be lower than the relevant cost of purchasing for this project.`,["The device will have no use after six months.","Purchased devices cannot be sold.","Leasing is always cheaper than buying."],"The recommendation needs a project-specific cost advantage, not universal superiority or zero residual value."),
v=>make("Training prerequisite",`Only employees who understand SQL should join Workshop ${v}, because exercises begin with database queries.`,`Participants without SQL knowledge may be unable to follow the starting exercises.`,["Every SQL user needs the workshop.","Database queries are the only workshop content.","SQL is harder than every other skill."],"The entry restriction assumes the starting work requires existing SQL comprehension; the other claims are unnecessary."),
v=>make("Capacity decision",`A second support shift should be added because average wait time exceeded ${10+v} minutes for four weeks.`,`Additional staffed capacity can reduce at least part of the observed waiting delay.`,["Every delay is caused by staff shortage.","Customers will leave after exactly ${10+v} minutes.","The first shift performs no useful work."],"Adding a shift is relevant only if capacity affects delay; it need not be the sole cause."),
v=>make("Forecast inference",`Demand for Product ${v} increased in each of the last ${3+v} months, so the planner expects another increase next month.`,`The planner treats the recent upward pattern as relevant to the next month.`,["Demand can never decrease.","No external factor affects demand.","The next increase will equal the previous one."],"A forecast extrapolates relevance of the recent trend without requiring certainty or equal increments."),
v=>make("Safety instruction",`Wear insulated gloves while servicing Panel ${v}.`,`Servicing the panel may expose a worker to a hazard that insulated gloves help reduce.`,["Gloves remove every electrical hazard.","Only untrained workers need gloves.","The panel is always energised."],"The instruction presumes a mitigable risk, not perfect protection or continuous energisation."),
v=>make("Comparison argument",`Plan A${v} is preferable because it delivers the same output as Plan B${v} at lower cost.`,`Output quality and other relevant conditions are sufficiently comparable between the plans.`,["Plan A has zero risk.","Plan B is unaffordable.","Cost is the only factor anyone values."],"The cost comparison supports preference only when relevant outputs and conditions are comparable."),
v=>make("Hiring criterion",`Role ${v} requires night-shift availability; therefore candidates unavailable at night should not be shortlisted.`,`Night-shift availability is necessary for performing the role as currently designed.`,["Night work is more productive.","All candidates prefer day shifts.","The role can never be redesigned."],"The screening rule depends on current role necessity, not productivity, preferences, or permanent design."),
v=>make("Process automation",`Automate Report ${v} to reduce repetitive manual effort.`,`A material part of producing the report consists of repeatable steps suitable for automation.`,["Automation makes no errors.","No judgement is required anywhere in reporting.","Manual work has no value."],"The proposal requires automatable repetition, not total elimination of judgement or error."),
v=>make("Pilot programme",`Run a small pilot before rolling System ${v} out company-wide.`,`Results from a limited implementation can reveal information relevant to a wider rollout.`,["The full rollout will fail.","Pilots cost nothing.","All departments are identical."],"A pilot is useful because it can reduce uncertainty; it does not assume failure, zero cost, or identical settings."),
v=>make("Price reduction",`Lowering the price of Subscription Plan ${v} should increase sign-ups.`,`Some potential customers are discouraged by the current price.`,["Price is the only reason anyone declines.","Every existing subscriber will remain.","Lower prices always increase total profit."],"The demand response needs price-sensitive prospects, not price as the sole barrier or guaranteed profit."),
v=>make("Data backup",`Create an off-site backup of Dataset ${v} to protect against a local-site disaster.`,`A local disaster could make the primary data and local backups unavailable together.`,["The primary site will certainly fail.","Off-site storage can never fail.","The dataset changes every minute."],"Off-site protection is relevant because correlated local loss is possible, not certain."),
v=>make("Meeting reduction",`For Team ${v}, replace the weekly status meeting with a written update to save team time.`,`A written update can communicate the status information adequately for its intended purpose.`,["Meetings never create value.","Everyone reads every message immediately.","No discussion will ever be needed."],"The substitution requires adequate information transfer, not the elimination of all meeting value or discussion."),
v=>make("Location choice",`Open Service Desk ${v} near the main entrance because most visitors pass through it.`,`Being near a route used by most visitors improves accessibility to the desk.`,["Every visitor needs the desk.","No visitor uses another entrance.","Rent is identical everywhere."],"The location argument connects traffic to accessibility; universal usage and equal rent are unnecessary."),
v=>make("Exam preparation",`Students should practise timed sets because the assessment allows about ${30+v} seconds per item.`,`Performance depends partly on solving accurately under limited time.`,["Untimed practice has no benefit.","Every item requires exactly ${30+v} seconds.","Speed matters more than correctness."],"Timed practice is justified when time pressure is relevant, without denying untimed learning or accuracy."),
v=>make("Customer retention",`Call customers from Segment ${v} who cancelled this month to learn why they left.`,`At least some former customers can provide information useful for understanding cancellations.`,["Every cancellation has the same cause.","All former customers will return after a call.","Current customers have no useful feedback."],"The research action assumes informative feedback is possible, not uniform causes or guaranteed recovery."),
v=>make("Maintenance schedule",`Inspect Machine ${v} before the peak season to reduce unexpected downtime.`,`Pre-season inspection can detect or prevent some faults that might otherwise cause downtime.`,["Inspection prevents every failure.","The machine currently has a fault.","Peak-season downtime is always more expensive."],"Preventive maintenance relies on partial detectability or prevention, not certainty or known existing failure."),
v=>make("Performance dashboard",`Publish Team ${v} metrics monthly so managers can identify emerging problems earlier.`,`Monthly visibility can reveal relevant changes before they would otherwise be noticed.`,["Metrics explain every problem.","Managers currently notice nothing.","Publishing data automatically fixes problems."],"The dashboard must improve detection timing; explanation and automatic correction are stronger claims."),
v=>make("Flexible deadline",`Extend the application deadline because the portal was unavailable for ${2+v} hours.`,`The outage may have prevented some otherwise eligible applicants from submitting on time.`,["Every applicant waited until the final hours.","The outage was intentional.","No application submitted before the outage is valid."],"Fairness rationale requires possible obstruction for some applicants, not universal last-minute behaviour."),
v=>make("Prototype decision",`Build a prototype of Feature ${v} before committing the full engineering budget.`,`Prototype results can reduce uncertainty about feasibility or user response.`,["The feature is infeasible.","A prototype contains every production capability.","Engineering estimates are always wrong."],"The staged decision assumes learning value under uncertainty, not expected failure or complete equivalence."),
v=>make("Observed decline inference",`Complaints fell from ${120+10*v} to ${90+8*v} after the support guide was released, with no controlled comparison.`,`Recorded complaints were lower in the later period.`,["The guide alone caused the decline.","Customer satisfaction certainly increased.","The decline will continue at the same rate."],"The data establish the recorded before-after difference only; cause, satisfaction, and future continuation are not forced."),
];

export const assumptionInferenceLogicalBank=()=>buildLogicalBank(patterns);
