import { buildLogicalBank } from "./LogicalQuestionFactory.js";

const statuses=["Only conclusion I follows","Only conclusion II follows","Both conclusions follow","Neither conclusion follows"];
const make=(subtopic,statement,first,second,answer,explanation)=>({
  subtopic,prompt:`Statement: ${statement} Conclusions: I. ${first} II. ${second} Choose what necessarily follows from the statement alone.`,
  correct:statuses[answer],distractors:statuses.filter((_,i)=>i!==answer),explanation,assessmentStyle:"multi-step",
  shortcut:"Separate what is explicitly forced from what is merely plausible; test conclusions I and II independently.",
  commonMistake:"Do not use outside knowledge, convert a one-way condition, or infer causes from a reported outcome.",
});

const patterns=[
v=>make("Policy implication",`Every employee completing Level ${v} security training receives system access. Riya completed that training.`,`Riya receives system access.`,`Everyone with system access completed Level ${v} training.`,0,"The policy and Riya's completion force access by modus ponens; the reverse direction is not stated."),
v=>make("Fixed-volume revenue",`A product's price rose by ${10+v}% while the number of units sold remained unchanged.`,`Total sales revenue increased.`,`The company's profit necessarily increased.`,0,"Revenue equals price times unchanged volume, so it rises; profit also depends on costs, which are not supplied."),
v=>make("Entry requirement",`No person may enter Lab ${v} without an active identity badge. Arun entered Lab ${v}.`,`Arun had an active identity badge.`,`Every badge holder entered the lab.`,0,"Entry establishes the necessary badge condition; possessing a badge does not force a person to enter."),
v=>make("Threshold rule",`Applicants scoring at least ${60+v} are shortlisted. Kavya scored ${70+v}.`,`Kavya is shortlisted.`,`Every applicant scoring below ${60+v} is rejected.`,0,"Kavya satisfies the sufficient threshold; the statement does not define every outcome below the threshold."),
v=>make("Exclusive selection",`Exactly one of Project A${v} and Project B${v} will be funded. Project A${v} will not be funded.`,`Project B${v} will be funded.`,`Both projects will be funded.`,0,"Exactly-one plus not-A forces B; funding both contradicts the exclusive condition."),
v=>make("Subset existence",`All remote auditors submit digital logs, and some analysts are remote auditors in Unit ${v}.`,`Some analysts submit digital logs.`,`All analysts submit digital logs.`,0,"The witnessed analysts inside remote auditors inherit log submission; analysts outside that subset remain unrestricted."),
v=>make("Contrapositive alert",`Whenever Server ${v} fails, the monitoring console displays an alert. No alert was displayed.`,`Server ${v} did not fail.`,`An alert can occur only after server failure.`,0,"No alert denies the necessary consequence and therefore rules out failure; the converse cause restriction is unstated."),
v=>make("Survey majority",`In a valid survey of ${500+50*v} users, more than half preferred Interface X to Interface Y.`,`Interface X received more responses than Interface Y.`,`Interface X is objectively better for every user.`,0,"A majority comparison forces the first numerical conclusion; objective universal superiority is not measured."),
v=>make("Stock balance",`During Week ${v}, inventory decreased even though new stock was received and there was no damage.`,`Units issued exceeded units received.`,`Customer demand necessarily increased over the previous week.`,0,"With no damage, net decline requires issues greater than receipts; prior-week demand is not given."),
v=>make("Bonus condition",`If Team ${v} completes the release on time, every member receives a bonus. No member received a bonus.`,`The team did not complete the release on time.`,`The team completed the release but management withheld the bonus.`,0,"The absent necessary outcome supports the contrapositive not-on-time conclusion; withholding contradicts the stated rule."),
v=>make("Minimum capacity",`Room ${v} can hold at most ${30+v} people. Exactly ${30+v} people are already inside.`,`No additional person may enter without someone leaving.`,`The room contains fewer than ${30+v} people.`,0,"The room is at its stated maximum, so an extra entrant requires an exit; the second conclusion contradicts the exact count."),
v=>make("Mutual exclusion",`No encrypted file in Folder ${v} is publicly readable. File K is encrypted and stored there.`,`File K is not publicly readable.`,`Some publicly readable files are encrypted.`,0,"K belongs to the excluded encrypted set, while the second conclusion contradicts the no-overlap rule."),
v=>make("Two-stage requirement",`A candidate is interviewed only if the aptitude test is cleared, and is offered a role only if the interview is cleared. Nila received an offer in Cycle ${v}.`,`Nila cleared the interview.`,`Nila cleared the aptitude test.`,2,"Offer requires interview clearance, and reaching the interview requires aptitude clearance, so both prerequisites follow."),
v=>make("Exact ranking",`In a five-team table, Team P${v} ranks above Q${v}, and Q${v} ranks above R${v}.`,`P${v} ranks above R${v}.`,`R${v} ranks above P${v}.`,0,"The transitive order P above Q above R forces P above R and excludes the reverse."),
v=>make("Partial order ambiguity",`A${v} finished before B${v}, while C${v} finished before D${v}.`,`A${v} finished before D${v}.`,`C${v} finished before B${v}.`,3,"The two order chains are disconnected, so neither cross-chain comparison is forced."),
v=>make("Average constraint",`The average score of Batch ${v} is ${70+v}.`,`At least one score is ${70+v} or higher.`,`Every score equals ${70+v}.`,0,"An average cannot exceed all observations, so at least one reaches it; equal individual scores are not required."),
v=>make("Percentage partition",`${40+v}% of the registered candidates are women and the remainder are men.`,`Men form ${60-v}% of the registered candidates.`,`Women outnumber men.`,0,"Complementary percentages force the first value; for these inputs women remain below half, so the second does not follow."),
v=>make("Either-or evidence",`Either Module X${v} or Module Y${v}, but not both, caused the observed error. Module Y${v} was inactive.`,`Module X${v} caused the error.`,`Module Y${v} caused the error.`,0,"The exclusive alternative and inactive Y leave X as the only permitted cause."),
v=>make("Universal negative conversion",`No temporary account is allowed to approve payments in System ${v}.`,`No payment approver is a temporary account.`,`Some permanent accounts approve payments.`,0,"A no-overlap statement converts safely, but it does not assert that any approver exists."),
v=>make("Some statement conversion",`Some quality reviewers in Plant ${v} are engineers.`,`Some engineers are quality reviewers.`,`All engineers are quality reviewers.`,0,"A particular affirmative converts, proving the same overlap; it cannot be expanded into a universal relation."),
v=>make("Causal restraint",`After a new checklist was introduced, reported defects fell by ${5+v}%. No other information was collected.`,`The defect count was lower after introduction.`,`The checklist alone caused the entire reduction.`,0,"The before-after observation supports a lower count but cannot isolate causation without controls."),
v=>make("Necessary condition",`A valid expense claim must include a receipt. Claim C${v} does not include a receipt.`,`Claim C${v} is not valid.`,`Every claim with a receipt is valid.`,0,"Missing a necessary condition rules out validity; presence of one necessary item is not sufficient for validity."),
v=>make("Upper-bound inference",`No delivery in Route ${v} took more than ${40+v} minutes.`,`Every delivery took at most ${40+v} minutes.`,`At least one delivery took exactly ${40+v} minutes.`,0,"The upper bound restates the first conclusion, while equality at the boundary is not guaranteed."),
v=>make("Conditional chain",`If demand rises, production increases; if production increases, overtime is scheduled. Demand rose in Month ${v}.`,`Production increased.`,`Overtime was scheduled.`,2,"Demand activates the first implication, whose result activates the second, forcing both conclusions."),
v=>make("Insufficient correlation",`Branches with higher training hours tended to show higher sales in Quarter ${v}.`,`Training hours and sales were positively associated in the observation.`,`Increasing training hours will certainly raise every branch's sales.`,0,"The reported tendency supports association only; it does not prove a universal causal guarantee."),
];

export const statementConclusionLogicalBank=()=>buildLogicalBank(patterns);
